// DEPS: hashes util crypto
// Host tests for src/crypto.cpp. Expected values:
//   * official vectors: RFC 6979 A.2.5 (P-256/SHA-256), BIP-32 test vector 1 (keys/chain codes decoded from the
//     BIP's base58check xprv/xpub strings), SLIP-0010 nist256p1 test vector 1 + derivation/seed retry vectors,
//     RFC 4231 HMAC vectors, FIPS 180-4 SHA-512 examples, secp256k1 key 1 -> 0x7E5F4552...5Bdf
//   * crypto_vectors.h: generated by tools/ref_crypto.py (independent pure-Python EC/RFC6979/BIP32/SLIP10,
//     itself self-tested against the official vectors above), regenerate with `python tools/ref_crypto.py gen`
#include <cstdio>
#include <ctime>
#include <string>
#include <vector>

#include "check.h"
#include "crypto.h"
#include "crypto_vectors.h"
#include "hashes.h"
#include "util.h"

using namespace ripar;

namespace ripar {
namespace crypto_test {  // host-only hook in crypto.cpp (RIPAR_HOST_TEST): RFC 6979 ECDSA without low-s
bool ecdsa_sign_raw(Curve c, const uint8_t priv[32], const uint8_t digest[32], uint8_t rs[64], int* recid,
                    uint8_t k_out[32]);
bool rfc6979_candidate(Curve c, const uint8_t priv[32], const uint8_t digest[32], unsigned index, uint8_t k[32]);
}
}  // namespace ripar

static Bytes HX(const char* s) {
  Bytes b;
  if (!from_hex(s, b)) {
    std::printf("test bug: bad hex literal %s\n", s);
    b.clear();
  }
  return b;
}

static const uint8_t* S(const char* s) { return reinterpret_cast<const uint8_t*>(s); }

static Curve curve_of(int c) { return c ? Curve::P256 : Curve::Secp256k1; }

static std::string addr_hex(const Addr& a) { return to_hex(a.v, 20, false); }

// compressed SEC1 point from X||Y
static std::string compressed(const uint8_t xy[64]) {
  uint8_t c[33];
  c[0] = uint8_t(0x02 | (xy[63] & 1));
  std::memcpy(c + 1, xy, 32);
  return to_hex(c, 33, false);
}

static bool is_low_s(Curve c, const uint8_t rs[64]) {
  static const char* HALF_K1 = "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0";
  static const char* HALF_P1 = "7fffffff800000007fffffffffffffffde737d56d38bcf4279dce5617e3192a8";
  Bytes half = HX(c == Curve::P256 ? HALF_P1 : HALF_K1);
  return std::memcmp(rs + 32, half.data(), 32) <= 0;
}

// xorshift64* for the self-consistency round trips
static uint64_t g_rng = 0x9E3779B97F4A7C15ull;
static uint8_t rnd8() {
  g_rng ^= g_rng >> 12;
  g_rng ^= g_rng << 25;
  g_rng ^= g_rng >> 27;
  return uint8_t((g_rng * 0x2545F4914F6CDD1Dull) >> 56);
}
static void rnd(uint8_t* p, size_t n) {
  for (size_t i = 0; i < n; i++) p[i] = rnd8();
}

// ------------------------------------------------------------------------------------------------ hashes
static void test_sha512_hmac() {
  CHECK_SECTION("sha512 FIPS 180-4 examples");
  uint8_t d[64];
  sha512(S(""), 0, d);
  CHECK_EQ_HEX(d, 64,
               "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd4"
               "7417a81a538327af927da3e");
  sha512(nullptr, 0, d);
  CHECK_EQ_HEX(d, 64,
               "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd4"
               "7417a81a538327af927da3e");
  sha512(S("abc"), 3, d);
  CHECK_EQ_HEX(d, 64,
               "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d44236"
               "43ce80e2a9ac94fa54ca49f");
  {
    std::vector<uint8_t> a(1000000, 'a');
    sha512(a.data(), a.size(), d);
    CHECK_EQ_HEX(d, 64,
                 "e718483d0ce769644e2e42c7bc15b4638e1f98b13b2044285632a803afa973ebde0ff244877ea60a4cb0432ce577c31beb009c5c2"
                 "c49aa2e4eadb217ad8cc09b");
  }

  CHECK_SECTION("HMAC RFC 4231 cases 1 and 6");
  {
    uint8_t k1[20];
    std::memset(k1, 0x0b, sizeof(k1));
    uint8_t o32[32], o64[64];
    hmac_sha256(k1, 20, S("Hi There"), 8, o32);
    CHECK_EQ_HEX(o32, 32, "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7");
    hmac_sha512(k1, 20, S("Hi There"), 8, o64);
    CHECK_EQ_HEX(o64, 64,
                 "87aa7cdea5ef619d4ff0b4241a1d6cb02379f4e2ce4ec2787ad0b30545e17cdedaa833b7d6b8a702038b274eaea3f4e4be9d914ee"
                 "b61f1702e696c203a126854");
    uint8_t k6[131];
    std::memset(k6, 0xaa, sizeof(k6));
    const char* m6 = "Test Using Larger Than Block-Size Key - Hash Key First";
    hmac_sha256(k6, 131, S(m6), std::strlen(m6), o32);
    CHECK_EQ_HEX(o32, 32, "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54");
    hmac_sha512(k6, 131, S(m6), std::strlen(m6), o64);
    CHECK_EQ_HEX(o64, 64,
                 "80b24263c7c1a3ebb71493c1dd7be8b49b46d1f41b4aeec1121b013783f8f3526b56d037e05f2598bd0fd2215d6a1e5295e64f73f"
                 "63f0aec8b915a985d786598");
  }

  CHECK_SECTION("sha512 / HMAC over block-boundary lengths (hashlib)");
  for (const HashVec& v : HASH_VECS) {
    std::vector<uint8_t> key(v.klen), msg(v.mlen);
    for (size_t i = 0; i < key.size(); i++) key[i] = uint8_t(i * 13 + 7);
    for (size_t i = 0; i < msg.size(); i++) msg[i] = uint8_t(i * 7 + 3);
    uint8_t o32[32], o64[64];
    sha512(msg.data(), msg.size(), o64);
    CHECK_EQ_HEX(o64, 64, v.sha512);
    hmac_sha256(key.data(), key.size(), msg.data(), msg.size(), o32);
    CHECK_EQ_HEX(o32, 32, v.hmac_sha256);
    hmac_sha512(key.data(), key.size(), msg.data(), msg.size(), o64);
    CHECK_EQ_HEX(o64, 64, v.hmac_sha512);
  }

  CHECK_SECTION("HMAC output aliasing key / message");
  {
    uint8_t buf[64], ref[64];
    for (int i = 0; i < 64; i++) buf[i] = uint8_t(i);
    hmac_sha256(buf, 32, buf + 32, 32, ref);
    hmac_sha256(buf, 32, buf + 32, 32, buf);  // out == key
    CHECK_EQ_BYTES(buf, ref, 32);
    for (int i = 0; i < 64; i++) buf[i] = uint8_t(i);
    hmac_sha256(buf + 32, 32, buf, 32, buf);  // out == msg
    hmac_sha256(ref, 0, ref, 0, ref);         // (just must not crash with empty key/msg)
    uint8_t buf2[64];
    for (int i = 0; i < 64; i++) buf2[i] = uint8_t(i);
    hmac_sha256(buf2 + 32, 32, buf2, 32, ref);
    CHECK_EQ_BYTES(buf, ref, 32);
    for (int i = 0; i < 64; i++) buf[i] = uint8_t(i);
    hmac_sha512(buf, 64, buf, 64, ref);
    hmac_sha512(buf, 64, buf, 64, buf);
    CHECK_EQ_BYTES(buf, ref, 64);
  }
}

// ------------------------------------------------------------------------------------------------ curves / keys
static void test_pubkeys() {
  CHECK_SECTION("ec_pubkey generators and ranges");
  uint8_t one[32] = {0};
  one[31] = 1;
  uint8_t xy[64];
  CHECK(ec_pubkey(Curve::Secp256k1, one, xy));
  CHECK_EQ_HEX(xy, 64,
               "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a"
               "68554199c47d08ffb10d4b8");
  CHECK(ec_pubkey(Curve::P256, one, xy));
  CHECK_EQ_HEX(xy, 64,
               "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576"
               "b315ececbb6406837bf51f5");

  // secp256k1 private key 1 -> the well-known address 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf
  CHECK(ec_pubkey(Curve::Secp256k1, one, xy));
  Addr a = eth_address(xy);
  CHECK_EQ(addr_hex(a), std::string("7e5f4552091a69125d5dfcb7b8c2659029395bdf"));
  CHECK_EQ(short_addr(a), std::string("0x7E5F...5Bdf"));

  struct {
    Curve c;
    const char* n;
    const char* nm1_pub;  // (n-1)*G = -G
  } cs[2] = {
      {Curve::Secp256k1, "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
       "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798b7c52588d95c3b9aa25b0403f1eef75702e84bb7597aab"
       "e663b82f6f04ef2777"},
      {Curve::P256, "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551",
       "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296b01cbd1c01e58065711814b583f061e9d431cca994cea1"
       "313449bf97c840ae0a"},
  };
  for (auto& t : cs) {
    Bytes n = HX(t.n);
    uint8_t k[32];
    std::memset(k, 0, 32);
    CHECK(!ec_pubkey(t.c, k, xy));  // 0
    std::memcpy(k, n.data(), 32);
    CHECK(!ec_pubkey(t.c, k, xy));  // n
    k[31]++;
    CHECK(!ec_pubkey(t.c, k, xy));  // n + 1
    std::memset(k, 0xff, 32);
    CHECK(!ec_pubkey(t.c, k, xy));  // 2^256 - 1
    std::memcpy(k, n.data(), 32);
    k[31]--;
    CHECK(ec_pubkey(t.c, k, xy));  // n - 1
    CHECK_EQ_HEX(xy, 64, t.nm1_pub);
    CHECK(!ec_pubkey(t.c, nullptr, xy));
  }
}

// ------------------------------------------------------------------------------------------------ RFC 6979
static void test_rfc6979() {
  CHECK_SECTION("RFC 6979 A.2.5 P-256 SHA-256");
  const Curve c = Curve::P256;
  Bytes x = HX("C9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721");
  uint8_t pub[64];
  CHECK(ec_pubkey(c, x.data(), pub));
  CHECK_EQ_HEX(pub, 64,
               "60FED4BA255A9D31C961EB74C6356D68C049B8923B61FA6CE669622E60F29FB6"
               "7903FE1008B8BC99A41AE9E95628BC64F2F1B20C2D7E9F5177A3C294D4462299");
  struct {
    const char* msg;
    const char* k;
    const char* r;
    const char* s;       // RFC value (raw)
    const char* s_low;   // after low-s normalisation (n - s if s > n/2)
    const char* der;     // DER of (r, s_low)
  } vs[2] = {
      {"sample", "A6E3C57DD01ABE90086538398355DD4C3B17AA873382B0F24D6129493D8AAD60",
       "EFD48B2AACB6A8FD1140DD9CD45E81D69D2C877B56AAF991C34D0EA84EAF3716",
       "F7CB1C942D657C41D436C7A1B6E29F65F3E900DBB9AFF4064DC4AB2F843ACDA8",
       "0834e36ad29a83bf2bc9385e491d6099c8fdf9d1ed67aa7ea5f51f93782857a9",
       "3045022100efd48b2aacb6a8fd1140dd9cd45e81d69d2c877b56aaf991c34d0ea84eaf371602200834e36ad29a83bf2bc9385e491d6099c8"
       "fdf9d1ed67aa7ea5f51f93782857a9"},
      {"test", "D16B6AE827F17175E040871A1C7EC3500192C4C92677336EC2537ACAEE0008E0",
       "F1ABB023518351CD71D881567B1EA663ED3EFCF6C5132B354F28D3B0B7D38367",
       "019F4113742A2B14BD25926B49C649155F267E60D3814B4C0CC84250E46F0083",
       "019F4113742A2B14BD25926B49C649155F267E60D3814B4C0CC84250E46F0083",
       "3045022100f1abb023518351cd71d881567b1ea663ed3efcf6c5132b354f28d3b0b7d383670220019f4113742a2b14bd25926b49c64915"
       "5f267e60d3814b4c0cc84250e46f0083"},
  };
  for (auto& v : vs) {
    uint8_t dg[32];
    sha256(S(v.msg), std::strlen(v.msg), dg);
    // raw (non-normalised) internal path: k, r, s exactly as printed in the RFC
    uint8_t rs[64], k[32];
    int rid_raw = -1;
    CHECK(crypto_test::ecdsa_sign_raw(c, x.data(), dg, rs, &rid_raw, k));
    CHECK_EQ_HEX(k, 32, v.k);
    CHECK_EQ_HEX(rs, 32, v.r);
    CHECK_EQ_HEX(rs + 32, 32, v.s);
    CHECK(rid_raw == 0 || rid_raw == 1);
    CHECK(ecdsa_verify(c, pub, dg, rs));  // verify accepts high-s (plain ECDSA)
    uint8_t rec[64];
    CHECK(ecdsa_recover(c, dg, rs, rid_raw, rec));
    CHECK_EQ_BYTES(rec, pub, 64);
    // public path: low-s
    int rid = -1;
    CHECK(ecdsa_sign(c, x.data(), dg, rs, &rid));
    CHECK_EQ_HEX(rs, 32, v.r);
    CHECK_EQ_HEX(rs + 32, 32, v.s_low);
    CHECK(is_low_s(c, rs));
    CHECK(ecdsa_verify(c, pub, dg, rs));
    CHECK(ecdsa_recover(c, dg, rs, rid, rec));
    CHECK_EQ_BYTES(rec, pub, 64);
    const bool flipped = std::string(v.s) != std::string(v.s_low);
    CHECK_EQ(rid, flipped ? (rid_raw ^ 1) : rid_raw);
    uint8_t der[72];
    size_t dn = ecdsa_der(rs, der);
    CHECK_EQ_HEX(der, dn, v.der);
    // determinism
    uint8_t rs2[64];
    int rid2 = -1;
    CHECK(ecdsa_sign(c, x.data(), dg, rs2, &rid2));
    CHECK_EQ_BYTES(rs2, rs, 64);
    CHECK_EQ(rid2, rid);
  }
  CHECK_SECTION("RFC 6979 DRBG candidates 0..3 incl. the reject step (vs ref_crypto.py)");
  for (const NonceVec& v : NONCE_VECS) {
    Bytes priv = HX(v.priv), dg = HX(v.digest);
    for (unsigned i = 0; i < 4; i++) {
      uint8_t k[32];
      CHECK(crypto_test::rfc6979_candidate(curve_of(v.curve), priv.data(), dg.data(), i, k));
      CHECK_EQ_HEX(k, 32, v.cand[i]);
    }
    // candidate 0 is the nonce ecdsa_sign actually uses
    uint8_t rs[64], k[32];
    int rid = 0;
    CHECK(crypto_test::ecdsa_sign_raw(curve_of(v.curve), priv.data(), dg.data(), rs, &rid, k));
    CHECK_EQ_HEX(k, 32, v.cand[0]);
  }
  {
    uint8_t k[32];
    CHECK_EQ_HEX(x.data(), 32, "C9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721");
    uint8_t dg[32];
    sha256(S("sample"), 6, dg);
    CHECK(crypto_test::rfc6979_candidate(c, x.data(), dg, 0, k));
    CHECK_EQ_HEX(k, 32, "A6E3C57DD01ABE90086538398355DD4C3B17AA873382B0F24D6129493D8AAD60");
  }
  CHECK_SECTION("RFC 6979 A.2.5 recid of the normalised 'sample' signature");
  // "sample": the RFC s is high, so the low-s recid must be the flipped one
  {
    uint8_t dg[32], rs[64];
    int rid = -1;
    sha256(S("sample"), 6, dg);
    CHECK(ecdsa_sign(c, x.data(), dg, rs, &rid));
    CHECK_EQ(rid, 1);
  }
}

// ------------------------------------------------------------------------------------------------ ECDSA vs Python
static void test_ecdsa_vectors() {
  CHECK_SECTION("ECDSA vs tools/ref_crypto.py (edge + random keys/digests, both curves)");
  int n_k1 = 0, n_p1 = 0;
  for (const EcdsaVec& v : ECDSA_VECS) {
    const Curve c = curve_of(v.curve);
    (v.curve ? n_p1 : n_k1)++;
    Bytes priv = HX(v.priv), dg = HX(v.digest), pubw = HX(v.pub), rsw = HX(v.rs), rsraw = HX(v.rs_raw);
    uint8_t pub[64], rs[64], rec[64];
    if (!CHECK(ec_pubkey(c, priv.data(), pub))) continue;
    CHECK_EQ_HEX(pub, 64, v.pub);
    int rid = -1;
    CHECK(ecdsa_sign(c, priv.data(), dg.data(), rs, &rid));
    CHECK_EQ_HEX(rs, 64, v.rs);
    CHECK_EQ(rid, v.recid);
    CHECK(is_low_s(c, rs));
    int rid_raw = -1;
    uint8_t k[32];
    CHECK(crypto_test::ecdsa_sign_raw(c, priv.data(), dg.data(), rs, &rid_raw, k));
    CHECK_EQ_HEX(rs, 64, v.rs_raw);
    CHECK_EQ(rid_raw, v.recid_raw);
    CHECK(ecdsa_verify(c, pubw.data(), dg.data(), rsw.data()));
    CHECK(ecdsa_verify(c, pubw.data(), dg.data(), rsraw.data()));
    CHECK(ecdsa_recover(c, dg.data(), rsw.data(), v.recid, rec));
    CHECK_EQ_BYTES(rec, pubw.data(), 64);
    // the other recid gives a different key (or none)
    if (ecdsa_recover(c, dg.data(), rsw.data(), v.recid ^ 1, rec)) CHECK(std::memcmp(rec, pubw.data(), 64) != 0);
    uint8_t der[72];
    size_t dn = ecdsa_der(rsw.data(), der);
    CHECK_EQ_HEX(der, dn, v.der);
    if (!v.curve) CHECK_EQ(addr_hex(eth_address(pubw.data())), std::string(v.addr));
    // tampering
    Bytes bad = dg;
    bad[7] ^= 0x10;
    CHECK(!ecdsa_verify(c, pubw.data(), bad.data(), rsw.data()));
    Bytes badrs = rsw;
    badrs[40] ^= 0x01;
    CHECK(!ecdsa_verify(c, pubw.data(), dg.data(), badrs.data()));
  }
  CHECK_EQ(n_k1, 46);
  CHECK_EQ(n_p1, 46);
}

static void test_ecdsa_rejects() {
  CHECK_SECTION("verify / recover / sign reject malformed input");
  for (int ci = 0; ci < 2; ci++) {
    const Curve c = curve_of(ci);
    const EcdsaVec* v = nullptr;
    for (const EcdsaVec& e : ECDSA_VECS)
      if (e.curve == ci) {
        v = &e;
        break;
      }
    if (!CHECK(v != nullptr)) return;
    Bytes pub = HX(v->pub), dg = HX(v->digest), rs = HX(v->rs), priv = HX(v->priv);
    Bytes n = HX(ci ? "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551"
                    : "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141");
    Bytes p = HX(ci ? "ffffffff00000001000000000000000000000000ffffffffffffffffffffffff"
                    : "fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f");
    uint8_t out[64];
    CHECK(ecdsa_verify(c, pub.data(), dg.data(), rs.data()));
    // r = 0, s = 0, r = n, s = n
    Bytes t = rs;
    std::memset(t.data(), 0, 32);
    CHECK(!ecdsa_verify(c, pub.data(), dg.data(), t.data()));
    CHECK(!ecdsa_recover(c, dg.data(), t.data(), 0, out));
    t = rs;
    std::memset(t.data() + 32, 0, 32);
    CHECK(!ecdsa_verify(c, pub.data(), dg.data(), t.data()));
    CHECK(!ecdsa_recover(c, dg.data(), t.data(), 0, out));
    t = rs;
    std::memcpy(t.data(), n.data(), 32);
    CHECK(!ecdsa_verify(c, pub.data(), dg.data(), t.data()));
    CHECK(!ecdsa_recover(c, dg.data(), t.data(), 0, out));
    t = rs;
    std::memcpy(t.data() + 32, n.data(), 32);
    CHECK(!ecdsa_verify(c, pub.data(), dg.data(), t.data()));
    CHECK(!ecdsa_recover(c, dg.data(), t.data(), 1, out));
    // recid outside {0,1}
    CHECK(!ecdsa_recover(c, dg.data(), rs.data(), 2, out));
    CHECK(!ecdsa_recover(c, dg.data(), rs.data(), 3, out));
    CHECK(!ecdsa_recover(c, dg.data(), rs.data(), -1, out));
    // public key off the curve / out of range
    t = pub;
    t[63] ^= 1;
    CHECK(!ecdsa_verify(c, t.data(), dg.data(), rs.data()));
    t = pub;
    std::memcpy(t.data(), p.data(), 32);
    CHECK(!ecdsa_verify(c, t.data(), dg.data(), rs.data()));
    t.assign(64, 0);
    CHECK(!ecdsa_verify(c, t.data(), dg.data(), rs.data()));
    // wrong key
    Bytes other = HX(ECDSA_VECS[ci ? 47 : 1].pub);
    CHECK(!ecdsa_verify(c, other.data(), dg.data(), rs.data()));
    // sign with invalid private keys
    uint8_t k[32];
    int rid = 7;
    std::memset(k, 0, 32);
    CHECK(!ecdsa_sign(c, k, dg.data(), out, &rid));
    CHECK(!ecdsa_sign(c, n.data(), dg.data(), out, &rid));
    std::memset(k, 0xff, 32);
    CHECK(!ecdsa_sign(c, k, dg.data(), out, &rid));
    CHECK_EQ(rid, 7);  // untouched on failure
    // recid pointer is optional
    CHECK(ecdsa_sign(c, priv.data(), dg.data(), out, nullptr));
    CHECK_EQ_BYTES(out, rs.data(), 64);
    // an x that is not on the curve cannot be recovered: find an r with no square root
    t = rs;
    bool found_nonresidue = false;
    for (int i = 0; i < 64 && !found_nonresidue; i++) {
      t[31] = uint8_t(i + 1);
      std::memset(t.data(), 0, 31);
      if (!ecdsa_recover(c, dg.data(), t.data(), 0, out) && !ecdsa_recover(c, dg.data(), t.data(), 1, out))
        found_nonresidue = true;
    }
    CHECK(found_nonresidue);
  }
}

// ------------------------------------------------------------------------------------------------ DER
static void test_der() {
  CHECK_SECTION("strict DER vs ref_crypto.der");
  for (const DerVec& v : DER_VECS) {
    Bytes rs = HX(v.rs);
    uint8_t out[72];
    size_t n = ecdsa_der(rs.data(), out);
    CHECK_EQ_HEX(out, n, v.der);
  }
  CHECK_SECTION("DER hand cases");
  uint8_t rs[64], out[72];
  std::memset(rs, 0xff, 64);  // both high bit, 33-byte INTEGERs -> maximal 72 bytes
  size_t n = ecdsa_der(rs, out);
  CHECK_EQ(n, size_t(72));
  CHECK_EQ_HEX(out, 6, "3046022100ff");
  CHECK_EQ(out[0], 0x30);
  CHECK_EQ(out[1], 70);
  CHECK_EQ(out[2], 0x02);
  CHECK_EQ(out[3], 33);
  CHECK_EQ(out[4], 0x00);
  CHECK_EQ(out[5], 0xff);
  CHECK_EQ(out[37], 0x02);
  CHECK_EQ(out[38], 33);
  CHECK_EQ(out[39], 0x00);
  std::memset(rs, 0, 64);
  rs[31] = 0x80;  // r = 0x80 -> 02 02 00 80
  rs[63] = 0x7f;  // s = 0x7f -> 02 01 7f
  n = ecdsa_der(rs, out);
  CHECK_EQ_HEX(out, n, "30070202008002017f");
  std::memset(rs, 0, 64);
  rs[1] = 0x80;   // r has one leading zero byte, then a high bit -> 32-byte INTEGER with 0x00 pad
  rs[32] = 0x7f;  // s: 32 bytes, no pad
  n = ecdsa_der(rs, out);
  CHECK_EQ(n, size_t(2 + 2 + 32 + 2 + 32));
  CHECK_EQ(out[3], 32);
  CHECK_EQ(out[4], 0x00);
  CHECK_EQ(out[5], 0x80);
}

// ------------------------------------------------------------------------------------------------ BIP-32 / SLIP-10
struct TvNode {
  std::vector<uint32_t> path;
  const char* chain;
  const char* priv;
  const char* pub33;
};

static void check_chain(Curve c, const Bytes& seed, const std::vector<TvNode>& nodes, const char* label) {
  for (const TvNode& nd : nodes) {
    ExtKey k;
    bool ok = bip32_master(c, seed.data(), seed.size(), k);
    for (size_t i = 0; ok && i < nd.path.size(); i++) {
      ExtKey child;
      ok = bip32_ckd_priv(c, k, nd.path[i], child);
      k = child;
    }
    if (!CHECK(ok)) {
      std::printf("     (%s depth %u)\n", label, unsigned(nd.path.size()));
      continue;
    }
    CHECK_EQ_HEX(k.key, 32, nd.priv);
    CHECK_EQ_HEX(k.chain, 32, nd.chain);
    uint8_t xy[64];
    CHECK(ec_pubkey(c, k.key, xy));
    CHECK_EQ(compressed(xy), std::string(nd.pub33));
    uint8_t priv[32];
    CHECK(derive_path(c, seed.data(), seed.size(), nd.path.empty() ? nullptr : nd.path.data(), nd.path.size(), priv));
    CHECK_EQ_HEX(priv, 32, nd.priv);
  }
}

static void test_bip32() {
  const Bytes seed = HX("000102030405060708090a0b0c0d0e0f");
  CHECK_SECTION("BIP-32 test vector 1 (secp256k1)");
  const std::vector<TvNode> tv1 = {
      {{}, "873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508",
       "e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35",
       "0339a36013301597daef41fbe593a02cc513d0b55527ec2df1050e2e8ff49c85c2"},
      {{0 | H}, "47fdacbd0f1097043b78c63c20c34ef4ed9a111d980047ad16282c7ae6236141",
       "edb2e14f9ee77d26dd93b4ecede8d16ed408ce149b6cd80b0715a2d911a0afea",
       "035a784662a4a20a65bf6aab9ae98a6c068a81c52e4b032c0fb5400c706cfccc56"},
      {{0 | H, 1}, "2a7857631386ba23dacac34180dd1983734e444fdbf774041578e9b6adb37c19",
       "3c6cb8d0f6a264c91ea8b5030fadaa8e538b020f0a387421a12de9319dc93368",
       "03501e454bf00751f24b1b489aa925215d66af2234e3891c3b21a52bedb3cd711c"},
      {{0 | H, 1, 2 | H}, "04466b9cc8e161e966409ca52986c584f07e9dc81f735db683c3ff6ec7b1503f",
       "cbce0d719ecf7431d88e6a89fa1483e02e35092af60c042b1df2ff59fa424dca",
       "0357bfe1e341d01c69fe5654309956cbea516822fba8a601743a012a7896ee8dc2"},
      {{0 | H, 1, 2 | H, 2}, "cfb71883f01676f587d023cc53a35bc7f88f724b1f8c2892ac1275ac822a3edd",
       "0f479245fb19a38a1954c5c7c0ebab2f9bdfd96a17563ef28a6a4b1a2a764ef4",
       "02e8445082a72f29b75ca48748a914df60622a609cacfce8ed0e35804560741d29"},
      {{0 | H, 1, 2 | H, 2, 1000000000}, "c783e67b921d2beb8f6b389cc646d7263b4145701dadd2161548a8b078e65e9e",
       "471b76e389e528d6de6d816857e012c5455051cad6660850e58372a6c3e6e7c8",
       "022a471424da5e657499d1ff51cb43c47481a03b1e77f951fe64cec9f5a48f7011"},
  };
  check_chain(Curve::Secp256k1, seed, tv1, "bip32 tv1");

  CHECK_SECTION("SLIP-10 nist256p1 test vector 1");
  const std::vector<TvNode> s1 = {
      {{}, "beeb672fe4621673f722f38529c07392fecaa61015c80c34f29ce8b41b3cb6ea",
       "612091aaa12e22dd2abef664f8a01a82cae99ad7441b7ef8110424915c268bc2",
       "0266874dc6ade47b3ecd096745ca09bcd29638dd52c2c12117b11ed3e458cfa9e8"},
      {{0 | H}, "3460cea53e6a6bb5fb391eeef3237ffd8724bf0a40e94943c98b83825342ee11",
       "6939694369114c67917a182c59ddb8cafc3004e63ca5d3b84403ba8613debc0c",
       "0384610f5ecffe8fda089363a41f56a5c7ffc1d81b59a612d0d649b2d22355590c"},
      {{0 | H, 1}, "4187afff1aafa8445010097fb99d23aee9f599450c7bd140b6826ac22ba21d0c",
       "284e9d38d07d21e4e281b645089a94f4cf5a5a81369acf151a1c3a57f18b2129",
       "03526c63f8d0b4bbbf9c80df553fe66742df4676b241dabefdef67733e070f6844"},
      {{0 | H, 1, 2 | H}, "98c7514f562e64e74170cc3cf304ee1ce54d6b6da4f880f313e8204c2a185318",
       "694596e8a54f252c960eb771a3c41e7e32496d03b954aeb90f61635b8e092aa7",
       "0359cf160040778a4b14c5f4d7b76e327ccc8c4a6086dd9451b7482b5a4972dda0"},
      {{0 | H, 1, 2 | H, 2}, "ba96f776a5c3907d7fd48bde5620ee374d4acfd540378476019eab70790c63a0",
       "5996c37fd3dd2679039b23ed6f70b506c6b56b3cb5e424681fb0fa64caf82aaa",
       "029f871f4cb9e1c97f9f4de9ccd0d4a2f2a171110c61178f84430062230833ff20"},
      {{0 | H, 1, 2 | H, 2, 1000000000}, "b9b7b82d326bb9cb5b5b121066feea4eb93d5241103c9e7a18aad40f1dde8059",
       "21c4f269ef0a5fd1badf47eeacebeeaa3de22eb8e5b0adcd0f27dd99d34d0119",
       "02216cd26d31147f72427a453c443ed2cde8a1e53c9cc44e5ddf739725413fe3f4"},
  };
  check_chain(Curve::P256, seed, s1, "slip10 tv1");

  CHECK_SECTION("SLIP-10 nist256p1 derivation retry (m/28578H/33941)");
  const std::vector<TvNode> rt = {
      {{28578 | H}, "e94c8ebe30c2250a14713212f6449b20f3329105ea15b652ca5bdfc68f6c65c2",
       "06f0db126f023755d0b8d86d4591718a5210dd8d024e3e14b6159d63f53aa669",
       "02519b5554a4872e8c9c1c847115363051ec43e93400e030ba3c36b52a3e70a5b7"},
      {{28578 | H, 33941}, "9e87fe95031f14736774cd82f25fd885065cb7c358c1edf813c72af535e83071",
       "092154eed4af83e078ff9b84322015aefe5769e31270f62c3f66c33888335f3a",
       "0235bfee614c0d5b2cae260000bb1d0d84b270099ad790022c1ae0b2e782efe120"},
  };
  check_chain(Curve::P256, seed, rt, "slip10 retry");

  CHECK_SECTION("SLIP-10 nist256p1 seed retry");
  {
    const Bytes sd = HX("a7305bc8df8d0951f0cb224c0e95d7707cbdf2c6ce7e8d481fec69c7ff5e9446");
    const std::vector<TvNode> m = {{{}, "7762f9729fed06121fd13f326884c82f59aa95c57ac492ce8c9654e60efd130c",
                                    "3b8c18469a4634517d6d0b65448f8e6c62091b45540a1743c5846be55d47d88f",
                                    "0383619fadcde31063d8c5cb00dbfe1713f3e6fa169d8541a798752a1c1ca0cb20"}};
    check_chain(Curve::P256, sd, m, "slip10 seed retry");
  }

  CHECK_SECTION("bip32_ckd_priv: child may alias parent; invalid parents rejected");
  {
    ExtKey k, k2;
    CHECK(bip32_master(Curve::Secp256k1, seed.data(), seed.size(), k));
    k2 = k;
    CHECK(bip32_ckd_priv(Curve::Secp256k1, k, 0 | H, k));  // in place
    CHECK_EQ_HEX(k.key, 32, "edb2e14f9ee77d26dd93b4ecede8d16ed408ce149b6cd80b0715a2d911a0afea");
    CHECK_EQ_HEX(k.chain, 32, "47fdacbd0f1097043b78c63c20c34ef4ed9a111d980047ad16282c7ae6236141");
    CHECK(bip32_ckd_priv(Curve::Secp256k1, k, 1, k));  // in place, non-hardened
    CHECK_EQ_HEX(k.key, 32, "3c6cb8d0f6a264c91ea8b5030fadaa8e538b020f0a387421a12de9319dc93368");
    ExtKey bad = k2, out;
    std::memset(bad.key, 0, 32);
    CHECK(!bip32_ckd_priv(Curve::Secp256k1, bad, 1, out));
    CHECK(!bip32_ckd_priv(Curve::P256, bad, 1 | H, out));
    std::memset(bad.key, 0xff, 32);
    CHECK(!bip32_ckd_priv(Curve::Secp256k1, bad, 1 | H, out));
    CHECK(!bip32_ckd_priv(Curve::P256, bad, 1, out));
    uint8_t priv[32];
    CHECK(!derive_path(Curve::Secp256k1, seed.data(), seed.size(), nullptr, 2, priv));
    CHECK(!bip32_master(Curve::Secp256k1, nullptr, 16, k));
    CHECK(bip32_master(Curve::P256, nullptr, 0, k));  // empty seed is allowed (HMAC of "")
  }

  CHECK_SECTION("product paths");
  CHECK_EQ(PATH_K1[0], 44u | H);
  CHECK_EQ(PATH_K1[1], 60u | H);
  CHECK_EQ(PATH_K1[2], 0u | H);
  CHECK_EQ(PATH_K1[3], 0u);
  CHECK_EQ(PATH_K1[4], 0u);
  CHECK_EQ(PATH_P1[0], 7951u | H);
  CHECK_EQ(PATH_P1[1], 0u | H);
  CHECK_EQ(H, 0x80000000u);
  {
    Bytes sd = HX(DEMO_SEED);
    uint8_t priv[32], xy[64];
    CHECK(derive_path(Curve::Secp256k1, sd.data(), sd.size(), PATH_K1, 5, priv));
    CHECK_EQ_HEX(priv, 32, DEMO_K1_PRIV);
    CHECK(ec_pubkey(Curve::Secp256k1, priv, xy));
    CHECK_EQ(addr_hex(eth_address(xy)), std::string(DEMO_K1_ADDR));
    CHECK(derive_path(Curve::P256, sd.data(), sd.size(), PATH_P1, 2, priv));
    CHECK_EQ_HEX(priv, 32, DEMO_P1_PRIV);
    CHECK(ec_pubkey(Curve::P256, priv, xy));
    CHECK_EQ_HEX(xy, 64, DEMO_P1_PUB);
  }

  CHECK_SECTION("derivation vs ref_crypto.py (random seeds/paths, both curves)");
  for (const DeriveVec& v : DERIVE_VECS) {
    const Curve c = curve_of(v.curve);
    Bytes sd = HX(v.seed);
    uint32_t path[6];
    for (int i = 0; i < 6; i++) path[i] = v.path[i];
    uint8_t priv[32];
    CHECK(derive_path(c, sd.data(), sd.size(), path, size_t(v.depth), priv));
    CHECK_EQ_HEX(priv, 32, v.priv);
    ExtKey k;
    bool ok = bip32_master(c, sd.data(), sd.size(), k);
    for (int i = 0; ok && i < v.depth; i++) ok = bip32_ckd_priv(c, k, path[i], k);
    CHECK(ok);
    CHECK_EQ_HEX(k.chain, 32, v.chain);
  }
}

// ------------------------------------------------------------------------------------------------ round trips
static void test_roundtrips() {
  CHECK_SECTION("random sign/verify/recover round trips (self-consistency)");
  for (int ci = 0; ci < 2; ci++) {
    const Curve c = curve_of(ci);
    int fails = 0, highs = 0, recid1 = 0;
    const int N = 150;
    for (int it = 0; it < N; it++) {
      uint8_t priv[32], dg[32], pub[64], rs[64], rec[64];
      rnd(priv, 32);
      if (it % 10 == 0) std::memset(priv, 0, 28);  // small keys too
      rnd(dg, 32);
      if (!ec_pubkey(c, priv, pub)) continue;  // (out of range: astronomically unlikely)
      int rid = -1;
      bool ok = ecdsa_sign(c, priv, dg, rs, &rid);
      ok = ok && (rid == 0 || rid == 1);
      ok = ok && ecdsa_verify(c, pub, dg, rs);
      ok = ok && ecdsa_recover(c, dg, rs, rid, rec) && std::memcmp(rec, pub, 64) == 0;
      if (!is_low_s(c, rs)) highs++;
      recid1 += rid;
      dg[0] ^= 0x80;
      ok = ok && !ecdsa_verify(c, pub, dg, rs);
      if (!ok) fails++;
    }
    CHECK_EQ(fails, 0);
    CHECK_EQ(highs, 0);
    CHECK(recid1 > N / 5 && recid1 < N * 4 / 5);  // both recids occur
  }
}

static void bench() {
  CHECK_SECTION("host timing (informational)");
  Bytes seed = HX(DEMO_SEED);
  uint8_t priv[32], pub[64], dg[32], rs[64];
  sha256(S("bench"), 5, dg);
  for (int ci = 0; ci < 2; ci++) {
    const Curve c = curve_of(ci);
    CHECK(derive_path(c, seed.data(), seed.size(), ci ? PATH_P1 : PATH_K1, ci ? 2 : 5, priv));
    CHECK(ec_pubkey(c, priv, pub));
    const int N = 50;
    int rid = 0;
    std::clock_t t0 = std::clock();
    for (int i = 0; i < N; i++) {
      dg[0] = uint8_t(i);
      ecdsa_sign(c, priv, dg, rs, &rid);
    }
    std::clock_t t1 = std::clock();
    for (int i = 0; i < N; i++) ecdsa_recover(c, dg, rs, rid, pub);
    std::clock_t t2 = std::clock();
    for (int i = 0; i < N; i++) derive_path(c, seed.data(), seed.size(), ci ? PATH_P1 : PATH_K1, ci ? 2 : 5, priv);
    std::clock_t t3 = std::clock();
    const double ms = 1000.0 / CLOCKS_PER_SEC / N;
    std::printf("   %s: sign %.2f ms, recover %.2f ms, derive_path %.2f ms (host)\n", ci ? "P-256" : "secp256k1",
                double(t1 - t0) * ms, double(t2 - t1) * ms, double(t3 - t2) * ms);
  }
}

int main() {
  test_sha512_hmac();
  test_pubkeys();
  test_rfc6979();
  test_ecdsa_vectors();
  test_ecdsa_rejects();
  test_der();
  test_bip32();
  test_roundtrips();
  bench();
  return CHECK_SUMMARY();
}
