// DEPS: hashes util cbor ur
// Host tests for src/cbor.cpp + src/ur.cpp.
// Expected values: RFC 8949 Appendix A (CBOR examples), BCR-2020-012 / bc-ur test.cpp (bytewords), BCR-2020-005
// (ur:seed examples), bc-ur test.cpp (single-part UR, the 20 UR-encoder parts, choose_fragments), and fountain
// streams generated by tools/ref_ur.py (whose own selftest reproduces all the official bc-ur vectors).
// Regenerate the data block with:  python tools/ref_ur.py gen-cpp
#include <algorithm>
#include <cmath>
#include <cstring>
#include <string>
#include <vector>

#include "cbor.h"
#include "check.h"
#include "hashes.h"
#include "ur.h"
#include "util.h"

using namespace ripar;

// ---- BEGIN generated by tools/ref_ur.py gen-cpp (do not edit by hand) ----
static const uint8_t kWolf256Cbor[259] = {
    0x59, 0x01, 0x00, 0x91, 0x6e, 0xc6, 0x5c, 0xf7, 0x7c, 0xad, 0xf5, 0x5c, 0xd7, 0xf9, 0xcd, 0xa1, 0xa1, 0x03, 0x00, 0x26,
    0xdd, 0xd4, 0x2e, 0x90, 0x5b, 0x77, 0xad, 0xc3, 0x6e, 0x4f, 0x2d, 0x3c, 0xcb, 0xa4, 0x4f, 0x7f, 0x04, 0xf2, 0xde, 0x44,
    0xf4, 0x2d, 0x84, 0xc3, 0x74, 0xa0, 0xe1, 0x49, 0x13, 0x6f, 0x25, 0xb0, 0x18, 0x52, 0x54, 0x59, 0x61, 0xd5, 0x5f, 0x7f,
    0x7a, 0x8c, 0xde, 0x6d, 0x0e, 0x2e, 0xc4, 0x3f, 0x3b, 0x2d, 0xcb, 0x64, 0x4a, 0x22, 0x09, 0xe8, 0xc9, 0xe3, 0x4a, 0xf5,
    0xc4, 0x74, 0x79, 0x84, 0xa5, 0xe8, 0x73, 0xc9, 0xcf, 0x5f, 0x96, 0x5e, 0x25, 0xee, 0x29, 0x03, 0x9f, 0xdf, 0x8c, 0xa7,
    0x4f, 0x1c, 0x76, 0x9f, 0xc0, 0x7e, 0xb7, 0xeb, 0xae, 0xc4, 0x6e, 0x06, 0x95, 0xae, 0xa6, 0xcb, 0xd6, 0x0b, 0x3e, 0xc4,
    0xbb, 0xff, 0x1b, 0x9f, 0xfe, 0x8a, 0x9e, 0x72, 0x40, 0x12, 0x93, 0x77, 0xb9, 0xd3, 0x71, 0x1e, 0xd3, 0x8d, 0x41, 0x2f,
    0xbb, 0x44, 0x42, 0x25, 0x6f, 0x1e, 0x6f, 0x59, 0x5e, 0x0f, 0xc5, 0x7f, 0xed, 0x45, 0x1f, 0xb0, 0xa0, 0x10, 0x1f, 0xb7,
    0x6b, 0x1f, 0xb1, 0xe1, 0xb8, 0x8c, 0xfd, 0xfd, 0xaa, 0x94, 0x62, 0x94, 0xa4, 0x7d, 0xe8, 0xff, 0xf1, 0x73, 0xf0, 0x21,
    0xc0, 0xe6, 0xf6, 0x5b, 0x05, 0xc0, 0xa4, 0x94, 0xe5, 0x07, 0x91, 0x27, 0x0a, 0x00, 0x50, 0xa7, 0x3a, 0xe6, 0x9b, 0x67,
    0x25, 0x50, 0x5a, 0x2e, 0xc8, 0xa5, 0x79, 0x14, 0x57, 0xc9, 0x87, 0x6d, 0xd3, 0x4a, 0xad, 0xd1, 0x92, 0xa5, 0x3a, 0xa0,
    0xdc, 0x66, 0xb5, 0x56, 0xc0, 0xc2, 0x15, 0xc7, 0xce, 0xb8, 0x24, 0x8b, 0x71, 0x7c, 0x22, 0x95, 0x1e, 0x65, 0x30, 0x5b,
    0x56, 0xa3, 0x70, 0x6e, 0x3e, 0x86, 0xeb, 0x01, 0xc8, 0x03, 0xbb, 0xf9, 0x15, 0xd8, 0x0e, 0xdc, 0xd6, 0x4d, 0x4d,
};
static const uint32_t kWolf256Crc = 0xeda0ae73u;
static const uint8_t kWolf50Cbor[52] = {
    0x58, 0x32, 0x91, 0x6e, 0xc6, 0x5c, 0xf7, 0x7c, 0xad, 0xf5, 0x5c, 0xd7, 0xf9, 0xcd, 0xa1, 0xa1, 0x03, 0x00, 0x26, 0xdd,
    0xd4, 0x2e, 0x90, 0x5b, 0x77, 0xad, 0xc3, 0x6e, 0x4f, 0x2d, 0x3c, 0xcb, 0xa4, 0x4f, 0x7f, 0x04, 0xf2, 0xde, 0x44, 0xf4,
    0x2d, 0x84, 0xc3, 0x74, 0xa0, 0xe1, 0x49, 0x13, 0x6f, 0x25, 0xb0, 0x18,
};
static const uint32_t kWolf1024Crc = 0x2f19f3bbu;
static const size_t kWolf1024SeqLen = 11;
static const uint8_t kStreamMsg[733] = {
    0xa4, 0x01, 0x50, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x02,
    0x19, 0x27, 0x9f, 0x09, 0x59, 0x02, 0xbc, 0x03, 0x0a, 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57,
    0x5e, 0x65, 0x6c, 0x73, 0x7a, 0x81, 0x88, 0x8f, 0x96, 0x9d, 0xa4, 0xab, 0xb2, 0xb9, 0xc0, 0xc7, 0xce, 0xd5, 0xdc, 0xe3,
    0xea, 0xf1, 0xf8, 0xff, 0x06, 0x0d, 0x14, 0x1b, 0x22, 0x29, 0x30, 0x37, 0x3e, 0x45, 0x4c, 0x53, 0x5a, 0x61, 0x68, 0x6f,
    0x76, 0x7d, 0x84, 0x8b, 0x92, 0x99, 0xa0, 0xa7, 0xae, 0xb5, 0xbc, 0xc3, 0xca, 0xd1, 0xd8, 0xdf, 0xe6, 0xed, 0xf4, 0xfb,
    0x02, 0x09, 0x10, 0x17, 0x1e, 0x25, 0x2c, 0x33, 0x3a, 0x41, 0x48, 0x4f, 0x56, 0x5d, 0x64, 0x6b, 0x72, 0x79, 0x80, 0x87,
    0x8e, 0x95, 0x9c, 0xa3, 0xaa, 0xb1, 0xb8, 0xbf, 0xc6, 0xcd, 0xd4, 0xdb, 0xe2, 0xe9, 0xf0, 0xf7, 0xfe, 0x05, 0x0c, 0x13,
    0x1a, 0x21, 0x28, 0x2f, 0x36, 0x3d, 0x44, 0x4b, 0x52, 0x59, 0x60, 0x67, 0x6e, 0x75, 0x7c, 0x83, 0x8a, 0x91, 0x98, 0x9f,
    0xa6, 0xad, 0xb4, 0xbb, 0xc2, 0xc9, 0xd0, 0xd7, 0xde, 0xe5, 0xec, 0xf3, 0xfa, 0x01, 0x08, 0x0f, 0x16, 0x1d, 0x24, 0x2b,
    0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63, 0x6a, 0x71, 0x78, 0x7f, 0x86, 0x8d, 0x94, 0x9b, 0xa2, 0xa9, 0xb0, 0xb7,
    0xbe, 0xc5, 0xcc, 0xd3, 0xda, 0xe1, 0xe8, 0xef, 0xf6, 0xfd, 0x04, 0x0b, 0x12, 0x19, 0x20, 0x27, 0x2e, 0x35, 0x3c, 0x43,
    0x4a, 0x51, 0x58, 0x5f, 0x66, 0x6d, 0x74, 0x7b, 0x82, 0x89, 0x90, 0x97, 0x9e, 0xa5, 0xac, 0xb3, 0xba, 0xc1, 0xc8, 0xcf,
    0xd6, 0xdd, 0xe4, 0xeb, 0xf2, 0xf9, 0x00, 0x07, 0x0e, 0x15, 0x1c, 0x23, 0x2a, 0x31, 0x38, 0x3f, 0x46, 0x4d, 0x54, 0x5b,
    0x62, 0x69, 0x70, 0x77, 0x7e, 0x85, 0x8c, 0x93, 0x9a, 0xa1, 0xa8, 0xaf, 0xb6, 0xbd, 0xc4, 0xcb, 0xd2, 0xd9, 0xe0, 0xe7,
    0xee, 0xf5, 0xfc, 0x03, 0x0a, 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57, 0x5e, 0x65, 0x6c, 0x73,
    0x7a, 0x81, 0x88, 0x8f, 0x96, 0x9d, 0xa4, 0xab, 0xb2, 0xb9, 0xc0, 0xc7, 0xce, 0xd5, 0xdc, 0xe3, 0xea, 0xf1, 0xf8, 0xff,
    0x06, 0x0d, 0x14, 0x1b, 0x22, 0x29, 0x30, 0x37, 0x3e, 0x45, 0x4c, 0x53, 0x5a, 0x61, 0x68, 0x6f, 0x76, 0x7d, 0x84, 0x8b,
    0x92, 0x99, 0xa0, 0xa7, 0xae, 0xb5, 0xbc, 0xc3, 0xca, 0xd1, 0xd8, 0xdf, 0xe6, 0xed, 0xf4, 0xfb, 0x02, 0x09, 0x10, 0x17,
    0x1e, 0x25, 0x2c, 0x33, 0x3a, 0x41, 0x48, 0x4f, 0x56, 0x5d, 0x64, 0x6b, 0x72, 0x79, 0x80, 0x87, 0x8e, 0x95, 0x9c, 0xa3,
    0xaa, 0xb1, 0xb8, 0xbf, 0xc6, 0xcd, 0xd4, 0xdb, 0xe2, 0xe9, 0xf0, 0xf7, 0xfe, 0x05, 0x0c, 0x13, 0x1a, 0x21, 0x28, 0x2f,
    0x36, 0x3d, 0x44, 0x4b, 0x52, 0x59, 0x60, 0x67, 0x6e, 0x75, 0x7c, 0x83, 0x8a, 0x91, 0x98, 0x9f, 0xa6, 0xad, 0xb4, 0xbb,
    0xc2, 0xc9, 0xd0, 0xd7, 0xde, 0xe5, 0xec, 0xf3, 0xfa, 0x01, 0x08, 0x0f, 0x16, 0x1d, 0x24, 0x2b, 0x32, 0x39, 0x40, 0x47,
    0x4e, 0x55, 0x5c, 0x63, 0x6a, 0x71, 0x78, 0x7f, 0x86, 0x8d, 0x94, 0x9b, 0xa2, 0xa9, 0xb0, 0xb7, 0xbe, 0xc5, 0xcc, 0xd3,
    0xda, 0xe1, 0xe8, 0xef, 0xf6, 0xfd, 0x04, 0x0b, 0x12, 0x19, 0x20, 0x27, 0x2e, 0x35, 0x3c, 0x43, 0x4a, 0x51, 0x58, 0x5f,
    0x66, 0x6d, 0x74, 0x7b, 0x82, 0x89, 0x90, 0x97, 0x9e, 0xa5, 0xac, 0xb3, 0xba, 0xc1, 0xc8, 0xcf, 0xd6, 0xdd, 0xe4, 0xeb,
    0xf2, 0xf9, 0x00, 0x07, 0x0e, 0x15, 0x1c, 0x23, 0x2a, 0x31, 0x38, 0x3f, 0x46, 0x4d, 0x54, 0x5b, 0x62, 0x69, 0x70, 0x77,
    0x7e, 0x85, 0x8c, 0x93, 0x9a, 0xa1, 0xa8, 0xaf, 0xb6, 0xbd, 0xc4, 0xcb, 0xd2, 0xd9, 0xe0, 0xe7, 0xee, 0xf5, 0xfc, 0x03,
    0x0a, 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57, 0x5e, 0x65, 0x6c, 0x73, 0x7a, 0x81, 0x88, 0x8f,
    0x96, 0x9d, 0xa4, 0xab, 0xb2, 0xb9, 0xc0, 0xc7, 0xce, 0xd5, 0xdc, 0xe3, 0xea, 0xf1, 0xf8, 0xff, 0x06, 0x0d, 0x14, 0x1b,
    0x22, 0x29, 0x30, 0x37, 0x3e, 0x45, 0x4c, 0x53, 0x5a, 0x61, 0x68, 0x6f, 0x76, 0x7d, 0x84, 0x8b, 0x92, 0x99, 0xa0, 0xa7,
    0xae, 0xb5, 0xbc, 0xc3, 0xca, 0xd1, 0xd8, 0xdf, 0xe6, 0xed, 0xf4, 0xfb, 0x02, 0x09, 0x10, 0x17, 0x1e, 0x25, 0x2c, 0x33,
    0x3a, 0x41, 0x48, 0x4f, 0x56, 0x5d, 0x64, 0x6b, 0x72, 0x79, 0x80, 0x87, 0x8e, 0x95, 0x9c, 0xa3, 0xaa, 0xb1, 0xb8, 0xbf,
    0xc6, 0xcd, 0xd4, 0xdb, 0xe2, 0xe9, 0xf0, 0xf7, 0xfe, 0x05, 0x0c, 0x13, 0x1a, 0x21, 0x28, 0x2f, 0x36, 0x3d, 0x44, 0x4b,
    0x52, 0x59, 0x60, 0x67, 0x6e, 0x75, 0x7c, 0x83, 0x8a, 0x91, 0x98, 0x9f, 0xa6, 0xad, 0xb4, 0xbb, 0xc2, 0xc9, 0xd0, 0xd7,
    0xde, 0xe5, 0xec, 0xf3, 0xfa, 0x01, 0x08, 0x0f, 0x16, 0x1d, 0x24, 0x2b, 0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63,
    0x6a, 0x71, 0x78, 0x7f, 0x86, 0x8d, 0x94, 0x9b, 0xa2, 0xa9, 0xb0, 0xb7, 0xbe, 0xc5, 0xcc, 0xd3, 0xda, 0xe1, 0xe8, 0xef,
    0xf6, 0xfd, 0x04, 0x0b, 0x12, 0x19, 0x20, 0x10, 0x64, 0x55, 0x53, 0x44, 0x43,
};
static const size_t kStreamSeqLen = 11, kStreamFragLen = 67;
static const uint32_t kStreamCrc = 0x90dd9065u;
// mixed parts only: seq 12..23; an optimal (GF(2)) decoder completes exactly at the last one
static const char* const kStreamMixed[] = {
    "ur:ripar-cosign-req/12-11/lpbnbdcfaoutcymhutmhihhdfxlrotpkptpfrsswykuouyvovyvsylzebteebwcycfcxdlenda"
    "gsgrgmgyhdiojtkiielsleldmhneolgorfrksasesptsuewemwwfzsytaebscmahdwdneyehetflglhlfyiaimglrpfywe",
    "ur:ripar-cosign-req/13-11/lpbtbdcfaoutcymhutmhihhdfxwyykztaxbkbycsctdsdpeefrfwgagdhghyihjzjkknlylomy"
    "mtntoxpyprrhrtsttotluovlwdwnyazmambtbbcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplrerfflecoecm",
    "ur:ripar-cosign-req/14-11/lpbabdcfaoutcymhutmhihhdfxoeaxgmamfhaeadftaxaaahbaatayasaobdbnbtaaatdantch"
    "heaernahaabwcybycxdlenfsfngrgmpthdiojtkpjylslelymhneolpmpsrksatasptsuevwvewfzswnaebscmplwezeeo",
    "ur:ripar-cosign-req/15-11/lpbsbdcfaoutcymhutmhihhdfxptmkltkoihfyeocpadwturtorynsluknhkfdemdsbzwkvltd"
    "panbmykbjngsfrdrasyavdtbskoxmulfhsgdfhdmcaztwmtnrhpdmslnkpghfxeybyaewsuesnpsndleinhdflmdrspayk",
    "ur:ripar-cosign-req/16-11/lpbebdcfaoutcymhutmhihhdfxwlwmtaemesdnhkjlkkkginhgdtfrdturwlwmyttstadnesdl"
    "hkhpinktinhpdtfhdtdntaylytwmtadlesfrdthginkginhedtdneststawmytwstawpiahgfghhhndmeheefhsnjymnte",
    "ur:ripar-cosign-req/17-11/lpbybdcfaoutcymhutmhihhdfxswtbzswdwyuepkrdolhfimknkbjthtpklnrptnwdwyzewdtn"
    "olrppkhthyjtknimfghfrdpkpluewdzsvatbpkrdrnplhtimamkohtpkplrnpktnvasenbrdpaptqdzockascebwiyvafm",
    "ur:ripar-cosign-req/18-11/lpbgbdcfaoutcymhutmhihhdfxgwtyltecftdlhhinkbjkgdhlcpemdkttvazoyatssabknbdk"
    "aohgsbkohsgsemcpbtyavltorhoxmyknihgdfrdsbyztvdtdrypdmukbinghfhdrbzaewmtbsepsmslfjnhdfxfgnloeec",
    "ur:ripar-cosign-req/19-11/lpbwbdcfaoutcymhutmhihhdfxwkwfwzcfdyctckdadwdnbkehfdkthfhlieiaidgahnmymnmd"
    "nsndrdoyroosswsntytetdytmhzmzeahbnbdimbydetsenfsfyfxfwptfzjljtkpkekgnylymkltolpmqzqdpreeflssvt",
    "ur:ripar-cosign-req/20-11/lpbbbdcfaoutcymhutmhihhdfxlkdshfykvwsepaonlpkkhkfeecbyadyktltarhoslgghzchd"
    "indpprzevatnoerpplpkgmjtamimfwhfrnrdtduevazsvotbplpkprplfgimaokohyjnyauesoutwmosrpreqzhkaycecx",
    "ur:ripar-cosign-req/21-11/lpbzbdcfaoutcymhutmhihhdfxsrsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhlie"
    "jejpkklaltmnmdnsotpkparorsswsntyuyvowlwtylzeahbnbwcycldedlenfsfygrgmhkhniojtkpkelslemepkjzwlvl",
    "ur:ripar-cosign-req/22-11/lpcmbdcfaoutcymhutmhihhdfxlylslyltlylslyrslylslyltlylslymylylslyltlylslyne"
    "lylslyltlylslymylylslyltlylslylblylslyltlylslymylylslyltlylslynelylslyltlylslymylylslytahsfrmd",
    "ur:ripar-cosign-req/23-11/lpchbdcfaoutcymhutmhihhdfxcwckdtdwemftfefdguhfhsiejljpkilalumnnlnsospkrero"
    "srswtttyurvowewtzozeasbnchcydadeeoenfpfygwgmhlhnjejtkkkeltlemdmkotmezotytisksslylslymyvljsnyre",
};
static const size_t kStreamMixedCount = 12;
static const char* const kStreamMixedIdx[] = {
    "2,4,8",
    "8",
    "0,5,6,8,9",
    "2,3,4,5,6,8,9",
    "1,2,4,10",
    "1,2,5,7,9,10",
    "0,1,2",
    "1,2,3,7,9",
    "0,2,3,4,5,6,7,8,9,10",
    "9",
    "5,8",
    "4,7,10",
};
static const char* const kStreamPureShuffled[] = {
    "ur:ripar-cosign-req/7-11/lpatbdcfaoutcymhutmhihhdfxfygrgmhkhniojtkpkelslememkneolpmqzrksasotitsuevww"
    "pwfzsadaybscmcadkdneyesfzflglgohhiaimjskslblnlgmwndoeptpfrlrnsksftetnvyvswsynzcaabdbgpagsmdon",
    "ur:ripar-cosign-req/3-11/lpaxbdcfaoutcymhutmhihhdfxwtylzeahbnbwcycldedlenfsfygrgmhkhniojtkpkelslemem"
    "kneolpmqzrksasotitsuevwwpwfzsadaybscmcadkdneyesfzflglgohhiaimjskslblnlgmwndoeptpfrlrnrnkiqdkb",
    "ur:ripar-cosign-req/3-11/lpaxbdcfaoutcymhutmhihhdfxwtylzeahbnbwcycldedlenfsfygrgmhkhniojtkpkelslemem"
    "kneolpmqzrksasotitsuevwwpwfzsadaybscmcadkdneyesfzflglgohhiaimjskslblnlgmwndoeptpfrlrnrnkiqdkb",
    "ur:ripar-cosign-req/11-11/lpbdbdcfaoutcymhutmhihhdfxmkneolpmqzrksasotitsuevwwpwfzsadaybscmcadkdneyes"
    "fzflglgohhiaimjskslblnlgmwndoeptpfrlrnsksftetnvyvswsynzcaabdbgcfcxbeiegogufyfxaeaeaeaecwfgrltd",
    "ur:ripar-cosign-req/1-11/lpadbdcfaoutcymhutmhihhdfxoxadgdaeadaoaxaaahamatayasbkbdbnbtbabsaocfdineash"
    "kaorfaxbkbycsctdsdpeefrfwgagdhghyihjzjkknlylomymtntoxpyprrhrtsttotluovlwdwnyazmambtbbdehdhhts",
    "ur:ripar-cosign-req/9-11/lpasbdcfaoutcymhutmhihhdfxwyykztaxbkbycsctdsdpeefrfwgagdhghyihjzjkknlylomym"
    "tntoxpyprrhrtsttotluovlwdwnyazmambtbbcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplrerfqdoykkbw",
    "ur:ripar-cosign-req/7-11/lpatbdcfaoutcymhutmhihhdfxfygrgmhkhniojtkpkelslememkneolpmqzrksasotitsuevww"
    "pwfzsadaybscmcadkdneyesfzflglgohhiaimjskslblnlgmwndoeptpfrlrnsksftetnvyvswsynzcaabdbgpagsmdon",
    "ur:ripar-cosign-req/2-11/lpaobdcfaoutcymhutmhihhdfxcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplrerfs"
    "rsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlcnzmsrpd",
    "ur:ripar-cosign-req/10-11/lpbkbdcfaoutcymhutmhihhdfxsrsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhlie"
    "jejpkklaltmnmdnsotpkparorsswsntyuyvowlwtylzeahbnbwcycldedlenfsfygrgmhkhniojtkpkelslemetycykgsp",
    "ur:ripar-cosign-req/5-11/lpahbdcfaoutcymhutmhihhdfxnyoypdperprysssbtdtavtvdwyykztaxbkbycsctdsdpeefrf"
    "wgagdhghyihjzjkknlylomymtntoxpyprrhrtsttotluovlwdwnyazmambtbbcwcpdtdyemfmfegsguhthsisnehschjk",
    "ur:ripar-cosign-req/4-11/lpaabdcfaoutcymhutmhihhdfxsksftetnvyvswsynzcaabdbgcfcxdidmecfnfxgegyhdheiyj"
    "njykglfldmhmsnnonpsqdrdsesptktbutvewmwzytaeatbabzcecndrehetfhfggtghhpidinjoktkblplkmuonvehkrn",
    "ur:ripar-cosign-req/8-11/lpaybdcfaoutcymhutmhihhdfxcfcxdidmecfnfxgegyhdheiyjnjykglfldmhmsnnonpsqdrds"
    "esptktbutvewmwzytaeatbabzcecndrehetfhfggtghhpidinjoktkblplkmunyoypdperprysssbtdtavtvdfdckdpte",
    "ur:ripar-cosign-req/6-11/lpambdcfaoutcymhutmhihhdfxjlkokilrlumonlnbosplrerfsrsgtttpurvawewkzoaoasbec"
    "hckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlwtylzeahbnbwcycldedlenfsutktdtlp",
};
static const size_t kStreamPureShuffledCount = 13;
// 5 pure parts then mixed parts; completes exactly at the last one
static const char* const kStreamCombo[] = {
    "ur:ripar-cosign-req/2-11/lpaobdcfaoutcymhutmhihhdfxcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplrerfs"
    "rsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlcnzmsrpd",
    "ur:ripar-cosign-req/4-11/lpaabdcfaoutcymhutmhihhdfxsksftetnvyvswsynzcaabdbgcfcxdidmecfnfxgegyhdheiyj"
    "njykglfldmhmsnnonpsqdrdsesptktbutvewmwzytaeatbabzcecndrehetfhfggtghhpidinjoktkblplkmuonvehkrn",
    "ur:ripar-cosign-req/6-11/lpambdcfaoutcymhutmhihhdfxjlkokilrlumonlnbosplrerfsrsgtttpurvawewkzoaoasbec"
    "hckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlwtylzeahbnbwcycldedlenfsutktdtlp",
    "ur:ripar-cosign-req/8-11/lpaybdcfaoutcymhutmhihhdfxcfcxdidmecfnfxgegyhdheiyjnjykglfldmhmsnnonpsqdrds"
    "esptktbutvewmwzytaeatbabzcecndrehetfhfggtghhpidinjoktkblplkmunyoypdperprysssbtdtavtvdfdckdpte",
    "ur:ripar-cosign-req/10-11/lpbkbdcfaoutcymhutmhihhdfxsrsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhlie"
    "jejpkklaltmnmdnsotpkparorsswsntyuyvowlwtylzeahbnbwcycldedlenfsfygrgmhkhniojtkpkelslemetycykgsp",
    "ur:ripar-cosign-req/61-11/lpcsfsbdcfaoutcymhutmhihhdfxvafdaeheheiojlgwlbltmynenemspepersrltksntswzfx"
    "wzqdwffyaabncebnbnaaaaaaaakebnceztaaaaaaaabnztbnbnaaaaaaaacebnkeceaaaaaaaabncebnbnaaaaaaflgmglfn",
    "ur:ripar-cosign-req/62-11/lpcsfmbdcfaoutcymhutmhihhdfxylttuydtfhclhpinktjsjehkdladdntatswnzowlurclfr"
    "dthggyjekkjlfpdnesemttuywlzmvyuydtemehdnhkjllyjehkhgehfrdturvyzowltsttdnesdlfpjekkktgyhpwnpmpeby",
    "ur:ripar-cosign-req/63-11/lpcsfhbdcfaoutcymhutmhihhdfxecfrdpurwezoyktstldnfsdlhljekpktgohpdpfhdpuytl"
    "ylykwmutdlfsdngohgkpkgjnhedpfrectstlwmzcwsutdnecemgohpjnlbjnhpgoemecdnutwszcwmtltsecfrdplpoloxdk",
    "ur:ripar-cosign-req/64-11/lpcsfzbdcfaoutcymhutmhihhdfxcfcxdidmecfnfxgegyhdheiyjnjykglfldmhmsnnonpsqd"
    "rdsesptktbutvewmwzytaeatbabzcecndrehetfhfggtghhpidinjoktkblplkmunyoypdperprysssbtdtavtvdmkvylecw",
    "ur:ripar-cosign-req/65-11/lpcsfpbdcfaoutcymhutmhihhdfxcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplre"
    "rfsrsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlcagugttp",
    "ur:ripar-cosign-req/66-11/lpcsfwbdcfaoutcymhutmhihhdfxcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplre"
    "rfsrsgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlsehdtydn",
    "ur:ripar-cosign-req/67-11/lpcsfxbdcfaoutcymhutmhihhdfxeoahdlsktezcylwetedafhdagujnktkigufedlaheoutts"
    "wewfvwurdaeodphghljklpjlfegufsemdptevwzmvwtedpemfsgufejllpjkhlhgdpeobgmdlpnswduelkjehtgacxdpdlgw",
    "ur:ripar-cosign-req/68-11/lpcsfybdcfaoutcymhutmhihhdfxcmrszefwgujykphfhgpdrhpkuyuozczeurtioylapyjsso"
    "kgdnjzvooyroostosntytetnytmhzmvaahbnbdbgbydetsfmfsfyfxgeptfzjlcmkpkekglflymkltplpmqzqdrdwzgokbly",
    "ur:ripar-cosign-req/69-11/lpcsfebdcfaoutcymhutmhihhdfxmkneolpmqzrksasotitsuevwwpwfzsadaybscmcadkdney"
    "esfzflglgohhiaimjskslblnlgmwndoeptpfrlrnsksftetnvyvswsynzcaabdbgcfcxbeiegogufyfxaeaeaeaepdurdary",
    "ur:ripar-cosign-req/70-11/lpcsfgbdcfaoutcymhutmhihhdfxhssnlstnvtwdwpwzyaaobncybedrdwcpeteygsfdfdlbrt"
    "jleekostlylslymylylslyltlylslynelylslyltlylslymylylslyltlylslyzmlylslyltlylslymylylslyltcfrlflmt",
};
static const size_t kStreamComboCount = 15;
static const uint8_t kStream2Msg[333] = {
    0xa4, 0x01, 0x50, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x02,
    0x19, 0x27, 0x9f, 0x09, 0x59, 0x01, 0x2c, 0x03, 0x0a, 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57,
    0x5e, 0x65, 0x6c, 0x73, 0x7a, 0x81, 0x88, 0x8f, 0x96, 0x9d, 0xa4, 0xab, 0xb2, 0xb9, 0xc0, 0xc7, 0xce, 0xd5, 0xdc, 0xe3,
    0xea, 0xf1, 0xf8, 0xff, 0x06, 0x0d, 0x14, 0x1b, 0x22, 0x29, 0x30, 0x37, 0x3e, 0x45, 0x4c, 0x53, 0x5a, 0x61, 0x68, 0x6f,
    0x76, 0x7d, 0x84, 0x8b, 0x92, 0x99, 0xa0, 0xa7, 0xae, 0xb5, 0xbc, 0xc3, 0xca, 0xd1, 0xd8, 0xdf, 0xe6, 0xed, 0xf4, 0xfb,
    0x02, 0x09, 0x10, 0x17, 0x1e, 0x25, 0x2c, 0x33, 0x3a, 0x41, 0x48, 0x4f, 0x56, 0x5d, 0x64, 0x6b, 0x72, 0x79, 0x80, 0x87,
    0x8e, 0x95, 0x9c, 0xa3, 0xaa, 0xb1, 0xb8, 0xbf, 0xc6, 0xcd, 0xd4, 0xdb, 0xe2, 0xe9, 0xf0, 0xf7, 0xfe, 0x05, 0x0c, 0x13,
    0x1a, 0x21, 0x28, 0x2f, 0x36, 0x3d, 0x44, 0x4b, 0x52, 0x59, 0x60, 0x67, 0x6e, 0x75, 0x7c, 0x83, 0x8a, 0x91, 0x98, 0x9f,
    0xa6, 0xad, 0xb4, 0xbb, 0xc2, 0xc9, 0xd0, 0xd7, 0xde, 0xe5, 0xec, 0xf3, 0xfa, 0x01, 0x08, 0x0f, 0x16, 0x1d, 0x24, 0x2b,
    0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63, 0x6a, 0x71, 0x78, 0x7f, 0x86, 0x8d, 0x94, 0x9b, 0xa2, 0xa9, 0xb0, 0xb7,
    0xbe, 0xc5, 0xcc, 0xd3, 0xda, 0xe1, 0xe8, 0xef, 0xf6, 0xfd, 0x04, 0x0b, 0x12, 0x19, 0x20, 0x27, 0x2e, 0x35, 0x3c, 0x43,
    0x4a, 0x51, 0x58, 0x5f, 0x66, 0x6d, 0x74, 0x7b, 0x82, 0x89, 0x90, 0x97, 0x9e, 0xa5, 0xac, 0xb3, 0xba, 0xc1, 0xc8, 0xcf,
    0xd6, 0xdd, 0xe4, 0xeb, 0xf2, 0xf9, 0x00, 0x07, 0x0e, 0x15, 0x1c, 0x23, 0x2a, 0x31, 0x38, 0x3f, 0x46, 0x4d, 0x54, 0x5b,
    0x62, 0x69, 0x70, 0x77, 0x7e, 0x85, 0x8c, 0x93, 0x9a, 0xa1, 0xa8, 0xaf, 0xb6, 0xbd, 0xc4, 0xcb, 0xd2, 0xd9, 0xe0, 0xe7,
    0xee, 0xf5, 0xfc, 0x03, 0x0a, 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57, 0x5e, 0x65, 0x6c, 0x73,
    0x7a, 0x81, 0x88, 0x8f, 0x96, 0x9d, 0xa4, 0xab, 0xb2, 0xb9, 0xc0, 0xc7, 0xce, 0xd5, 0xdc, 0xe3, 0xea, 0xf1, 0xf8, 0xff,
    0x06, 0x0d, 0x14, 0x1b, 0x22, 0x29, 0x30, 0x10, 0x64, 0x55, 0x53, 0x44, 0x43,
};
static const char* const kStream2Pure[] = {
    "ur:ripar-cosign-req/1-5/lpadahcfadgtcykkprfrnehdfxoxadgdaeadaoaxaaahamatayasbkbdbnbtbabsaocfdineashk"
    "addwaxbkbycsctdsdpeefrfwgagdhghyihjzjkknlylomymtntoxpyprrhrtsttotluovlwdwnyazmambtbbkeioasks",
    "ur:ripar-cosign-req/2-5/lpaoahcfadgtcykkprfrnehdfxcwcpdtdyemfmfegsguhthsisjlkokilrlumonlnbosplrerfsr"
    "sgtttpurvawewkzoaoasbechckdadweoftfpfdgwhfhliejejpkklaltmnmdnsotpkparorsswsntyuyvowlpebewsjl",
    "ur:ripar-cosign-req/3-5/lpaxahcfadgtcykkprfrnehdfxwtylzeahbnbwcycldedlenfsfygrgmhkhniojtkpkelslememk"
    "neolpmqzrksasotitsuevwwpwfzsadaybscmcadkdneyesfzflglgohhiaimjskslblnlgmwndoeptpfrlrneymonerh",
    "ur:ripar-cosign-req/4-5/lpaaahcfadgtcykkprfrnehdfxsksftetnvyvswsynzcaabdbgcfcxdidmecfnfxgegyhdheiyjn"
    "jykglfldmhmsnnonpsqdrdsesptktbutvewmwzytaeatbabzcecndrehetfhfggtghhpidinjoktkblplkmudtbdkpkk",
    "ur:ripar-cosign-req/5-5/lpahahcfadgtcykkprfrnehdfxnyoypdperprysssbtdtavtvdwyykztaxbkbycsctdsdpeefrfw"
    "gagdhghyihjzjkknlylomymtntoxpyprrhrtsttotluovlwdwnyazmambtbbcwcpdtdybeiegogufyfxaeaeiofdnbne",
};
static const size_t kStream2Count = 5;
static const uint8_t kSeedMsg[54] = {
    0xa1, 0x01, 0x58, 0x32, 0x9d, 0x34, 0x7f, 0x84, 0x1a, 0x4e, 0x2c, 0xe6, 0xbc, 0x88, 0x6e, 0x1a, 0xee, 0x74, 0xd8, 0x24,
    0x42, 0xb2, 0xf7, 0x64, 0x9c, 0x60, 0x6d, 0xae, 0xdb, 0xad, 0x06, 0xcf, 0x8f, 0x0f, 0x73, 0xc8, 0xe8, 0x34, 0xc2, 0xeb,
    0xb7, 0xd2, 0x86, 0x8d, 0x75, 0x82, 0x0a, 0xb4, 0xfb, 0x4e, 0x45, 0xa1, 0x00, 0x4c,
};
static const char* const kSeedParts[] = {
    "ur:seed/1-3/lpadaxcsencylobemohsgmoyadhdeynteelblrcygldwvarflojtcywyjydmylgdsa",
    "ur:seed/2-3/lpaoaxcsencylobemohsgmtpdkfwprylienshnjnpluypmamtkmybsjksptnglsoio",
    "ur:seed/3-3/lpaxaxcsencylobemohsgmvseesawmrltdlnlgkplfbkqzzoglfeoyaegsfmmnsrkn",
    "ur:seed/4-3/lpaaaxcsencylobemohsgmgaecnytadrvaytasjlsfdsgmflswdnrkwyetcnckvtpt",
    "ur:seed/5-3/lpahaxcsencylobemohsgmmebytpjeutlfihinaoidzczmfpasoxqzntwtsngogurp",
    "ur:seed/6-3/lpamaxcsencylobemohsgmtpdkfwprylienshnjnpluypmamtkmybsjkspuonlfsbw",
};
// fragment indexes of ur:seed parts 1..6: [[0], [1], [2], [0, 2], [0, 1, 2], [1]]
static const uint8_t kSmallCbor[118] = {
    0xa4, 0x01, 0x50, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x02,
    0x58, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x4c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x04, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const char* const kSmallUr = "UR:RIPAR-COSIGN/OXADGDAEADAOAXAAAHAMATAYASBKBDBNBTBABSAOHDFZAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAXGSAEAEAEAEAEAEAEAEAEAEAEAEAAGDAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEFMAENNNB";
// ---- END generated ----

// ---------------------------------------------------------------------------------------------------------------
// helpers

static Bytes H(const char* hex) {
  Bytes b;
  if (!from_hex(hex, b)) {
    std::printf("bad hex literal in test: %s\n", hex);
    b.clear();
  }
  return b;
}
static std::string hx(const Bytes& b) { return to_hex(b, false); }
static Bytes B(const uint8_t* p, size_t n) { return Bytes(p, p + n); }
static Bytes S(const std::string& s) { return Bytes(s.begin(), s.end()); }

static std::string upper(std::string s) {
  for (char& c : s)
    if (c >= 'a' && c <= 'z') c = char(c - 'a' + 'A');
  return s;
}

static bool dec(const char* hex, CborVal& v, std::string* err = nullptr) { return cbor_decode(H(hex), v, err); }
static bool dec_ok(const char* hex) {
  CborVal v;
  return dec(hex, v);
}
static bool rejects(const Bytes& b) {
  CborVal v;
  v.type = CborVal::UInt;
  v.u = 42;
  std::string err;
  bool ok = cbor_decode(b, v, &err);
  // on failure: an error message, and the output left untouched
  return !ok && !err.empty() && v.type == CborVal::UInt && v.u == 42;
}
static bool rejects(const char* hex) { return rejects(H(hex)); }

static double as_double(const CborVal& v) {
  double d;
  std::memcpy(&d, &v.u, 8);
  return d;
}

static std::string rep(const char* unit, size_t n) {
  std::string s;
  for (size_t i = 0; i < n; i++) s += unit;
  return s;
}

// ---------------------------------------------------------------------------------------------------------------
// CBOR writer: RFC 8949 Appendix A encodings + head boundaries

static void test_cbor_writer() {
  CHECK_SECTION("cbor writer: unsigned (RFC 8949 App. A + boundaries)");
  struct U {
    uint64_t v;
    const char* hex;
  } uints[] = {
      {0, "00"},
      {1, "01"},
      {10, "0a"},
      {23, "17"},
      {24, "1818"},
      {25, "1819"},
      {100, "1864"},
      {255, "18ff"},
      {256, "190100"},
      {1000, "1903e8"},
      {65535, "19ffff"},
      {65536, "1a00010000"},
      {1000000, "1a000f4240"},
      {0xFFFFFFFFull, "1affffffff"},
      {0x100000000ull, "1b0000000100000000"},
      {1000000000000ull, "1b000000e8d4a51000"},
      {18446744073709551615ull, "1bffffffffffffffff"},
  };
  for (const U& u : uints) {
    CborWriter w;
    w.uint(u.v);
    CHECK_EQ(hx(w.out()), std::string(u.hex));
  }

  CHECK_SECTION("cbor writer: negative");
  struct N {
    uint64_t v;
    const char* hex;
  } nints[] = {{0, "20"}, {9, "29"}, {99, "3863"}, {999, "3903e7"}, {23, "37"}, {24, "3818"},
               {18446744073709551615ull, "3bffffffffffffffff"}};
  for (const N& n : nints) {
    CborWriter w;
    w.nint(n.v);  // -1 - v : -1, -10, -100, -1000, -24, -25, -18446744073709551616
    CHECK_EQ(hx(w.out()), std::string(n.hex));
  }

  CHECK_SECTION("cbor writer: strings");
  {
    CborWriter w;
    w.bytes(nullptr, 0);
    CHECK_EQ(hx(w.out()), std::string("40"));
  }
  {
    CborWriter w;
    w.bytes(H("01020304"));
    CHECK_EQ(hx(w.out()), std::string("4401020304"));
  }
  {
    CborWriter w;
    Bytes b(24, 0xAB);
    w.bytes(b);
    CHECK_EQ(hx(w.out()), "5818" + hx(b));
  }
  {
    CborWriter w;
    Bytes b(300, 0x01);
    w.bytes(b);
    CHECK_EQ(hx(Bytes(w.out().begin(), w.out().begin() + 3)), std::string("59012c"));
    CHECK_EQ(w.out().size(), size_t(303));
  }
  struct T {
    const char* s;
    const char* hex;
  } texts[] = {{"", "60"},
               {"a", "6161"},
               {"IETF", "6449455446"},
               {"\"\\", "62225c"},
               {"\xc3\xbc", "62c3bc"},
               {"\xe6\xb0\xb4", "63e6b0b4"},
               {"\xf0\x90\x85\x91", "64f0908591"}};
  for (const T& t : texts) {
    CborWriter w;
    w.text(t.s);
    CHECK_EQ(hx(w.out()), std::string(t.hex));
  }

  CHECK_SECTION("cbor writer: containers, tags, simple");
  {
    CborWriter w;
    w.array(0);
    CHECK_EQ(hx(w.out()), std::string("80"));
  }
  {
    CborWriter w;  // [1, [2, 3], [4, 5]]
    w.array(3);
    w.uint(1);
    w.array(2);
    w.uint(2);
    w.uint(3);
    w.array(2);
    w.uint(4);
    w.uint(5);
    CHECK_EQ(hx(w.out()), std::string("8301820203820405"));
  }
  {
    CborWriter w;  // [1..25]
    w.array(25);
    for (uint64_t i = 1; i <= 25; i++) w.uint(i);
    CHECK_EQ(hx(w.out()), std::string("98190102030405060708090a0b0c0d0e0f101112131415161718181819"));
  }
  {
    CborWriter w;
    w.map(0);
    CHECK_EQ(hx(w.out()), std::string("a0"));
  }
  {
    CborWriter w;  // {1: 2, 3: 4}
    w.map(2);
    w.uint(1);
    w.uint(2);
    w.uint(3);
    w.uint(4);
    CHECK_EQ(hx(w.out()), std::string("a201020304"));
  }
  {
    CborWriter w;  // {"a": 1, "b": [2, 3]}
    w.map(2);
    w.text("a");
    w.uint(1);
    w.text("b");
    w.array(2);
    w.uint(2);
    w.uint(3);
    CHECK_EQ(hx(w.out()), std::string("a26161016162820203"));
  }
  {
    CborWriter w;  // ["a", {"b": "c"}]
    w.array(2);
    w.text("a");
    w.map(1);
    w.text("b");
    w.text("c");
    CHECK_EQ(hx(w.out()), std::string("826161a161626163"));
  }
  {
    CborWriter w;  // {"a": "A", ..., "e": "E"}
    w.map(5);
    const char* k[] = {"a", "b", "c", "d", "e"};
    const char* v[] = {"A", "B", "C", "D", "E"};
    for (int i = 0; i < 5; i++) {
      w.text(k[i]);
      w.text(v[i]);
    }
    CHECK_EQ(hx(w.out()), std::string("a56161614161626142616361436164614461656145"));
  }
  {
    CborWriter w;
    w.tag(0);
    w.text("2013-03-21T20:04:00Z");
    CHECK_EQ(hx(w.out()), std::string("c074323031332d30332d32315432303a30343a30305a"));
  }
  {
    CborWriter w;
    w.tag(1);
    w.uint(1363896240);
    CHECK_EQ(hx(w.out()), std::string("c11a514b67b0"));
  }
  {
    CborWriter w;
    w.tag(23);
    w.bytes(H("01020304"));
    CHECK_EQ(hx(w.out()), std::string("d74401020304"));
  }
  {
    CborWriter w;
    w.tag(24);
    w.bytes(H("6449455446"));
    CHECK_EQ(hx(w.out()), std::string("d818456449455446"));
  }
  {
    CborWriter w;
    w.tag(32);
    w.text("http://www.example.com");
    CHECK_EQ(hx(w.out()), std::string("d82076687474703a2f2f7777772e6578616d706c652e636f6d"));
  }
  {
    CborWriter w;
    w.tag(37);  // UUID tag used for request ids
    w.bytes(Bytes(16, 0x11));
    CHECK_EQ(hx(w.out()), "d82550" + rep("11", 16));
  }
  {
    CborWriter w;
    w.boolean(false);
    w.boolean(true);
    w.null();
    CHECK_EQ(hx(w.out()), std::string("f4f5f6"));
    Bytes t = w.take();
    CHECK_EQ(hx(t), std::string("f4f5f6"));
  }
}

// ---------------------------------------------------------------------------------------------------------------
// CBOR decoder: RFC 8949 Appendix A (well-formed), values, limits, malformed

static void test_cbor_decoder_values() {
  CHECK_SECTION("cbor decode: integers");
  CborVal v;
  CHECK(dec("00", v) && v.type == CborVal::UInt && v.u == 0);
  CHECK(dec("17", v) && v.type == CborVal::UInt && v.u == 23);
  CHECK(dec("1818", v) && v.u == 24);
  CHECK(dec("1903e8", v) && v.u == 1000);
  CHECK(dec("1a000f4240", v) && v.u == 1000000);
  CHECK(dec("1b000000e8d4a51000", v) && v.u == 1000000000000ull);
  CHECK(dec("1bffffffffffffffff", v) && v.type == CborVal::UInt && v.u == 18446744073709551615ull);
  CHECK(dec("20", v) && v.type == CborVal::NInt && v.u == 0);    // -1
  CHECK(dec("29", v) && v.type == CborVal::NInt && v.u == 9);    // -10
  CHECK(dec("3863", v) && v.type == CborVal::NInt && v.u == 99);  // -100
  CHECK(dec("3903e7", v) && v.type == CborVal::NInt && v.u == 999);
  CHECK(dec("3bffffffffffffffff", v) && v.type == CborVal::NInt && v.u == 18446744073709551615ull);
  // bignums are just tags 2/3 around a byte string
  CHECK(dec("c249010000000000000000", v) && v.type == CborVal::Tag && v.u == 2 && v.items.size() == 1u &&
        v.items[0].type == CborVal::Bytes_ && hx(v.items[0].b) == "010000000000000000");
  CHECK(dec("c349010000000000000000", v) && v.type == CborVal::Tag && v.u == 3);
  // non-minimal heads are accepted on input (the writer never produces them)
  CHECK(dec("1801", v) && v.type == CborVal::UInt && v.u == 1);
  CHECK(dec("1b0000000000000001", v) && v.u == 1);
  CHECK(dec("5a0000000161", v) && v.type == CborVal::Bytes_ && hx(v.b) == "61");

  CHECK_SECTION("cbor decode: floats and simple values");
  CHECK(dec("f90000", v) && v.type == CborVal::Float && as_double(v) == 0.0 && !std::signbit(as_double(v)));
  CHECK(dec("f98000", v) && as_double(v) == 0.0 && std::signbit(as_double(v)));
  CHECK(dec("f93c00", v) && as_double(v) == 1.0);
  CHECK(dec("fb3ff199999999999a", v) && as_double(v) == 1.1);
  CHECK(dec("f93e00", v) && as_double(v) == 1.5);
  CHECK(dec("f97bff", v) && as_double(v) == 65504.0);
  CHECK(dec("fa47c35000", v) && as_double(v) == 100000.0);
  CHECK(dec("fa7f7fffff", v) && as_double(v) == 3.4028234663852886e+38);
  CHECK(dec("fb7e37e43c8800759c", v) && as_double(v) == 1.0e+300);
  CHECK(dec("f90001", v) && as_double(v) == std::ldexp(1.0, -24));  // 5.960464477539063e-8
  CHECK(dec("f90400", v) && as_double(v) == 0.00006103515625);
  CHECK(dec("f9c400", v) && as_double(v) == -4.0);
  CHECK(dec("fbc010666666666666", v) && as_double(v) == -4.1);
  CHECK(dec("f97c00", v) && std::isinf(as_double(v)) && as_double(v) > 0);
  CHECK(dec("f97e00", v) && std::isnan(as_double(v)));
  CHECK(dec("f9fc00", v) && std::isinf(as_double(v)) && as_double(v) < 0);
  CHECK(dec("fa7f800000", v) && std::isinf(as_double(v)) && as_double(v) > 0);
  CHECK(dec("fa7fc00000", v) && std::isnan(as_double(v)));
  CHECK(dec("faff800000", v) && std::isinf(as_double(v)) && as_double(v) < 0);
  CHECK(dec("fb7ff0000000000000", v) && std::isinf(as_double(v)));
  CHECK(dec("fb7ff8000000000000", v) && std::isnan(as_double(v)));
  CHECK(dec("fbfff0000000000000", v) && std::isinf(as_double(v)) && as_double(v) < 0);
  CHECK(dec("fa00000001", v) && as_double(v) == std::ldexp(1.0, -149));  // smallest single subnormal
  CHECK(dec("f903ff", v) && as_double(v) == std::ldexp(1023.0, -24));     // largest half subnormal
  CHECK(dec("f4", v) && v.type == CborVal::Bool && v.u == 0);
  CHECK(dec("f5", v) && v.type == CborVal::Bool && v.u == 1);
  CHECK(dec("f6", v) && v.type == CborVal::Null);
  CHECK(dec("f7", v) && v.type == CborVal::Undefined);
  CHECK(rejects("f0"));    // simple(16): unassigned, not representable
  CHECK(rejects("f8ff"));  // simple(255)
  CHECK(rejects("f818"));  // two-byte simple < 32: not well-formed

  CHECK_SECTION("cbor decode: strings, tags");
  CHECK(dec("40", v) && v.type == CborVal::Bytes_ && v.b.empty());
  CHECK(dec("4401020304", v) && v.type == CborVal::Bytes_ && hx(v.b) == "01020304");
  CHECK(dec("60", v) && v.type == CborVal::Text && v.str().empty());
  CHECK(dec("6449455446", v) && v.type == CborVal::Text && v.str() == "IETF");
  CHECK(dec("62225c", v) && v.str() == "\"\\");
  CHECK(dec("62c3bc", v) && v.str() == "\xc3\xbc");
  CHECK(dec("63e6b0b4", v) && v.str() == "\xe6\xb0\xb4");
  CHECK(dec("64f0908591", v) && v.str() == "\xf0\x90\x85\x91");
  CHECK(dec("c074323031332d30332d32315432303a30343a30305a", v) && v.type == CborVal::Tag && v.u == 0 &&
        v.items.size() == 1u && v.items[0].str() == "2013-03-21T20:04:00Z");
  CHECK(dec("c11a514b67b0", v) && v.u == 1 && v.items[0].type == CborVal::UInt && v.items[0].u == 1363896240);
  CHECK(dec("c1fb41d452d9ec200000", v) && v.u == 1 && v.items[0].type == CborVal::Float &&
        as_double(v.items[0]) == 1363896240.5);
  CHECK(dec("d74401020304", v) && v.u == 23 && hx(v.items[0].b) == "01020304");
  CHECK(dec("d818456449455446", v) && v.u == 24 && hx(v.items[0].b) == "6449455446");
  CHECK(dec("d82076687474703a2f2f7777772e6578616d706c652e636f6d", v) && v.u == 32 &&
        v.items[0].str() == "http://www.example.com");

  CHECK_SECTION("cbor decode: arrays and maps");
  CHECK(dec("80", v) && v.type == CborVal::Array && v.items.empty());
  CHECK(dec("83010203", v) && v.items.size() == 3u && v.items[2].u == 3);
  CHECK(dec("8301820203820405", v) && v.items.size() == 3u && v.items[1].type == CborVal::Array &&
        v.items[2].items[1].u == 5);
  CHECK(dec("98190102030405060708090a0b0c0d0e0f101112131415161718181819", v) && v.items.size() == 25u &&
        v.items[24].u == 25);
  CHECK(dec("a0", v) && v.type == CborVal::Map && v.items.empty());
  CHECK(dec("a201020304", v) && v.type == CborVal::Map && v.items.size() == 4u);
  {
    const CborVal* a = cbor_get(v, 1);
    const CborVal* b = cbor_get(v, 3);
    CHECK(a && a->type == CborVal::UInt && a->u == 2);
    CHECK(b && b->u == 4);
    CHECK(cbor_get(v, 2) == nullptr);  // 2 is a value, not a key
    CHECK(cbor_get(v, 4) == nullptr);
  }
  CHECK(dec("a26161016162820203", v) && v.items[0].str() == "a" && v.items[3].items.size() == 2u);
  CHECK(cbor_get(v, 1) == nullptr);  // text keys are not found by uint lookup
  CHECK(dec("826161a161626163", v) && v.items[1].type == CborVal::Map && v.items[1].items[1].str() == "c");
  CHECK(dec("a56161614161626142616361436164614461656145", v) && v.items.size() == 10u && v.items[9].str() == "E");
  CHECK(dec("83010203", v) && cbor_get(v, 0) == nullptr);  // not a map
  CHECK(dec("a1200a", v) && cbor_get(v, 0) == nullptr);    // key -1 is not key 0
}

static void test_cbor_decoder_malformed() {
  CHECK_SECTION("cbor decode: indefinite lengths rejected (RFC 8949 App. A)");
  CHECK(rejects("5f42010243030405ff"));
  CHECK(rejects("7f657374726561646d696e67ff"));
  CHECK(rejects("9fff"));
  CHECK(rejects("9f018202039f0405ffff"));
  CHECK(rejects("9f01820203820405ff"));
  CHECK(rejects("83018202039f0405ff"));
  CHECK(rejects("83019f0203ff820405"));
  CHECK(rejects("bf61610161629f0203ffff"));
  CHECK(rejects("826161bf61626163ff"));
  CHECK(rejects("bf6346756ef563416d7421ff"));
  CHECK(rejects("1f"));  // indefinite on int: malformed
  CHECK(rejects("3f"));
  CHECK(rejects("df00"));  // indefinite tag
  CHECK(rejects("ff"));    // stray break

  CHECK_SECTION("cbor decode: truncated / reserved / trailing");
  CHECK(rejects(Bytes()));
  {
    CborVal v;
    CHECK(!cbor_decode(nullptr, 0, v));
  }
  const char* bad[] = {"18", "1900", "1a000000", "1b00000000000000", "38", "5801", "4201", "6261", "7801", "81",
                       "8201", "a1", "a101", "a20102", "c0", "d8", "d825", "f9", "f900", "fa000000", "fb00000000000000",
                       "f8", "1c", "1d", "1e", "3c", "5c", "7c", "9c", "bc", "dc", "fc", "fd", "fe", "0000", "8000",
                       "a0a0", "f6f6", "83010203ff", "4000", "60ff"};
  for (const char* h : bad)
    if (!CHECK(rejects(h))) std::printf("     input %s\n", h);
  // declared lengths far beyond the input must fail without allocating them
  CHECK(rejects("5bffffffffffffffff"));
  CHECK(rejects("5b000000010000000000"));
  CHECK(rejects("7bffffffffffffffff"));
  CHECK(rejects("9bffffffffffffffff"));
  CHECK(rejects("bbffffffffffffffff"));
  CHECK(rejects("9a00000100"));  // 256 elements declared, none present
  CHECK(rejects("5aff000000"));

  CHECK_SECTION("cbor decode: invalid UTF-8 text rejected");
  const char* badtext[] = {"61ff", "6180", "62c080", "62c1bf", "63e08080", "63eda080", "64f4908080", "64f8888080",
                           "62c328", "61c3"};
  for (const char* h : badtext)
    if (!CHECK(rejects(h))) std::printf("     input %s\n", h);
  CHECK(dec_ok("63efbfbf"));    // U+FFFF
  CHECK(dec_ok("64f48fbfbf"));  // U+10FFFF
  CHECK(dec_ok("63ed9fbf"));    // U+D7FF

  CHECK_SECTION("cbor decode: duplicate map keys rejected");
  CHECK(rejects("a201020103"));
  CHECK(rejects("a20102180103"));        // same key 1, non-minimal head
  CHECK(rejects("a26161016161f6"));      // "a" twice
  CHECK(rejects("a2410001410002"));      // h'00' twice
  CHECK(rejects("a2820102f6820102f6"));  // [1,2] twice
  CHECK(rejects("a3010002000100"));      // 1, 2, 1
  CHECK(rejects("a2c10100c10100"));      // tagged keys
  CHECK(dec_ok("a2616101416102"));       // "a" vs h'61': different types
  CHECK(dec_ok("a2200000f6"));           // -1 vs 0
  CHECK(dec_ok("a2c10100c20100"));       // 1(1) vs 2(1)
  CHECK(dec_ok("a2a10102f6a10103f6"));   // {1:2} vs {1:3}

  CHECK_SECTION("cbor decode: nesting depth <= 8");
  CHECK(dec_ok((rep("81", 7) + "80").c_str()));        // 8 nested arrays
  CHECK(rejects((rep("81", 8) + "80").c_str()));       // 9
  CHECK(dec_ok((rep("81", 7) + "00").c_str()));        // scalar inside the 7th
  CHECK(dec_ok((rep("c1", 8) + "00").c_str()));        // 8 nested tags
  CHECK(rejects((rep("c1", 9) + "00").c_str()));       // 9
  CHECK(dec_ok((rep("a101", 7) + "a0").c_str()));      // 8 nested maps
  CHECK(rejects((rep("a101", 8) + "a0").c_str()));     // 9
  CHECK(dec_ok((rep("81", 6) + "c180").c_str()));      // arrays + tag + array = 8
  CHECK(rejects((rep("81", 7) + "c180").c_str()));     // 9
  CHECK(rejects((rep("81", 100) + "00").c_str()));     // deep garbage
  CHECK(rejects((rep("9f", 1000) + "00").c_str()));

  CHECK_SECTION("cbor decode: <= 256 items per container");
  CHECK(dec_ok(("990100" + rep("00", 256)).c_str()));
  CHECK(rejects(("990101" + rep("00", 257)).c_str()));
  {
    std::string m = "b90100";
    for (int k = 0; k < 256; k++) {
      char buf[16];
      std::snprintf(buf, sizeof buf, k < 24 ? "%02x00" : "18%02x00", k);
      m += buf;
    }
    CHECK(dec_ok(m.c_str()));
    std::string m2 = "b90101" + m.substr(6) + "19010000";  // 257 distinct keys
    CHECK(rejects(m2.c_str()));
  }
}

static void test_cbor_roundtrip() {
  CHECK_SECTION("cbor round trip: protocol-like request");
  CborWriter w;
  w.map(8);
  w.uint(1);
  w.tag(37);
  w.bytes(Bytes(16, 0xA5));
  w.uint(2);
  w.uint(10143);
  w.uint(3);
  w.bytes(Bytes(20, 0x11));
  w.uint(8);
  w.bytes(H("0de0b6b3a7640000"));
  w.uint(9);
  w.bytes(Bytes(68, 0x42));
  w.uint(11);
  w.uint(0xFFFFFFFFFFull);
  w.uint(12);
  w.map(2);
  w.uint(1);
  w.text("nansen");
  w.uint(4);
  w.uint(3);
  w.uint(16);
  w.text("AUSD");
  CborVal v;
  std::string err;
  CHECK(cbor_decode(w.out(), v, &err));
  CHECK_EQ(err, std::string());
  CHECK(v.type == CborVal::Map && v.items.size() == 16u);
  const CborVal* id = cbor_get(v, 1);
  CHECK(id && id->type == CborVal::Tag && id->u == 37 && id->items[0].b == Bytes(16, 0xA5));
  const CborVal* chain = cbor_get(v, 2);
  CHECK(chain && chain->type == CborVal::UInt && chain->u == 10143);
  const CborVal* val = cbor_get(v, 8);
  CHECK(val && val->type == CborVal::Bytes_ && hx(val->b) == "0de0b6b3a7640000");
  const CborVal* cd = cbor_get(v, 9);
  CHECK(cd && cd->b.size() == 68u);
  const CborVal* exp = cbor_get(v, 11);
  CHECK(exp && exp->u == 0xFFFFFFFFFFull);
  const CborVal* risk = cbor_get(v, 12);
  CHECK(risk && risk->type == CborVal::Map && cbor_get(*risk, 1) && cbor_get(*risk, 1)->str() == "nansen");
  CHECK(risk && cbor_get(*risk, 4) && cbor_get(*risk, 4)->u == 3);
  const CborVal* sym = cbor_get(v, 16);
  CHECK(sym && sym->type == CborVal::Text && sym->str() == "AUSD");
  CHECK(cbor_get(v, 5) == nullptr);
  // every strict prefix is truncated, and one extra byte is trailing
  const Bytes& all = w.out();
  bool all_prefixes_rejected = true;
  for (size_t n = 0; n < all.size(); n++)
    if (!rejects(Bytes(all.begin(), all.begin() + std::ptrdiff_t(n)))) all_prefixes_rejected = false;
  CHECK(all_prefixes_rejected);
  Bytes extra = all;
  extra.push_back(0x00);
  CHECK(rejects(extra));
}

// ---------------------------------------------------------------------------------------------------------------
// Bytewords

static void test_bytewords() {
  CHECK_SECTION("bytewords: official vectors");
  const Bytes in1 = {0, 1, 2, 128, 255};
  CHECK_EQ(bytewords_minimal_encode(in1), std::string("aeadaolazmjendeoti"));  // bc-ur test_bytewords_1
  Bytes out;
  CHECK(bytewords_minimal_decode("aeadaolazmjendeoti", out) && out == in1);
  out.clear();
  CHECK(bytewords_minimal_decode("AEADAOLAZMJENDEOTI", out) && out == in1);
  const uint8_t in2[100] = {245, 215, 20,  198, 241, 235, 69,  59,  209, 205, 165, 18,  150, 158, 116, 135, 229,
                            212, 19,  159, 17,  37,  239, 240, 253, 11,  109, 191, 37,  242, 38,  120, 223, 41,
                            156, 189, 242, 254, 147, 204, 66,  163, 216, 175, 191, 72,  169, 54,  32,  60,  144,
                            230, 210, 137, 184, 197, 33,  113, 88,  14,  157, 31,  177, 46,  1,   115, 205, 69,
                            225, 150, 65,  235, 58,  144, 65,  240, 133, 69,  113, 247, 63,  53,  242, 165, 160,
                            144, 26,  13,  79,  237, 133, 71,  82,  69,  254, 165, 138, 41,  85,  24};
  const char* min2 =
      "yktsbbswwnwmfefrttsnonbgmtnnjyltvwtybwnebydawswtzcbdjnrsdawzdsksurdtnsrywzzemusffwottppersfdptencxfnmhvatdl"
      "droskcljshdbantctpadmadjksnfevymtfpwmftmhfpwtlpfejsylfhecwzonnbmhcybtgwwelpflgmfezeonledtgocsfzhycypf";
  CHECK_EQ(bytewords_minimal_encode(B(in2, 100)), std::string(min2));  // bc-ur test_bytewords_2
  CHECK(bytewords_minimal_decode(min2, out) && out == B(in2, 100));
  // BCR-2020-012 example
  const Bytes spec = H("d99d6ca20150c7098580125e2ab0981253468b2dbc5202c11947da");
  CHECK_EQ(bytewords_minimal_encode(spec), std::string("tantjzoeadgdstaslplabghydrpfmkbggufgludprfgmaosecffltnsoaawkbd"));
  CHECK_EQ(crc32(spec.data(), spec.size()), 0xC904F40Bu);

  CHECK_SECTION("bytewords: table (256 unique minimal words, all round trip)");
  std::vector<std::string> seen;
  bool all_rt = true;
  for (int b = 0; b < 256; b++) {
    const Bytes one = {uint8_t(b)};
    const std::string e = bytewords_minimal_encode(one);
    if (e.size() != 10u) all_rt = false;
    seen.push_back(e.substr(0, 2));
    Bytes d;
    if (!bytewords_minimal_decode(e, d) || d != one) all_rt = false;
    if (!bytewords_minimal_decode(upper(e), d) || d != one) all_rt = false;
  }
  CHECK(all_rt);
  std::sort(seen.begin(), seen.end());
  CHECK(std::unique(seen.begin(), seen.end()) == seen.end());
  CHECK_EQ(seen.size(), size_t(256));
  // first and last words of the list
  CHECK_EQ(bytewords_minimal_encode(Bytes{0x00}).substr(0, 2), std::string("ae"));  // able
  CHECK_EQ(bytewords_minimal_encode(Bytes{0x80}).substr(0, 2), std::string("la"));  // lava
  CHECK_EQ(bytewords_minimal_encode(Bytes{0xFF}).substr(0, 2), std::string("zm"));  // zoom

  CHECK_SECTION("bytewords: rejects");
  Bytes keep = {9, 9};
  CHECK(!bytewords_minimal_decode("aeadaolazmjendeotz", keep));  // "tz" is no word
  CHECK(!bytewords_minimal_decode("aeadaolazmjendeota", keep));  // last word changed -> CRC
  CHECK(!bytewords_minimal_decode("adadaolazmjendeoti", keep));  // payload changed -> CRC
  CHECK(!bytewords_minimal_decode("aeadaolazmjendeot", keep));   // odd length
  CHECK(!bytewords_minimal_decode("", keep));
  CHECK(!bytewords_minimal_decode(bytewords_minimal_encode(Bytes()), keep));  // CRC only: no payload
  CHECK(!bytewords_minimal_decode("ae1daolazmjendeoti", keep));
  CHECK(!bytewords_minimal_decode("ae adaolazmjendeoti", keep));
  CHECK(!bytewords_minimal_decode("aeadaolazmjendeoti ", keep));
  CHECK(keep == (Bytes{9, 9}));  // untouched on failure
}

// ---------------------------------------------------------------------------------------------------------------
// Single-part UR

static void test_ur_single() {
  CHECK_SECTION("ur single part: official bc-ur vector");
  const char* official =
      "ur:bytes/hdeymejtswhhylkepmykhhtsytsnoyoyaxaedsuttydmmhhpktpmsrjtgwdpfnsboxgwlbaawzuefywkdplrsrjynbvygabwjld"
      "apfcsdwkbrkch";
  CHECK_EQ(ur_encode("bytes", B(kWolf50Cbor, sizeof kWolf50Cbor)), upper(official));
  CHECK_EQ(ur_encode("BYTES", B(kWolf50Cbor, sizeof kWolf50Cbor)), upper(official));
  UrDecoder d;
  CHECK_EQ(d.receive(official), UrDecoder::Complete);
  CHECK(d.complete());
  CHECK_EQ(d.type(), std::string("bytes"));
  CHECK(d.message() == B(kWolf50Cbor, sizeof kWolf50Cbor));
  CHECK(d.progress() == 1.0f);
  CHECK_EQ(d.receive(official), UrDecoder::Ignored);  // already complete
  d.reset();
  CHECK(!d.complete() && d.message().empty() && d.type().empty());
  CHECK_EQ(d.receive(upper(official)), UrDecoder::Complete);
  CHECK(d.message() == B(kWolf50Cbor, sizeof kWolf50Cbor));

  CHECK_SECTION("ur single part: BCR-2020-005 ur:seed example");
  d.reset();
  const char* seed =
      "ur:seed/oyadhdeynteelblrcygldwvarflojtcywyjytpdkfwprylienshnjnpluypmamtkmybsjkspvseesawmrltdlnlgkplfbkqzzoglf"
      "eoyaegslobemohs";
  CHECK_EQ(d.receive(seed), UrDecoder::Complete);
  CHECK_EQ(d.type(), std::string("seed"));
  CHECK(d.message() == B(kSeedMsg, sizeof kSeedMsg));
  CborVal v;
  CHECK(cbor_decode(d.message(), v) && v.type == CborVal::Map && cbor_get(v, 1) && cbor_get(v, 1)->b.size() == 50u);
  CHECK_EQ(ur_encode("seed", d.message()), upper(seed));

  CHECK_SECTION("ur single part: device output shape");
  const Bytes small = B(kSmallCbor, sizeof kSmallCbor);
  const std::string u = ur_encode("ripar-cosign", small);
  CHECK_EQ(u, std::string(kSmallUr));
  bool alnum = true;  // QR alphanumeric mode: 0-9 A-Z space $ % * + - . / :
  for (char c : u)
    if (!((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || std::strchr(" $%*+-./:", c))) alnum = false;
  CHECK(alnum);
  d.reset();
  CHECK_EQ(d.receive(u), UrDecoder::Complete);
  CHECK(d.message() == small && d.type() == "ripar-cosign");

  CHECK_SECTION("ur single part: rejects");
  d.reset();
  CHECK_EQ(d.receive("hello"), UrDecoder::Ignored);
  CHECK_EQ(d.receive(""), UrDecoder::Ignored);
  CHECK_EQ(d.receive("u"), UrDecoder::Ignored);
  CHECK_EQ(d.receive("https://example.com/ur:bytes"), UrDecoder::Ignored);
  CHECK_EQ(d.receive("ur:bytes"), UrDecoder::Error);
  CHECK(!d.error().empty());
  CHECK_EQ(d.receive("ur:/aeadaolazmjendeoti"), UrDecoder::Error);
  CHECK_EQ(d.receive("ur:by_tes/aeadaolazmjendeoti"), UrDecoder::Error);
  CHECK_EQ(d.receive("ur:bytes/aeadaolazmjendeotz"), UrDecoder::Error);  // bad word
  CHECK_EQ(d.receive("ur:bytes/aeadaolazmjendeota"), UrDecoder::Error);  // bad CRC
  CHECK_EQ(d.receive("ur:bytes/"), UrDecoder::Error);
  CHECK(!d.complete());
  CHECK_EQ(d.receive("UR:BYTES/AEADAOLAZMJENDEOTI"), UrDecoder::Complete);  // any valid body completes
  CHECK(d.message() == (Bytes{0, 1, 2, 128, 255}));
}

// ---------------------------------------------------------------------------------------------------------------
// Fountain selection (official vectors)

static std::vector<size_t> parse_idx(const char* s) {
  std::vector<size_t> r;
  size_t cur = 0;
  bool any = false;
  for (const char* p = s;; p++) {
    if (*p >= '0' && *p <= '9') {
      cur = cur * 10 + size_t(*p - '0');
      any = true;
    } else {
      if (any) r.push_back(cur);
      cur = 0;
      any = false;
      if (!*p) break;
    }
  }
  return r;
}

static void test_choose_fragments() {
  CHECK_SECTION("fountain: choose_fragments (bc-ur test_choose_fragments)");
  const char* expected[30] = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "9", "2,5,6,8,9,10", "8", "1,5",
                              "1", "0,2,4,5,8,10", "5", "2", "2", "0,1,3,4,5,7,9,10", "0,1,2,3,5,6,8,9,10",
                              "0,2,4,5,7,8,9,10", "3,5", "4", "0,1,2,3,4,5,6,7,8,9,10", "0,1,3,4,5,6,7,9,10", "6",
                              "5,6", "7"};
  for (uint32_t s = 1; s <= 30; s++) {
    std::vector<size_t> got = ur_choose_fragments(s, kWolf1024SeqLen, kWolf1024Crc);
    if (!CHECK(got == parse_idx(expected[s - 1]))) std::printf("     seq %u\n", unsigned(s));
  }
  CHECK_SECTION("fountain: choose_fragments (python stream)");
  for (size_t k = 0; k < kStreamMixedCount; k++) {
    std::vector<size_t> got = ur_choose_fragments(uint32_t(kStreamSeqLen + 1 + k), kStreamSeqLen, kStreamCrc);
    if (!CHECK(got == parse_idx(kStreamMixedIdx[k]))) std::printf("     part %u\n", unsigned(kStreamSeqLen + 1 + k));
  }
  CHECK(ur_choose_fragments(0, 5, 1).empty());
  CHECK(ur_choose_fragments(1, 0, 1).empty());
  CHECK(ur_choose_fragments(3, 5, 1) == std::vector<size_t>{2});
  // degree is always within [1, seqLen] and indexes are distinct and in range
  bool sane = true;
  for (uint32_t s = 1; s < 400; s++) {
    std::vector<size_t> r = ur_choose_fragments(s, 37, 0xDEADBEEF);
    if (r.empty() || r.size() > 37u || r.back() >= 37u) sane = false;
    for (size_t i = 1; i < r.size(); i++)
      if (r[i] <= r[i - 1]) sane = false;
  }
  CHECK(sane);
}

// ---------------------------------------------------------------------------------------------------------------
// Multipart decoding

static const char* const kOfficialParts[20] = {
    "ur:bytes/1-9/lpadascfadaxcywenbpljkhdcahkadaemejtswhhylkepmykhhtsytsnoyoyaxaedsuttydmmhhpktpmsrjtdkgslpgh",
    "ur:bytes/2-9/lpaoascfadaxcywenbpljkhdcagwdpfnsboxgwlbaawzuefywkdplrsrjynbvygabwjldapfcsgmghhkhstlrdcxaefz",
    "ur:bytes/3-9/lpaxascfadaxcywenbpljkhdcahelbknlkuejnbadmssfhfrdpsbiegecpasvssovlgeykssjykklronvsjksopdzmol",
    "ur:bytes/4-9/lpaaascfadaxcywenbpljkhdcasotkhemthydawydtaxneurlkosgwcekonertkbrlwmplssjtammdplolsbrdzcrtas",
    "ur:bytes/5-9/lpahascfadaxcywenbpljkhdcatbbdfmssrkzmcwnezelennjpfzbgmuktrhtejscktelgfpdlrkfyfwdajldejokbwf",
    "ur:bytes/6-9/lpamascfadaxcywenbpljkhdcackjlhkhybssklbwefectpfnbbectrljectpavyrolkzczcpkmwidmwoxkilghdsowp",
    "ur:bytes/7-9/lpatascfadaxcywenbpljkhdcavszmwnjkwtclrtvaynhpahrtoxmwvwatmedibkaegdosftvandiodagdhthtrlnnhy",
    "ur:bytes/8-9/lpayascfadaxcywenbpljkhdcadmsponkkbbhgsoltjntegepmttmoonftnbuoiyrehfrtsabzsttorodklubbuyaetk",
    "ur:bytes/9-9/lpasascfadaxcywenbpljkhdcajskecpmdckihdyhphfotjojtfmlnwmadspaxrkytbztpbauotbgtgtaeaevtgavtny",
    "ur:bytes/10-9/lpbkascfadaxcywenbpljkhdcahkadaemejtswhhylkepmykhhtsytsnoyoyaxaedsuttydmmhhpktpmsrjtwdkiplzs",
    "ur:bytes/11-9/lpbdascfadaxcywenbpljkhdcahelbknlkuejnbadmssfhfrdpsbiegecpasvssovlgeykssjykklronvsjkvetiiapk",
    "ur:bytes/12-9/lpbnascfadaxcywenbpljkhdcarllaluzmdmgstospeyiefmwejlwtpedamktksrvlcygmzemovovllarodtmtbnptrs",
    "ur:bytes/13-9/lpbtascfadaxcywenbpljkhdcamtkgtpknghchchyketwsvwgwfdhpgmgtylctotzopdrpayoschcmhplffziachrfgd",
    "ur:bytes/14-9/lpbaascfadaxcywenbpljkhdcapazewnvonnvdnsbyleynwtnsjkjndeoldydkbkdslgjkbbkortbelomueekgvstegt",
    "ur:bytes/15-9/lpbsascfadaxcywenbpljkhdcaynmhpddpzmversbdqdfyrehnqzlugmjzmnmtwmrouohtstgsbsahpawkditkckynwt",
    "ur:bytes/16-9/lpbeascfadaxcywenbpljkhdcawygekobamwtlihsnpalnsghenskkiynthdzotsimtojetprsttmukirlrsbtamjtpd",
    "ur:bytes/17-9/lpbyascfadaxcywenbpljkhdcamklgftaxykpewyrtqzhydntpnytyisincxmhtbceaykolduortotiaiaiafhiaoyce",
    "ur:bytes/18-9/lpbgascfadaxcywenbpljkhdcahkadaemejtswhhylkepmykhhtsytsnoyoyaxaedsuttydmmhhpktpmsrjtntwkbkwy",
    "ur:bytes/19-9/lpbwascfadaxcywenbpljkhdcadekicpaajootjzpsdrbalpeywllbdsnbinaerkurspbncxgslgftvtsrjtksplcpeo",
    "ur:bytes/20-9/lpbbascfadaxcywenbpljkhdcayapmrleeleaxpasfrtrdkncffwjyjzgyetdmlewtkpktgllepfrltataztksmhkbot",
};

// Feeds parts; returns the 1-based index of the part that returned Complete (0 = never); every other part must be
// Accepted (and complete() false before the last).
static size_t feed(UrDecoder& d, const char* const* parts, size_t n, bool up = false) {
  for (size_t i = 0; i < n; i++) {
    std::string p = up ? upper(parts[i]) : std::string(parts[i]);
    UrDecoder::Result r = d.receive(p);
    if (r == UrDecoder::Complete) return i + 1;
    if (r != UrDecoder::Accepted) {
      std::printf("     part %u -> result %d (%s)\n", unsigned(i + 1), int(r), d.error().c_str());
      return 0;
    }
    if (d.complete()) return 0;
  }
  return 0;
}

static void test_ur_multipart_official() {
  CHECK_SECTION("ur multipart: official bc-ur parts, pure 1..9");
  const Bytes want = B(kWolf256Cbor, sizeof kWolf256Cbor);
  CHECK_EQ(crc32(want.data(), want.size()), kWolf256Crc);
  UrDecoder d;
  CHECK(d.progress() == 0.0f);
  for (size_t i = 0; i < 8; i++) {
    CHECK_EQ(d.receive(kOfficialParts[i]), UrDecoder::Accepted);
    CHECK_EQ(d.seq_len(), size_t(9));
    CHECK_EQ(d.received_pure(), i + 1);
    CHECK(std::fabs(d.progress() - float(i + 1) / 9.0f) < 1e-6f);
  }
  CHECK_EQ(d.receive(kOfficialParts[8]), UrDecoder::Complete);
  CHECK(d.complete() && d.type() == "bytes" && d.message() == want);
  CHECK(d.progress() == 1.0f);

  CHECK_SECTION("ur multipart: official parts 20..1 (mixed first)");
  d.reset();
  std::vector<const char*> rev(kOfficialParts, kOfficialParts + 20);
  std::reverse(rev.begin(), rev.end());
  // GF(2) rank of parts 20,19,... reaches 9 at the 16th part (tools/ref_ur.py gf2_complete_at)
  CHECK_EQ(feed(d, rev.data(), rev.size()), size_t(16));
  CHECK(d.message() == want);

  CHECK_SECTION("ur multipart: official mixed parts 10..20 only (rank 8 of 9: must not complete)");
  d.reset();
  CHECK_EQ(feed(d, kOfficialParts + 9, 11), size_t(0));
  CHECK(!d.complete());
  CHECK(std::fabs(d.progress() - 8.0f / 9.0f) < 1e-6f);
  // pure parts 1..4 add nothing new; part 5 (fragment 4) is the missing dimension
  for (size_t i = 0; i < 4; i++) CHECK_EQ(d.receive(kOfficialParts[i]), UrDecoder::Accepted);
  CHECK(std::fabs(d.progress() - 8.0f / 9.0f) < 1e-6f);
  CHECK_EQ(d.receive(kOfficialParts[4]), UrDecoder::Complete);
  CHECK(d.message() == want);

  CHECK_SECTION("ur multipart: BCR-2020-005 ur:seed 1-3 + generated parts");
  d.reset();
  CHECK_EQ(d.receive(kSeedParts[4]), UrDecoder::Accepted);  // 5-3 = {0,1,2}
  CHECK_EQ(d.received_pure(), size_t(0));
  CHECK(std::fabs(d.progress() - 1.0f / 3.0f) < 1e-6f);
  CHECK_EQ(d.receive(kSeedParts[3]), UrDecoder::Accepted);  // 4-3 = {0,2}  -> fragment 1 solved
  CHECK_EQ(d.received_pure(), size_t(1));
  CHECK(std::fabs(d.progress() - 2.0f / 3.0f) < 1e-6f);
  CHECK_EQ(d.receive(kSeedParts[5]), UrDecoder::Accepted);  // 6-3 = {1}: nothing new
  CHECK(std::fabs(d.progress() - 2.0f / 3.0f) < 1e-6f);
  CHECK_EQ(d.receive(kSeedParts[0]), UrDecoder::Complete);  // 1-3 = {0}: the spec's own part
  CHECK(d.message() == B(kSeedMsg, sizeof kSeedMsg));
}

static void test_ur_multipart_streams() {
  const Bytes want = B(kStreamMsg, sizeof kStreamMsg);
  UrDecoder d;

  CHECK_SECTION("ur multipart: python stream, mixed parts only");
  CHECK_EQ(feed(d, kStreamMixed, kStreamMixedCount), kStreamMixedCount);
  CHECK(d.message() == want && d.type() == "ripar-cosign-req");
  CborVal v;
  CHECK(cbor_decode(d.message(), v) && cbor_get(v, 2) && cbor_get(v, 2)->u == 10143);

  CHECK_SECTION("ur multipart: python stream, mixed parts only, upper case");
  d.reset();
  CHECK_EQ(feed(d, kStreamMixed, kStreamMixedCount, true), kStreamMixedCount);
  CHECK(d.message() == want);

  CHECK_SECTION("ur multipart: pure parts out of order with duplicates");
  d.reset();
  CHECK_EQ(feed(d, kStreamPureShuffled, kStreamPureShuffledCount), kStreamPureShuffledCount);
  CHECK(d.message() == want);

  CHECK_SECTION("ur multipart: 5 pure parts + later mixed parts");
  d.reset();
  CHECK_EQ(feed(d, kStreamCombo, kStreamComboCount), kStreamComboCount);
  CHECK(d.message() == want);

  CHECK_SECTION("ur multipart: every mixed part twice");
  d.reset();
  {
    size_t done = 0;
    for (size_t i = 0; i < kStreamMixedCount && !done; i++) {
      for (int rep2 = 0; rep2 < 2 && !done; rep2++) {
        UrDecoder::Result r = d.receive(kStreamMixed[i]);
        if (r == UrDecoder::Complete) done = i + 1;
        else CHECK_EQ(r, UrDecoder::Accepted);
      }
    }
    CHECK_EQ(done, kStreamMixedCount);
    CHECK(d.message() == want);
  }

  CHECK_SECTION("ur multipart: noise, other types and bad frames keep the progress");
  d.reset();
  {
    size_t done = 0;
    for (size_t i = 0; i < kStreamMixedCount && !done; i++) {
      const float before = d.progress();
      CHECK_EQ(d.receive("not a ur"), UrDecoder::Ignored);
      if (i > 0) CHECK_EQ(d.receive(kOfficialParts[0]), UrDecoder::Ignored);  // other type while in progress
      if (i > 0) CHECK_EQ(d.receive("ur:bytes/aeadaolazmjendeoti"), UrDecoder::Ignored);
      std::string bad = kStreamMixed[i];
      bad[bad.size() - 3] = bad[bad.size() - 3] == 'a' ? 'e' : 'a';  // corrupt one letter
      CHECK_EQ(d.receive(bad), UrDecoder::Error);
      CHECK(!d.error().empty());
      CHECK(d.progress() == before);
      UrDecoder::Result r = d.receive(kStreamMixed[i]);
      if (r == UrDecoder::Complete) done = i + 1;
      else CHECK_EQ(r, UrDecoder::Accepted);
    }
    CHECK_EQ(done, kStreamMixedCount);
    CHECK(d.message() == want);
  }

  CHECK_SECTION("ur multipart: a different message of the same type starts over");
  d.reset();
  CHECK_EQ(d.receive(kStreamMixed[0]), UrDecoder::Accepted);
  CHECK_EQ(d.receive(kStreamMixed[1]), UrDecoder::Accepted);
  CHECK_EQ(d.receive(kStreamPureShuffled[0]), UrDecoder::Accepted);
  CHECK_EQ(d.seq_len(), kStreamSeqLen);
  CHECK_EQ(feed(d, kStream2Pure, kStream2Count), kStream2Count);
  CHECK(d.message() == B(kStream2Msg, sizeof kStream2Msg));

  CHECK_SECTION("ur multipart: single-part UR of the same type completes");
  d.reset();
  CHECK_EQ(d.receive(kStreamMixed[0]), UrDecoder::Accepted);
  CHECK_EQ(d.receive(ur_encode("ripar-cosign-req", B(kSmallCbor, sizeof kSmallCbor))), UrDecoder::Complete);
  CHECK(d.message() == B(kSmallCbor, sizeof kSmallCbor));
}

// builds "ur:<type>/<n>-<len>/<bytewords of [seqNum, seqLen, msgLen, checksum, frag]>"
static std::string make_part(const char* type, uint64_t seq_num, uint64_t seq_len, uint64_t msg_len, uint64_t sum,
                             const Bytes& frag, const char* path = nullptr) {
  CborWriter w;
  w.array(5);
  w.uint(seq_num);
  w.uint(seq_len);
  w.uint(msg_len);
  w.uint(sum);
  w.bytes(frag);
  char buf[64];
  if (path)
    std::snprintf(buf, sizeof buf, "%s", path);
  else
    std::snprintf(buf, sizeof buf, "%lu-%lu", (unsigned long)seq_num, (unsigned long)seq_len);
  return std::string("ur:") + type + "/" + buf + "/" + bytewords_minimal_encode(w.out());
}

static void test_ur_multipart_crafted() {
  CHECK_SECTION("ur multipart: crafted parts (own encoder, pure + xor)");
  const Bytes msg = S("Ripar Wallet fountain test message!");  // 35 bytes -> 4 fragments of 9 (1 pad byte)
  const uint32_t sum = crc32(msg.data(), msg.size());
  std::vector<Bytes> fr(4);
  for (size_t i = 0; i < 4; i++) {
    fr[i].assign(9, 0);
    for (size_t k = 0; k < 9 && i * 9 + k < msg.size(); k++) fr[i][k] = msg[i * 9 + k];
  }
  UrDecoder d;
  CHECK_EQ(d.receive(make_part("t", 3, 4, 35, sum, fr[2])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 1, 4, 35, sum, fr[0])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 4, 4, 35, sum, fr[3])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 1, 4, 35, sum, fr[0])), UrDecoder::Accepted);  // duplicate
  CHECK_EQ(d.received_pure(), size_t(3));
  CHECK_EQ(d.receive(make_part("t", 2, 4, 35, sum, fr[1])), UrDecoder::Complete);
  CHECK(d.message() == msg);

  // mixed parts built from ur_choose_fragments (ties the decoder to the selection function)
  d.reset();
  size_t done = 0;
  for (uint32_t s = 5; s < 60 && !done; s++) {
    std::vector<size_t> idx = ur_choose_fragments(s, 4, sum);
    Bytes x(9, 0);
    for (size_t i : idx)
      for (size_t k = 0; k < 9; k++) x[k] ^= fr[i][k];
    UrDecoder::Result r = d.receive(make_part("t", s, 4, 35, sum, x));
    if (r == UrDecoder::Complete) done = s;
    else if (!CHECK_EQ(r, UrDecoder::Accepted)) break;
  }
  CHECK(done != 0);
  CHECK(d.message() == msg);

  CHECK_SECTION("ur multipart: single fragment message (1-1)");
  d.reset();
  CHECK_EQ(d.receive(make_part("t", 1, 1, 3, crc32(msg.data(), 3), Bytes(msg.begin(), msg.begin() + 3))),
           UrDecoder::Complete);
  CHECK(d.message() == Bytes(msg.begin(), msg.begin() + 3));

  CHECK_SECTION("ur multipart: message checksum mismatch");
  d.reset();
  CHECK_EQ(d.receive(make_part("t", 1, 4, 35, sum ^ 1, fr[0])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 2, 4, 35, sum ^ 1, fr[1])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 3, 4, 35, sum ^ 1, fr[2])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 4, 4, 35, sum ^ 1, fr[3])), UrDecoder::Error);
  CHECK(!d.complete() && d.seq_len() == 0u && !d.error().empty());
  // afterwards a good stream decodes
  for (size_t i = 0; i < 3; i++) CHECK_EQ(d.receive(make_part("t", i + 1, 4, 35, sum, fr[i])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 4, 4, 35, sum, fr[3])), UrDecoder::Complete);
  CHECK(d.message() == msg);

  CHECK_SECTION("ur multipart: malformed parts -> Error, progress kept");
  d.reset();
  CHECK_EQ(d.receive(make_part("t", 1, 4, 35, sum, fr[0])), UrDecoder::Accepted);
  const Bytes f9(9, 7);
  struct Bad {
    std::string part;
    const char* why;
  } bads[] = {
      {make_part("t", 2, 4, 35, sum, fr[1], "3-4"), "path seqNum differs from CBOR"},
      {make_part("t", 2, 4, 35, sum, fr[1], "2-5"), "path seqLen differs from CBOR"},
      {make_part("t", 2, 4, 35, sum, fr[1], "0-4"), "path seqNum 0"},
      {make_part("t", 2, 4, 35, sum, fr[1], "2-0"), "path seqLen 0"},
      {make_part("t", 2, 4, 35, sum, fr[1], "2"), "path without dash"},
      {make_part("t", 2, 4, 35, sum, fr[1], "-4"), "path empty seqNum"},
      {make_part("t", 2, 4, 35, sum, fr[1], "2-"), "path empty seqLen"},
      {make_part("t", 2, 4, 35, sum, fr[1], "x-4"), "path not decimal"},
      {make_part("t", 2, 4, 35, sum, fr[1], "2-4-1"), "path two dashes"},
      {make_part("t", 2, 4, 35, sum, fr[1], "99999999999-4"), "path seqNum overflow"},
      {make_part("t", 0, 4, 35, sum, fr[1], "0-4"), "seqNum 0"},
      {make_part("t", 2, 5, 35, sum, fr[1]), "seqLen inconsistent with msgLen/fragLen"},
      {make_part("t", 2, 4, 0, sum, fr[1]), "msgLen 0"},
      {make_part("t", 2, 4, 35, sum, Bytes()), "empty fragment"},
      {make_part("t", 2, 200, 1800, sum, f9), "seqLen above limit"},
      {make_part("t", 2, 2, 9000, sum, Bytes(4500, 1)), "message above limit"},
      {make_part("t", 0x100000000ull, 4, 35, sum, fr[1], "4294967295-4"), "seqNum > 32 bit"},
      {make_part("t", 2, 4, 35, 0x100000000ull, fr[1]), "checksum > 32 bit"},
      {"ur:t/2-4/" + bytewords_minimal_encode(H("8402041823f6")), "array of 4"},
      {"ur:t/2-4/" + bytewords_minimal_encode(H("85020418230169000000000000000000")), "fragment is text"},
      {"ur:t/2-4/" + bytewords_minimal_encode(H("8502041823f64900000000000000000000")), "checksum not uint"},
      {"ur:t/2-4/" + bytewords_minimal_encode(H("a0")), "not an array"},
      {"ur:t/2-4/" + bytewords_minimal_encode(H("9f02041823f6ff")), "indefinite array"},
      {"ur:t/2-4/aeadaolazmjendeota", "bad bytewords CRC"},
      {"ur:t/2-4/", "empty body"},
      {"ur:t/2-4/x/y", "too many components"},
  };
  size_t nbad = sizeof bads / sizeof bads[0];
  for (size_t i = 0; i < nbad; i++) {
    const float before = d.progress();
    UrDecoder::Result r = d.receive(bads[i].part);
    if (!CHECK_EQ(r, UrDecoder::Error)) std::printf("     case: %s\n", bads[i].why);
    if (!CHECK(d.progress() == before && d.seq_len() == 4u)) std::printf("     case: %s\n", bads[i].why);
  }
  for (size_t i = 1; i < 3; i++) CHECK_EQ(d.receive(make_part("t", i + 1, 4, 35, sum, fr[i])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 4, 4, 35, sum, fr[3])), UrDecoder::Complete);
  CHECK(d.message() == msg);

  CHECK_SECTION("ur multipart: consistent part of another message restarts");
  d.reset();
  CHECK_EQ(d.receive(make_part("t", 1, 4, 35, sum, fr[0])), UrDecoder::Accepted);
  CHECK_EQ(d.receive(make_part("t", 2, 4, 36, sum, fr[1])), UrDecoder::Accepted);  // msgLen differs
  CHECK_EQ(d.received_pure(), size_t(1));
  CHECK_EQ(d.receive(make_part("t", 2, 4, 35, sum ^ 2, fr[1])), UrDecoder::Accepted);  // checksum differs
  CHECK_EQ(d.received_pure(), size_t(1));
  CHECK_EQ(d.receive(make_part("t", 2, 3, 27, sum, fr[1])), UrDecoder::Accepted);  // seqLen differs
  CHECK_EQ(d.seq_len(), size_t(3));
  CHECK_EQ(d.receive(make_part("t", 2, 4, 35, sum, Bytes(fr[1].begin(), fr[1].begin() + 8), "2-5")),
           UrDecoder::Error);  // 35/8 -> 5 fragments, path says 5 but CBOR says 4

  CHECK_SECTION("ur multipart: limits accepted at the edge");
  d.reset();
  {
    // 128 fragments of 64 bytes = 8192-byte message: pure parts in reverse order
    Bytes big(8192);
    for (size_t i = 0; i < big.size(); i++) big[i] = uint8_t(i * 13 + 5);
    const uint32_t bs = crc32(big.data(), big.size());
    UrDecoder::Result r = UrDecoder::Accepted;
    for (size_t k = 128; k >= 1 && r == UrDecoder::Accepted; k--)
      r = d.receive(make_part("big", k, 128, 8192, bs, Bytes(big.begin() + std::ptrdiff_t((k - 1) * 64),
                                                             big.begin() + std::ptrdiff_t(k * 64))));
    CHECK_EQ(r, UrDecoder::Complete);
    CHECK(d.message() == big);
  }
}

int main() {
  test_cbor_writer();
  test_cbor_decoder_values();
  test_cbor_decoder_malformed();
  test_cbor_roundtrip();
  test_bytewords();
  test_ur_single();
  test_choose_fragments();
  test_ur_multipart_official();
  test_ur_multipart_streams();
  test_ur_multipart_crafted();
  return CHECK_SUMMARY();
}
