// Byte-for-byte conformance with contracts/test/vectors/device_vectors.json (generated by
// contracts/test/vectors/gen_device_vectors.py through make_request.py's demo device): every request is rebuilt here
// from the generator's inputs, every response is parsed and verified, every digest / hash / terms / args compared.
import { createHash } from 'node:crypto';
import { hashTypedData } from 'viem';
import { describe, expect, it } from 'vitest';
import {
  type BuiltRequest,
  type CaveatSpec,
  ERC20_KIND_NUM,
  ROOT_AUTHORITY,
  TYPE_STRINGS,
  buildRequest,
  caveatDump,
  cosignRequestHash,
  decodeErc20,
  decodePulseTerms,
  decodeRequest,
  delegationHash,
  domainSeparator,
  expectVerified,
  humanApprovalHash,
  keccak256,
  keyIdOf,
  parseResponse,
  presenceHash,
  toChecksumAddress,
  toHex,
  typeHash,
  typedDataBindDevice,
  typedDataDelegation,
  typedDataDeny,
  typedDataHumanApproval,
  typedDataPanic,
  typedDataReopen,
  typedDataRevoke,
  urRead,
  urSingle,
  utf8,
} from '../src/index.js';
import {
  demoEvidence,
  panicResponse,
  reopenResponse,
  revokeResponse,
  simulate,
  simulateDenyFromCosign,
} from './helpers/demo-device.js';
import { VECTORS_PATH, bytesToHex, hexToBytes, readJson } from './helpers/env.js';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const V: any = readJson(VECTORS_PATH);
const A = V.addresses;
const CHAIN = V.chainId as number;
const NOW = V.now as number;
const EXPIRY = NOW + 3600;
const AGENT_ID = 17;
const SALT = 20260927;
const LABEL = 'Ripar conformance agent';

/** gen_device_vectors.fixed(label, n) */
const fixed = (label: string, n: number): Uint8Array =>
  Uint8Array.from(createHash('sha256').update('ripar conformance ' + label).digest().subarray(0, n));

const lc = (s: string): string => s.toLowerCase();

function checkRequest(built: BuiltRequest, doc: { request: { cbor: string; ur: string }; requestParts: number }): void {
  expect(bytesToHex(built.cbor)).toBe(doc.request.cbor);
  expect(built.ur).toBe(doc.request.ur);
  expect(built.parts.length).toBe(doc.requestParts);
  // the multipart loop reassembles, the single part reads back
  expect(bytesToHex(urRead(built.parts.join('\n')).cbor)).toBe(doc.request.cbor);
  expect(bytesToHex(urRead(built.ur).cbor)).toBe(doc.request.cbor);
}

const pairF = {
  reqId: fixed('pair req-id', 16),
  chainId: CHAIN,
  registry: A.registry,
  manager: A.delegationManager,
  enforcer: A.enforcer,
  sentinel: A.sentinel,
  relay: A.relay,
  vault: A.vault,
  now: NOW,
};

function mandateFields(name: string, epoch: number, salt: number, label: string, extra: CaveatSpec[] = []) {
  const pulse: CaveatSpec = {
    kind: 'pulse',
    enforcer: A.enforcer,
    p1Key: V.demo.px + V.demo.py.slice(2),
    token: A.token,
    perTxAutoCap: 25_000_000,
    periodAutoCap: 100_000_000,
    period: 86400,
    epoch,
    newPayeeNeedsHuman: true,
    sentinel: A.sentinel,
  };
  return {
    reqId: fixed(name + ' req-id', 16),
    chainId: CHAIN,
    manager: A.delegationManager,
    delegate: A.agent,
    delegator: A.vault,
    caveats: [...extra, pulse],
    salt,
    label,
    agentId: AGENT_ID,
  };
}

describe('device_vectors.json: domains and type hashes', () => {
  it('type hashes', () => {
    for (const [name, h] of Object.entries(V.typeHashes)) {
      expect(toHex(typeHash(name as keyof typeof TYPE_STRINGS))).toBe(h);
    }
  });
  it('domain separators', () => {
    for (const [which, d] of Object.entries<{ name: string; separator: string }>(V.domains)) {
      expect(toHex(domainSeparator(d.name, CHAIN, A[which]))).toBe(d.separator);
    }
  });
  it('demo key id = keccak256(abi.encode(px, py))', () => {
    expect(toHex(keyIdOf(V.demo.px + V.demo.py.slice(2)))).toBe(V.demo.keyId);
  });
});

describe('device_vectors.json: pair', () => {
  const doc = V.pair;
  const built = buildRequest('pair', pairF);
  it('request CBOR / UR / parts', () => checkRequest(built, doc));
  it('the demo device answers byte-identically', () => {
    expect(bytesToHex(simulate('pair', built.cbor))).toBe(doc.response.cbor);
    expect(urSingle('ripar-pair', hexToBytes(doc.response.cbor))).toBe(doc.response.ur);
  });
  it('response parses and verifies', () => {
    const rep = expectVerified(parseResponse(doc.response.ur, { request: built }));
    if (rep.type !== 'ripar-pair') throw new Error('type');
    expect(rep.fields.k1Address).toBe(doc.owner);
    expect(rep.fields.px).toBe(doc.px);
    expect(rep.fields.py).toBe(doc.py);
    expect(rep.fields.keyId).toBe(doc.keyId);
    expect(rep.fields.bindDigest).toBe(doc.digest);
    expect(rep.fields.p1Signature).toBe(doc.r + doc.s.slice(2));
    expect(rep.fields.k1Signature).toBe(doc.k1Signature);
    expect(rep.fields.firmwareId).toBe(doc.firmwareId);
    expect(rep.fields.emulator).toBe(false);
    expect(rep.checks.map((c) => c.name)).toEqual([
      'req-id echoed',
      'BindDevice P1 low-s',
      'BindDevice P1 P-256 signature',
      'BindDevice K1 v is 27/28',
      'BindDevice K1 low-s',
      'BindDevice K1 recoverable',
      'BindDevice K1 recovers the K1 address',
      'P1 key on curve',
    ]);
    expect(hashTypedData(typedDataBindDevice(CHAIN, A.registry, doc.owner, doc.px + doc.py.slice(2)) as never)).toBe(doc.digest);
  });
});

describe('device_vectors.json: mandate', () => {
  for (const [label, doc, fields] of [
    ['mandate', V.mandate, mandateFields('mandate', 0, SALT, LABEL)],
    [
      'repair mandate',
      V.repair.mandate,
      mandateFields('repair mandate', 1, SALT + 1, LABEL + ' (re-paired)', [
        { kind: 'timestamp', after: 0, before: V.repair.timestamp.before },
      ]),
    ],
  ] as const) {
    describe(label, () => {
      const built = buildRequest('mandate', fields);
      it('request CBOR / UR / parts', () => checkRequest(built, doc));
      it('caveats, terms and the device decode', () => {
        const q = decodeRequest('mandate', built.cbor);
        if (q.kind !== 'mandate') throw new Error('kind');
        expect(toHex(q.authority)).toBe(toHex(ROOT_AUTHORITY));
        expect(q.caveats.length).toBe(doc.caveatCount);
        q.caveats.forEach((c, i) => {
          expect(toChecksumAddress(c.enforcer)).toBe(doc.caveats[i].enforcer);
          expect(toHex(c.terms)).toBe(doc.caveats[i].terms);
        });
        const pulse = q.caveats[doc.pulseIndex]!;
        expect(toHex(pulse.terms)).toBe(doc.terms.hex);
        const t = decodePulseTerms(pulse.terms);
        expect(t.px).toBe(doc.terms.px);
        expect(t.py).toBe(doc.terms.py);
        expect(t.token).toBe(doc.terms.token);
        expect(t.perTxAutoCap).toBe(BigInt(doc.terms.perTxAutoCap));
        expect(t.periodAutoCap).toBe(BigInt(doc.terms.periodAutoCap));
        expect(t.period).toBe(BigInt(doc.terms.period));
        expect(t.epoch).toBe(BigInt(doc.terms.epoch));
        expect(t.newPayeeNeedsHuman).toBe(doc.terms.newPayeeNeedsHuman);
        expect(lc(t.sentinel)).toBe(lc(doc.terms.sentinel));
        const dumps = q.caveats.map((c) => caveatDump(CHAIN, c.enforcer, c.terms, CHAIN, A.enforcer));
        expect(doc.pulseIndex === 0 ? dumps[0] : dumps).toEqual(doc.deviceDecode);
        expect(toHex(delegationHash(q))).toBe(doc.delegationHash);
      });
      it('the demo device answers byte-identically', () => {
        expect(bytesToHex(simulate('mandate', built.cbor))).toBe(doc.response.cbor);
      });
      it('eth-signature parses and verifies against the paired K1', () => {
        const rep = expectVerified(parseResponse(doc.response.ur, { request: built, pairing: V.pair.response.ur }));
        if (rep.type !== 'eth-signature') throw new Error('type');
        expect(rep.fields.delegationHash).toBe(doc.delegationHash);
        expect(rep.fields.digest).toBe(doc.digest);
        expect(rep.fields.rsv).toBe(doc.signature);
        expect(rep.fields.signer).toBe(V.demo.k1);
        expect(rep.checks.map((c) => c.name)).toEqual([
          'req-id echoed',
          'mandate K1 v is 27/28',
          'mandate K1 low-s',
          'mandate K1 recoverable',
          'mandate signed by the paired K1',
        ]);
        const q = decodeRequest('mandate', built.cbor);
        if (q.kind !== 'mandate') throw new Error('kind');
        expect(hashTypedData(typedDataDelegation(CHAIN, A.delegationManager, q) as never)).toBe(doc.digest);
      });
    });
  }
});

const COSIGNS = [
  {
    key: 'cosignErc20',
    name: 'cosign erc20',
    nonce: 1,
    salt: 'salt cosign erc20',
    fields: {
      target: A.token,
      value: 0,
      transfer: { to: A.payee, amount: 40_000_000 },
      ai: {
        text: 'Pay invoice #2026-0927 (40 mUSD) to the usual design studio',
        claims: { to: A.payee, token: A.token, amount: 40_000_000 },
      },
      budgetLeft: 100_000_000,
      decimals: 6,
      symbol: 'mUSD',
    },
  },
  {
    key: 'cosignNative',
    name: 'cosign native',
    nonce: 2,
    salt: 'salt cosign native',
    fields: {
      target: A.payee,
      value: 500_000_000_000_000_000n,
      ai: {
        text: 'Send 0.5 MON to the design studio',
        claims: { to: A.payee, token: new Uint8Array(20), amount: 500_000_000_000_000_000n },
      },
      decimals: 18,
      symbol: 'MON',
    },
  },
  {
    key: 'cosignApprove',
    name: 'cosign approve',
    nonce: 3,
    salt: 'salt cosign approve',
    fields: { target: A.token, value: 0, approve: { spender: A.spender, amount: 30_000_000 }, decimals: 6, symbol: 'mUSD' },
  },
  {
    key: 'cosignTransferFrom',
    name: 'cosign transferFrom',
    nonce: 4,
    salt: 'salt cosign transferFrom',
    fields: {
      target: A.token,
      value: 0,
      transferFrom: { from: A.holder, to: A.payee2, amount: 15_000_000 },
      decimals: 6,
      symbol: 'mUSD',
    },
  },
] as const;

function cosignBuilt(c: (typeof COSIGNS)[number]): BuiltRequest {
  return buildRequest('cosign', {
    reqId: fixed(c.name + ' req-id', 16),
    chainId: CHAIN,
    enforcer: A.enforcer,
    delegationHash: V.mandate.delegationHash,
    delegator: A.vault,
    redeemer: A.agent,
    nonce: c.nonce,
    expiry: EXPIRY,
    ...c.fields,
  });
}

describe('device_vectors.json: co-signs', () => {
  for (const c of COSIGNS) {
    describe(c.key, () => {
      const doc = V[c.key];
      const built = cosignBuilt(c);
      const salt16 = fixed(c.salt, 16);
      it('request CBOR / UR / parts', () => checkRequest(built, doc));
      it('request fields, ERC-20 decode, hashes', () => {
        const q = decodeRequest('cosign', built.cbor);
        if (q.kind !== 'cosign') throw new Error('kind');
        expect(toHex(q.calldata)).toBe(doc.calldata);
        expect(toHex(keccak256(q.calldata))).toBe(doc.callDataHash);
        expect(q.value).toBe(BigInt(doc.value));
        const d = decodeErc20(q.calldata);
        if (d.kind === 'none') {
          expect(lc(toChecksumAddress(q.target))).toBe(lc(doc.payee));
        } else {
          expect(lc(toChecksumAddress(d.to))).toBe(lc(doc.payee));
          expect(d.amount).toBe(BigInt(doc.amount));
        }
        if (doc.kind) expect(d.kind).toBe(doc.kind);
        if (doc.from) expect(lc(toChecksumAddress(d.from))).toBe(lc(doc.from));
        expect(toHex(cosignRequestHash(q))).toBe(doc.requestHash);
        const ph = presenceHash(doc.evidence12, doc.salt16);
        expect(toHex(ph)).toBe(doc.presenceHash);
        expect(
          toHex(
            humanApprovalHash({
              delegationHash: q.delegationHash,
              delegator: q.delegator,
              redeemer: q.redeemer,
              target: q.target,
              value: q.value,
              callDataHash: keccak256(q.calldata),
              nonce: q.nonce,
              expiry: q.expiry,
              presenceHash: ph,
            }),
          ),
        ).toBe(doc.structHash);
        expect(hashTypedData(typedDataHumanApproval(q, ph) as never)).toBe(doc.digest);
      });
      it('the demo device answers byte-identically', () => {
        expect(bytesToHex(salt16)).toBe(doc.salt16);
        expect(bytesToHex(demoEvidence())).toBe(doc.evidence12);
        expect(bytesToHex(simulate('cosign', built.cbor, { ev12: demoEvidence(), salt16 }))).toBe(doc.response.cbor);
      });
      it('ripar-cosign parses and verifies; caveat args', () => {
        const rep = expectVerified(parseResponse(doc.response.ur, { request: built, p1Key: V.demo.px + V.demo.py.slice(2) }));
        if (rep.type !== 'ripar-cosign') throw new Error('type');
        expect(rep.fields.digest).toBe(doc.digest);
        expect(rep.fields.presenceHash).toBe(doc.presenceHash);
        expect(rep.fields.r).toBe(doc.r);
        expect(rep.fields.s).toBe(doc.s);
        expect(rep.fields.caveatArgs).toBe(doc.args);
        expect(rep.fields.evidence).toEqual({
          version: doc.evidence.version,
          bpm: doc.evidence.bpm,
          beats: doc.evidence.beats,
          irDC: doc.evidence.irDC,
          redDC: doc.evidence.redDC,
          jitterX1000: doc.evidence.jitter_x1000,
          durationMs: doc.evidence.duration_ms,
        });
        expect(rep.checks.map((x) => x.name)).toEqual(['req-id echoed', 'cosign low-s', 'cosign P-256 signature']);
      });
    });
  }
  it('key 15 / 16 claims of an unlisted token are kept as sent', () => {
    const q = decodeRequest('cosign', cosignBuilt(COSIGNS[0]).cbor);
    if (q.kind !== 'cosign') throw new Error('kind');
    expect(q.decimals).toBe(BigInt(V.cosignErc20.tokenDecimalsClaim));
    expect(q.symbol).toBe(V.cosignErc20.tokenSymbolClaim);
  });
});

describe('device_vectors.json: deny', () => {
  it('deny built by the device from the ERC-20 co-sign review', () => {
    const doc = V.deny;
    const cos = cosignBuilt(COSIGNS[0]);
    const resp = simulateDenyFromCosign(cos.cbor, BigInt(CHAIN), hexToBytes(A.relay), BigInt(AGENT_ID), fixed('salt deny', 16));
    expect(bytesToHex(resp)).toBe(doc.response.cbor);
    const rep = expectVerified(
      parseResponse(doc.response.ur, { request: cos, contract: A.relay, p1Key: V.demo.px + V.demo.py.slice(2) }),
    );
    if (rep.type !== 'ripar-deny') throw new Error('type');
    expect(rep.fields.reqId).toBe(doc.reqId);
    expect(rep.fields.requestHash).toBe(doc.requestHash);
    expect(rep.fields.presenceHash).toBe(doc.presenceHash);
    expect(rep.fields.digest).toBe(doc.digest);
    expect(rep.fields.agentId).toBe(BigInt(AGENT_ID));
    expect(rep.fields.evidence12).toBe(doc.evidence12);
    expect(rep.checks.map((c) => c.name)).toEqual([
      'req-id echoed',
      'requestHash = hashStruct(HumanApproval) of the co-sign request',
      'deny low-s',
      'deny P-256 signature',
    ]);
    expect(hashTypedData(typedDataDeny(CHAIN, A.relay, AGENT_ID, doc.requestHash, doc.presenceHash) as never)).toBe(doc.digest);
  });
  it('ripar-deny-req from the companion', () => {
    const doc = V.denyRequest;
    const built = buildRequest('deny', {
      reqId: fixed('deny request req-id', 16),
      chainId: CHAIN,
      relay: A.relay,
      agentId: AGENT_ID,
      requestHash: V.cosignNative.requestHash,
    });
    checkRequest(built, doc);
    expect(bytesToHex(simulate('deny', built.cbor, { ev12: new Uint8Array(12), salt16: fixed('salt deny request', 16) }))).toBe(
      doc.response.cbor,
    );
    const rep = expectVerified(parseResponse(doc.response.ur, { request: built, pairing: V.pair.response.ur }));
    if (rep.type !== 'ripar-deny') throw new Error('type');
    expect(rep.fields.digest).toBe(doc.digest);
    expect(rep.fields.presenceHash).toBe(doc.presenceHash);
    expect(rep.fields.requestHash).toBe(doc.requestHash);
    expect(rep.checks.map((c) => c.name)).toEqual([
      'req-id echoed',
      'agentId echoed',
      'requestHash echoed',
      'deny low-s',
      'deny P-256 signature',
    ]);
  });
});

describe('device_vectors.json: revoke / panic / reopen', () => {
  const p1Key = V.demo.px + V.demo.py.slice(2);
  const cases = [
    ['revoke', V.revoke],
    ['panic', V.panic],
    ['reopen', V.reopen],
    ['repair panic', V.repair.panic],
    ['repair reopen', V.repair.reopen],
  ] as const;
  for (const [name, doc] of cases) {
    it(name, () => {
      const isReopen = name.endsWith('reopen');
      const contract = isReopen ? A.sentinel : A.enforcer;
      const rep = expectVerified(parseResponse(doc.response.ur, { chainId: CHAIN, contract, p1Key }));
      expect((rep.fields as { digest?: string }).digest).toBe(doc.digest);
      expect(rep.checks.map((c) => c.name)).toEqual([`${rep.type} low-s`, `${rep.type} P-256 signature`]);
      let resp: Uint8Array;
      if (rep.type === 'ripar-revoke') {
        expect(rep.fields.delegationHash).toBe(doc.delegationHash);
        resp = revokeResponse(BigInt(CHAIN), hexToBytes(contract), hexToBytes(doc.delegationHash));
        expect(hashTypedData(typedDataRevoke(CHAIN, contract, doc.delegationHash) as never)).toBe(doc.digest);
      } else if (rep.type === 'ripar-panic') {
        expect(rep.fields.minEpoch).toBe(BigInt(doc.minEpoch));
        resp = panicResponse(BigInt(CHAIN), hexToBytes(contract), BigInt(doc.minEpoch));
        expect(hashTypedData(typedDataPanic(CHAIN, contract, doc.minEpoch) as never)).toBe(doc.digest);
      } else if (rep.type === 'ripar-reopen') {
        expect(rep.fields.vault).toBe(doc.vault);
        expect(rep.fields.nonce).toBe(BigInt(doc.nonce));
        resp = reopenResponse(BigInt(CHAIN), hexToBytes(contract), hexToBytes(doc.vault), BigInt(doc.nonce));
        expect(hashTypedData(typedDataReopen(CHAIN, contract, doc.vault, doc.nonce) as never)).toBe(doc.digest);
      } else throw new Error('type');
      expect(bytesToHex(resp)).toBe(doc.response.cbor);
      expect(urSingle(rep.type, resp)).toBe(doc.response.ur);
    });
  }
});

describe('device_vectors.json: re-pair with the on-chain floors', () => {
  it('request with keys 10 / 11, same BindDevice signatures', () => {
    const doc = V.repair.pair;
    const built = buildRequest('pair', {
      ...pairF,
      reqId: fixed('repair req-id', 16),
      now: doc.now,
      minEpoch: doc.minEpochFloor,
      reopenNonce: doc.reopenNonceFloor,
    });
    checkRequest(built, doc);
    expect(bytesToHex(simulate('pair', built.cbor))).toBe(doc.response.cbor);
    const rep = expectVerified(parseResponse(doc.response.ur, { request: built }));
    if (rep.type !== 'ripar-pair') throw new Error('type');
    expect(rep.fields.bindDigest).toBe(doc.digest);
    expect(rep.fields.k1Signature).toBe(doc.k1Signature);
  });
});

describe('device_vectors.json: firmware ERC-20 decode table', () => {
  it(`all ${V.erc20Decode.count} entries`, () => {
    expect(V.erc20Decode.kinds).toEqual(ERC20_KIND_NUM);
    for (const v of V.erc20Decode.vectors) {
      const d = decodeErc20(v.calldata);
      expect(ERC20_KIND_NUM[d.kind], v.note).toBe(v.kind);
      expect(toChecksumAddress(d.from), v.note).toBe(v.from);
      expect(toChecksumAddress(d.to), v.note).toBe(v.to);
      expect(d.amount, v.note).toBe(BigInt(v.amount));
    }
  });
});

describe('ripar-emulator firmware id', () => {
  it('= sha256("ripar-emulator v1")[:8] (the emulator README)', () => {
    const want = '0x' + createHash('sha256').update('ripar-emulator v1').digest('hex').slice(0, 16);
    expect(want).toBe('0x7bc44601d30720f1');
    expect(toHex(keccak256(utf8.encode('')))).toBe('0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');
  });
});
