// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import { RiparDeviceRegistry } from "../src/RiparDeviceRegistry.sol";
import { IRiparDeviceRegistry } from "../src/interfaces/IRiparDeviceRegistry.sol";
import { PeripheryTestBase } from "./utils/periphery/PeripheryTestBase.sol";

abstract contract RiparDeviceRegistryTestBase is PeripheryTestBase {
    event DeviceRegistered(address indexed owner, bytes32 indexed keyId, bytes32 px, bytes32 py);

    uint256 internal constant P1 = 0xA11CE; // device P-256 key
    uint256 internal constant K1 = 0xB0B; // device secp256k1 key (the vault owner)
    uint256 internal constant P1_B = 0xB1B1; // a second device
    uint256 internal constant K1_B = 0xB2B2;
    uint256 internal constant P1_C = 0xC1C1; // a third P-256 key

    RiparDeviceRegistry internal reg;
    address internal owner;
    bytes32 internal px;
    bytes32 internal py;
    bytes32 internal keyId;
    bytes32 internal pr; // genuine P1 signature over bindDigest(owner, px, py)
    bytes32 internal ps;

    function setUp() public virtual {
        reg = new RiparDeviceRegistry();
        owner = vm.addr(K1);
        (px, py) = p256Key(P1);
        keyId = p256KeyId(px, py);
        (pr, ps) = _p1Sig(P1, owner, px, py);
    }

    // ------------------------------------------------------------------ helpers

    function _p1Sig(uint256 pk, address o, bytes32 x, bytes32 y) internal view returns (bytes32 r, bytes32 s) {
        return p256Sign(pk, reg.bindDigest(o, x, y));
    }

    function _k1Sig(uint256 pk, address o, bytes32 x, bytes32 y) internal view returns (bytes memory) {
        return k1Sign(pk, reg.bindDigest(o, x, y));
    }

    function _assertUnbound(bytes32 id) internal view {
        (bytes32 x, bytes32 y, address o) = reg.keyOf(id);
        assertEq(o, address(0), "owner");
        assertEq(x, bytes32(0), "px");
        assertEq(y, bytes32(0), "py");
    }

    function _assertBound(address o, bytes32 x, bytes32 y) internal view {
        bytes32 id = p256KeyId(x, y);
        assertEq(reg.keyIdOf(o), id, "keyIdOf");
        (bytes32 kx, bytes32 ky, address ko) = reg.keyOf(id);
        assertEq(kx, x, "keyOf.px");
        assertEq(ky, y, "keyOf.py");
        assertEq(ko, o, "keyOf.owner");
    }

    // ------------------------------------------------------------------ EIP-712

    function test_domainSeparator_matchesHandRolled() public view {
        assertEq(reg.domainSeparator(), handDomain("RiparDeviceRegistry", block.chainid, address(reg)));
        (, string memory name, string memory version, uint256 chainId, address verifying,,) = reg.eip712Domain();
        assertEq(name, "RiparDeviceRegistry");
        assertEq(version, "1");
        assertEq(chainId, block.chainid);
        assertEq(verifying, address(reg));
    }

    function test_typehash() public view {
        assertEq(reg.BIND_DEVICE_TYPEHASH(), keccak256("BindDevice(address owner,bytes32 px,bytes32 py)"));
    }

    function test_bindDigest_matchesHandRolled() public view {
        bytes32 structHash =
            keccak256(abi.encode(keccak256("BindDevice(address owner,bytes32 px,bytes32 py)"), owner, px, py));
        bytes32 expected = keccak256(
            abi.encodePacked(hex"1901", handDomain("RiparDeviceRegistry", block.chainid, address(reg)), structHash)
        );
        assertEq(reg.bindDigest(owner, px, py), expected);
    }

    function testFuzz_bindDigest_matchesHandRolled(address o, bytes32 x, bytes32 y, uint256 chainId) public {
        chainId = bound(chainId, 0, type(uint64).max / 2); // the largest chain id Foundry accepts
        vm.chainId(chainId);
        bytes32 structHash = keccak256(abi.encode(reg.BIND_DEVICE_TYPEHASH(), o, x, y));
        assertEq(
            reg.bindDigest(o, x, y), handDigest(handDomain("RiparDeviceRegistry", chainId, address(reg)), structHash)
        );
    }

    /// @dev Vectors from firmware/test/host/vectors_eip712_abi.h (generated by the Python reference encoder).
    function test_firmwareVectors() public {
        // DOMAINS[4]: RiparDeviceRegistry v1, chainId 143
        address at = hexAddr(hex"c0f3fce6519abb6e44a02ca4f7c805c1c7015879");
        vm.etch(at, address(reg).code);
        vm.chainId(143);
        assertEq(
            RiparDeviceRegistry(at).domainSeparator(),
            hex"4ed74ec6055675ae29765fdf6d928fb1e6b7c181428c3df52b0a7179a6dc0e8c"
        );
        // BIND_DEVICES[4]: chainId 31337
        at = hexAddr(hex"526ba649fec3c5433385b838582f5d1aebfadb2b");
        vm.etch(at, address(reg).code);
        vm.chainId(31337);
        address o = hexAddr(hex"ff3496d2817e763c84c85fbfbd54f35d01032aa0");
        bytes32 x = hex"25d5f9824035e022be75c55fa3f1c33a2bb1f686f8ea15c3b51a73e7eef77857";
        bytes32 y = hex"f7f225fea9f3439e9d3985df8019e0b9e633125bf41d02baa8ee08eb3ce8404a";
        assertEq(
            keccak256(abi.encode(reg.BIND_DEVICE_TYPEHASH(), o, x, y)),
            hex"f003080af2b175cd5d203185543892e20e80c341533b7504909ccd1e99bfa10b",
            "structHash"
        );
        assertEq(
            RiparDeviceRegistry(at).bindDigest(o, x, y),
            hex"204e17640fe72d9bc19aa62f2052af0557960906197f50a302a152619a240046",
            "digest"
        );
        // BIND_DEVICES[1]: chainId 0, owner 0, registry 0xff..ff
        at = hexAddr(hex"ffffffffffffffffffffffffffffffffffffffff");
        vm.etch(at, address(reg).code);
        vm.chainId(0);
        assertEq(
            RiparDeviceRegistry(at)
                .bindDigest(
                    address(0),
                    hex"31f7819c3819b0c3b5ab33021a440db4de4837cc7cb7d00fbf61b19580438542",
                    hex"d56dbfa932643e8f8e300e7c6af002592fa156882c19365845b1fdf33a898607"
                ),
            hex"3fe76f5d93557644a3ec1772654c3853d34a1020d47f1aac0e1c86e74ee87488"
        );
    }

    // ------------------------------------------------------------------ happy path

    function test_register_happyPath() public {
        assertEq(reg.keyIdOf(owner), bytes32(0));
        _assertUnbound(keyId);

        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        bytes memory sig = _k1Sig(K1, owner, px, py);
        assertEq(sig.length, 65);

        vm.expectEmit(true, true, false, true, address(reg));
        emit DeviceRegistered(owner, keyId, px, py);
        vm.prank(makeAddr("relayer")); // anyone may relay
        bytes32 got = reg.registerDevice(owner, px, py, r, s, sig);

        assertEq(got, keyId);
        assertEq(got, keccak256(abi.encode(px, py)));
        _assertBound(owner, px, py);
    }

    function test_register_sameStateWhetherRelayedOrSelf() public {
        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        vm.prank(owner);
        reg.registerDevice(owner, px, py, r, s, _k1Sig(K1, owner, px, py));
        _assertBound(owner, px, py);
    }

    function test_register_samePairTwice_isNoOpAndEmits() public {
        registerPair(reg, P1, K1);
        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        bytes memory sig = _k1Sig(K1, owner, px, py);

        vm.expectEmit(true, true, false, true, address(reg));
        emit DeviceRegistered(owner, keyId, px, py);
        assertEq(reg.registerDevice(owner, px, py, r, s, sig), keyId);
        _assertBound(owner, px, py);

        // the exact same calldata a third time (replaying the pairing QR) is still fine
        assertEq(reg.registerDevice(owner, px, py, r, s, sig), keyId);
        _assertBound(owner, px, py);
    }

    function test_register_ownerNewKey_unlinksAndRetiresOldKey() public {
        registerPair(reg, P1, K1);
        (bytes32 cx, bytes32 cy) = p256Key(P1_C);
        bytes32 newId = p256KeyId(cx, cy);
        assertFalse(reg.isRetired(keyId));

        vm.expectEmit(true, true, false, true, address(reg));
        emit DeviceRegistered(owner, newId, cx, cy);
        assertEq(registerPair(reg, P1_C, K1), newId);

        _assertBound(owner, cx, cy);
        _assertUnbound(keyId); // the old key is unlinked (keyOf(old).owner == 0) ...
        assertTrue(reg.isRetired(keyId)); // ... and retired (v1.2)
        assertFalse(reg.isRetired(newId));

        // v1.2: a retired key is never bound again. Not by another owner, even with the old device's consent ...
        address ownerB = vm.addr(K1_B);
        (bytes32 r, bytes32 s) = _p1Sig(P1, ownerB, px, py);
        bytes memory sig = _k1Sig(K1_B, ownerB, px, py);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(ownerB, px, py, r, s, sig);
        assertEq(reg.keyIdOf(ownerB), bytes32(0));

        // ... and not by the owner that retired it (with fresh signatures)
        (r, s) = _p1Sig(P1, owner, px, py);
        sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
        _assertBound(owner, cx, cy);
        _assertUnbound(keyId);
    }

    /// @dev PERIPHERY-3 / INTEGRATION-5 / ATTACKER-5 at unit level: the old pairing transaction's calldata (both
    ///      signatures are public) replayed by anyone after a rotation reverts KeyTaken and changes nothing.
    function test_revert_replayOldBinding_afterRotation() public {
        (bytes32 oldR, bytes32 oldS) = _p1Sig(P1, owner, px, py);
        bytes memory oldSig = _k1Sig(K1, owner, px, py);
        reg.registerDevice(owner, px, py, oldR, oldS, oldSig);
        bytes32 newId = registerPair(reg, P1_C, K1);

        vm.prank(makeAddr("anyone"));
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(owner, px, py, oldR, oldS, oldSig);

        assertEq(reg.keyIdOf(owner), newId, "rotation not rolled back");
        (bytes32 cx, bytes32 cy) = p256Key(P1_C);
        _assertBound(owner, cx, cy);
        _assertUnbound(keyId);
        assertTrue(reg.isRetired(keyId));
    }

    /// @dev Several rotations retire every earlier key; only the current key stays bound.
    function test_register_rotationChain_retiresEveryEarlierKey() public {
        registerPair(reg, P1, K1);
        bytes32 idB = registerPair(reg, P1_B, K1); // the owner moves to P1_B
        bytes32 idC = registerPair(reg, P1_C, K1); // then to P1_C
        assertTrue(reg.isRetired(keyId));
        assertTrue(reg.isRetired(idB));
        assertFalse(reg.isRetired(idC));
        (bytes32 cx, bytes32 cy) = p256Key(P1_C);
        _assertBound(owner, cx, cy);
        _assertUnbound(keyId);
        _assertUnbound(idB);

        // neither earlier key can come back, for anyone
        (bytes32 bx, bytes32 by) = p256Key(P1_B);
        (bytes32 r, bytes32 s) = _p1Sig(P1_B, owner, bx, by);
        bytes memory sig = _k1Sig(K1, owner, bx, by);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(owner, bx, by, r, s, sig);
        address ownerB = vm.addr(K1_B);
        (r, s) = _p1Sig(P1_B, ownerB, bx, by);
        sig = _k1Sig(K1_B, ownerB, bx, by);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(ownerB, bx, by, r, s, sig);

        // the current key re-registered is still the no-op success (not retired, event emitted)
        (r, s) = _p1Sig(P1_C, owner, cx, cy);
        sig = _k1Sig(K1, owner, cx, cy);
        vm.expectEmit(true, true, false, true, address(reg));
        emit DeviceRegistered(owner, idC, cx, cy);
        assertEq(reg.registerDevice(owner, cx, cy, r, s, sig), idC);
        assertFalse(reg.isRetired(idC));
        _assertBound(owner, cx, cy);
    }

    /// @dev A first registration retires nothing; a no-op re-registration retires nothing.
    function test_isRetired_onlyAfterRotation() public {
        assertFalse(reg.isRetired(keyId));
        assertFalse(reg.isRetired(bytes32(0)));
        registerPair(reg, P1, K1);
        registerPair(reg, P1, K1);
        registerPair(reg, P1_B, K1_B);
        assertFalse(reg.isRetired(keyId));
        (bytes32 bx, bytes32 by) = p256Key(P1_B);
        assertFalse(reg.isRetired(p256KeyId(bx, by)));
        assertFalse(reg.isRetired(bytes32(0)), "the empty keyId of a fresh owner is never retired");
    }

    /// @dev KeyTaken for a retired key comes after both signature checks.
    function test_revert_retiredKey_signaturesCheckedFirst() public {
        registerPair(reg, P1, K1);
        registerPair(reg, P1_C, K1);
        assertTrue(reg.isRetired(keyId));
        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, p256HighS(s), sig);
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        reg.registerDevice(owner, px, py, r, s, hex"00");
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
    }

    /// @dev Any rotation retires the key it replaces, and that key can never be bound again, for any owner.
    function testFuzz_rotation_retiresOldKey(uint256 k1Pk, uint256 otherK1Pk) public {
        k1Pk = bound(k1Pk, 1, SECP256K1_N - 1);
        otherK1Pk = bound(otherK1Pk, 1, SECP256K1_N - 1);
        address o = vm.addr(k1Pk);
        address other = vm.addr(otherK1Pk);
        bytes32 oldId = registerPair(reg, P1, k1Pk);
        registerPair(reg, P1_C, k1Pk);
        assertTrue(reg.isRetired(oldId));
        (bytes32 r, bytes32 s) = _p1Sig(P1, other, px, py);
        bytes memory sig = _k1Sig(otherK1Pk, other, px, py);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(other, px, py, r, s, sig);
        (bytes32 cx, bytes32 cy) = p256Key(P1_C);
        _assertBound(o, cx, cy);
    }

    function test_register_twoDevicesTwoOwners() public {
        registerPair(reg, P1, K1);
        registerPair(reg, P1_B, K1_B);
        (bytes32 bx, bytes32 by) = p256Key(P1_B);
        _assertBound(owner, px, py);
        _assertBound(vm.addr(K1_B), bx, by);
    }

    function testFuzz_register(uint256 p1Pk, uint256 k1Pk) public {
        p1Pk = bound(p1Pk, 1, P256_N - 1);
        k1Pk = bound(k1Pk, 1, SECP256K1_N - 1);
        (bytes32 x, bytes32 y) = p256Key(p1Pk);
        address o = vm.addr(k1Pk);
        bytes32 id = registerPair(reg, p1Pk, k1Pk);
        assertEq(id, p256KeyId(x, y));
        _assertBound(o, x, y);
    }

    // ------------------------------------------------------------------ owner

    function test_revert_zeroOwner() public {
        (bytes32 r, bytes32 s) = _p1Sig(P1, address(0), px, py);
        bytes memory sig = _k1Sig(K1, address(0), px, py);
        vm.expectRevert(IRiparDeviceRegistry.ZeroOwner.selector);
        reg.registerDevice(address(0), px, py, r, s, sig);
    }

    // ------------------------------------------------------------------ P1 (device) signature

    function test_revert_p1_wrongKey() public {
        (bytes32 r, bytes32 s) = _p1Sig(P1_C, owner, px, py); // signed by another P-256 key
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
    }

    function test_revert_p1_signedForAnotherOwner() public {
        address other = vm.addr(K1_B);
        (bytes32 r, bytes32 s) = _p1Sig(P1, other, px, py); // the device bound itself to someone else
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
    }

    function test_revert_p1_otherDomain() public {
        RiparDeviceRegistry other = new RiparDeviceRegistry();
        (bytes32 r, bytes32 s) = p256Sign(P1, other.bindDigest(owner, px, py));
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
    }

    function test_revert_p1_otherChain() public {
        vm.chainId(143);
        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.chainId(10_143);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
    }

    function test_revert_p1_highS() public {
        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, p256HighS(s), sig);
    }

    function test_revert_p1_zeroAndSwapped() public {
        (bytes32 r, bytes32 s) = _p1Sig(P1, owner, px, py);
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, bytes32(0), s, sig);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, bytes32(0), sig);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, s, r, sig);
    }

    function test_revert_p1_keyNotOnCurve() public {
        // the zero key (keyId keccak256(0,0)) and a point off the curve can never be registered
        bytes32[2][3] memory bad = [[bytes32(0), bytes32(0)], [px, bytes32(uint256(py) ^ 1)], [py, px]];
        for (uint256 i; i < bad.length; ++i) {
            (bytes32 r, bytes32 s) = _p1Sig(P1, owner, bad[i][0], bad[i][1]);
            bytes memory sig = _k1Sig(K1, owner, bad[i][0], bad[i][1]);
            vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
            reg.registerDevice(owner, bad[i][0], bad[i][1], r, s, sig);
        }
    }

    function test_revert_p1_checkedBeforeK1() public {
        (bytes32 r, bytes32 s) = _p1Sig(P1_C, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, s, hex"00");
    }

    function testFuzz_revert_p1_garbage(bytes32 r, bytes32 s) public {
        (bytes32 gr, bytes32 gs) = _p1Sig(P1, owner, px, py);
        vm.assume(r != gr || s != gs);
        bytes memory sig = _k1Sig(K1, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadDeviceSignature.selector);
        reg.registerDevice(owner, px, py, r, s, sig);
    }

    // ------------------------------------------------------------------ K1 (owner) signature

    /// @dev no external call before registerDevice, so it pairs with vm.expectRevert
    function _registerWithK1Sig(bytes memory sig) internal {
        reg.registerDevice(owner, px, py, pr, ps, sig);
    }

    function test_revert_k1_wrongSigner() public {
        bytes memory sig = _k1Sig(K1_B, owner, px, py);
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(sig);
    }

    function test_revert_k1_otherDigest() public {
        (bytes32 cx, bytes32 cy) = p256Key(P1_C);
        bytes memory sig = _k1Sig(K1, owner, cx, cy); // the owner bound a different key
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(sig);
        sig = k1Sign(K1, keccak256("not a BindDevice digest"));
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(sig);
    }

    function test_revert_k1_length() public {
        bytes memory sig = _k1Sig(K1, owner, px, py);
        (bytes32 r, bytes32 s, uint8 v) = splitK1(sig);

        // 64 bytes: r‖s only, and the EIP-2098 compact form r‖vs; both are refused
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(abi.encodePacked(r, s));
        bytes32 vs = bytes32(uint256(s) | (uint256(v - 27) << 255));
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(abi.encodePacked(r, vs));

        // 66 bytes: a valid signature plus one trailing byte
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(abi.encodePacked(sig, uint8(0)));

        // empty, 1 byte, 130 bytes (two signatures)
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig("");
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(hex"1b");
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(abi.encodePacked(sig, sig));

        // the genuine 65-byte signature still works afterwards
        _registerWithK1Sig(sig);
        _assertBound(owner, px, py);
    }

    function test_revert_k1_highS() public {
        bytes32 d = reg.bindDigest(owner, px, py);
        bytes memory sig = k1Sign(K1, d);
        bytes memory malleable = k1HighS(sig);
        (bytes32 r, bytes32 s, uint8 v) = splitK1(malleable);
        assertEq(ecrecover(d, v, r, s), owner, "the malleable twin is valid for raw ecrecover");
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(malleable);
    }

    function test_revert_k1_badV() public {
        bytes memory sig = _k1Sig(K1, owner, px, py);
        (bytes32 r, bytes32 s, uint8 v) = splitK1(sig);
        uint8[5] memory vs = [uint8(0), 1, v == 27 ? uint8(28) : uint8(27), 29, 255];
        for (uint256 i; i < vs.length; ++i) {
            vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
            _registerWithK1Sig(abi.encodePacked(r, s, vs[i]));
        }
    }

    function test_revert_k1_zeroRS() public {
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(abi.encodePacked(bytes32(0), bytes32(0), uint8(27)));
    }

    /// @dev Whatever the bytes, a bad owner signature surfaces as BadOwnerSignature (never an OZ ECDSA error).
    function testFuzz_revert_k1_garbage(bytes calldata sig) public {
        vm.assume(keccak256(sig) != keccak256(_k1Sig(K1, owner, px, py)));
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(sig);
    }

    function testFuzz_revert_k1_garbage65(bytes32 r, bytes32 s, uint8 v) public {
        bytes memory sig = abi.encodePacked(r, s, v);
        vm.assume(keccak256(sig) != keccak256(_k1Sig(K1, owner, px, py)));
        vm.expectRevert(IRiparDeviceRegistry.BadOwnerSignature.selector);
        _registerWithK1Sig(sig);
    }

    // ------------------------------------------------------------------ KeyTaken

    function test_revert_keyTaken() public {
        registerPair(reg, P1, K1);
        address ownerB = vm.addr(K1_B);
        // the device key P1 genuinely signs a binding to owner B, B genuinely consents, but P1 is bound to owner A
        (bytes32 r, bytes32 s) = _p1Sig(P1, ownerB, px, py);
        bytes memory sig = _k1Sig(K1_B, ownerB, px, py);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(ownerB, px, py, r, s, sig);

        _assertBound(owner, px, py);
        assertEq(reg.keyIdOf(ownerB), bytes32(0));
    }

    function test_revert_keyTaken_doesNotRetireAnyKey() public {
        registerPair(reg, P1, K1);
        registerPair(reg, P1_B, K1_B);
        (bytes32 bx, bytes32 by) = p256Key(P1_B);
        address ownerB = vm.addr(K1_B);
        (bytes32 r, bytes32 s) = _p1Sig(P1, ownerB, px, py);
        bytes memory sig = _k1Sig(K1_B, ownerB, px, py);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(ownerB, px, py, r, s, sig);
        assertFalse(reg.isRetired(p256KeyId(bx, by)));
        assertFalse(reg.isRetired(keyId));
    }

    function test_revert_keyTaken_doesNotUnlinkOwnersCurrentKey() public {
        registerPair(reg, P1, K1);
        registerPair(reg, P1_B, K1_B);
        (bytes32 bx, bytes32 by) = p256Key(P1_B);
        address ownerB = vm.addr(K1_B);
        // owner B tries to move to A's key: KeyTaken, and B keeps its own key
        (bytes32 r, bytes32 s) = _p1Sig(P1, ownerB, px, py);
        bytes memory sig = _k1Sig(K1_B, ownerB, px, py);
        vm.expectRevert(IRiparDeviceRegistry.KeyTaken.selector);
        reg.registerDevice(ownerB, px, py, r, s, sig);
        _assertBound(ownerB, bx, by);
        _assertBound(owner, px, py);
    }

    function test_views_unknown() public {
        assertEq(reg.keyIdOf(address(0)), bytes32(0));
        assertEq(reg.keyIdOf(makeAddr("nobody")), bytes32(0));
        _assertUnbound(bytes32(0));
        _assertUnbound(keccak256("x"));
        assertFalse(reg.isRetired(bytes32(0)));
        assertFalse(reg.isRetired(keccak256("x")));
    }
}

/// @notice OZ P256 Solidity fallback (no code at 0x0100, like a local EVM).
contract RiparDeviceRegistryTest is RiparDeviceRegistryTestBase {
    function setUp() public override {
        super.setUp();
        _setUpP256Path(false);
    }
}

/// @notice P256VERIFY precompile at 0x0100 (like Monad).
contract RiparDeviceRegistryPrecompileTest is RiparDeviceRegistryTestBase {
    function setUp() public override {
        super.setUp();
        _setUpP256Path(true);
    }

    function test_register_usesPrecompile() public {
        bytes32 d = reg.bindDigest(owner, px, py);
        (bytes32 r, bytes32 s) = p256Sign(P1, d);
        bytes memory sig = k1Sign(K1, d);
        vm.expectCall(P256_PRECOMPILE, abi.encode(d, r, s, px, py));
        reg.registerDevice(owner, px, py, r, s, sig);
        _assertBound(owner, px, py);
    }
}
