// Local chain for the integration test: `anvil --fork-url <Monad testnet> --chain-id 10143` on a free 127.0.0.1 port,
// and the Ripar contracts deployed to it with `forge script` from a PRIVATE COPY of contracts/ (src, script,
// foundry.toml, remappings.txt copied; lib/ linked read-only as a directory junction / symlink). Nothing is ever sent
// to a public chain: every transaction goes to the local anvil, from keys generated by the test.
import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:net';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
export const CONTRACTS = resolve(REPO, 'contracts');
export const FORK_URL = process.env.RIPAR_FORK_URL ?? 'https://testnet-rpc.monad.xyz';

function which(name: string): string | null {
  const envKey = `${name.toUpperCase()}_BIN`;
  if (process.env[envKey]) return process.env[envKey]!;
  const exe = process.platform === 'win32' ? `${name}.exe` : name;
  for (const dir of [...(process.env.PATH ?? '').split(process.platform === 'win32' ? ';' : ':'), 'F:/tools/foundry', join(process.env.HOME ?? '', '.foundry/bin')]) {
    if (dir && existsSync(join(dir, exe))) return join(dir, exe);
  }
  return null;
}

export const ANVIL = which('anvil');
export const FORGE = which('forge');

export async function freePort(): Promise<number> {
  return new Promise((res, rej) => {
    const s = createServer();
    s.once('error', rej);
    s.listen(0, '127.0.0.1', () => {
      const p = (s.address() as { port: number }).port;
      s.close(() => res(p));
    });
  });
}

async function rpc(url: string, method: string, params: unknown[] = []): Promise<unknown> {
  const r = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) });
  const j = (await r.json()) as { result?: unknown; error?: { message: string } };
  if (j.error) throw new Error(`${method}: ${j.error.message}`);
  return j.result;
}

export interface Anvil {
  url: string;
  port: number;
  proc: ChildProcess;
  log: () => string;
  stop: () => void;
}

/** starts the fork; resolves null (with the reason) when it cannot start, so the caller can skip */
export async function startForkedAnvil(timeoutMs = 90_000): Promise<{ anvil: Anvil | null; reason?: string }> {
  if (!ANVIL) return { anvil: null, reason: 'anvil not found (PATH, ANVIL_BIN or F:/tools/foundry)' };
  const port = await freePort();
  let out = '';
  const proc = spawn(ANVIL, ['--fork-url', FORK_URL, '--chain-id', '10143', '--port', String(port), '--host', '127.0.0.1', '--silent'], {
    stdio: ['ignore', 'pipe', 'pipe'],
    windowsHide: true,
  });
  proc.stdout?.on('data', (c: Buffer) => (out += c.toString()));
  proc.stderr?.on('data', (c: Buffer) => (out += c.toString()));
  let exited = false;
  proc.on('exit', () => (exited = true));
  const stop = (): void => {
    if (!exited) proc.kill();
  };
  process.once('exit', stop);
  const url = `http://127.0.0.1:${port}`;
  const t0 = Date.now();
  while (Date.now() - t0 < timeoutMs) {
    if (exited) return { anvil: null, reason: `anvil exited: ${out.slice(-500)}` };
    try {
      const id = await rpc(url, 'eth_chainId');
      if (id === '0x279f') {
        await rpc(url, 'eth_getBlockByNumber', ['latest', false]);
        return { anvil: { url, port, proc, log: () => out, stop } };
      }
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  stop();
  return { anvil: null, reason: `the fork of ${FORK_URL} did not start within ${timeoutMs} ms: ${out.slice(-500)}` };
}

/** refreshes the private copy of contracts/ (never touches contracts/ itself; lib is linked, never deleted) */
export function preparePrivateContracts(work: string): string {
  const dst = resolve(work, 'contracts');
  mkdirSync(dst, { recursive: true });
  for (const d of ['src', 'script']) {
    rmSync(resolve(dst, d), { recursive: true, force: true }); // real copies only
    cpSync(resolve(CONTRACTS, d), resolve(dst, d), { recursive: true });
  }
  for (const f of ['foundry.toml', 'remappings.txt']) writeFileSync(resolve(dst, f), readFileSync(resolve(CONTRACTS, f)));
  const lib = resolve(dst, 'lib');
  if (!existsSync(resolve(lib, 'forge-std'))) {
    if (process.platform === 'win32') {
      const r = spawnSync('cmd', ['/c', 'mklink', '/J', lib.replace(/\//g, '\\'), resolve(CONTRACTS, 'lib').replace(/\//g, '\\')], { encoding: 'utf8' });
      if (r.status !== 0) throw new Error(`mklink /J failed: ${r.stdout} ${r.stderr}`);
    } else {
      spawnSync('ln', ['-s', resolve(CONTRACTS, 'lib'), lib]);
    }
  }
  rmSync(resolve(dst, 'deployments', '10143.json'), { force: true });
  return dst;
}

/** forge script script/Deploy.s.sol --broadcast against the fork; returns the deployments JSON path */
export function deployRipar(contractsDir: string, rpcUrl: string, deployerKey: string, workflowOwner: string): string {
  if (!FORGE) throw new Error('forge not found (PATH, FORGE_BIN or F:/tools/foundry)');
  const r = spawnSync(
    FORGE,
    ['script', 'script/Deploy.s.sol', '--rpc-url', rpcUrl, '--broadcast', '--private-key', deployerKey],
    {
      cwd: contractsDir,
      encoding: 'utf8',
      env: { ...process.env, RIPAR_WORKFLOW_OWNER: workflowOwner, FOUNDRY_DISABLE_NIGHTLY_WARNING: '1' },
      maxBuffer: 64 << 20,
      timeout: 600_000,
      windowsHide: true,
    },
  );
  const path = resolve(contractsDir, 'deployments', '10143.json');
  if (r.status !== 0 || !existsSync(path)) {
    throw new Error(`forge script failed (${r.status}):\n${(r.stdout ?? '').slice(-3000)}\n${(r.stderr ?? '').slice(-3000)}`);
  }
  return path;
}
