// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

/// @notice Known-answer EIP-712 vectors for the RiparPulseCosign domain, copied from
///         firmware/test/host/vectors_eip712_abi.h (generated by firmware/tools/ref_eip712.py gen, seed 712, an
///         independent Python EIP-712 reference). The firmware host tests check the C++ digests against the same
///         values, so passing here means contract and device hash byte-for-byte alike.
/// @dev Transcribed mechanically from that header (HUMAN_APPROVALS, REVOKES, PANICS, DOMAINS[RiparPulseCosign]).
///      If the firmware vectors are regenerated, re-transcribe them; do not edit values by hand.
library FirmwareVectors {
    struct HumanApprovalVector {
        bytes32 delegationHash;
        address delegator;
        address redeemer;
        address target;
        uint256 value;
        bytes32 callDataHash;
        uint256 nonce;
        uint64 expiry;
        bytes32 presenceHash;
        bytes32 structHash;
        uint256 chainId;
        address enforcer;
        bytes32 digest;
    }

    struct RevokeVector {
        bytes32 delegationHash;
        bytes32 structHash;
        uint256 chainId;
        address enforcer;
        bytes32 digest;
    }

    struct PanicVector {
        uint64 minEpoch;
        bytes32 structHash;
        uint256 chainId;
        address enforcer;
        bytes32 digest;
    }

    struct DomainVector {
        uint256 chainId;
        address enforcer;
        bytes32 separator;
    }

    function humanApprovals() internal pure returns (HumanApprovalVector[] memory v) {
        v = new HumanApprovalVector[](12);
        v[0] = HumanApprovalVector({
            delegationHash: bytes32(0xe7a6ffea81a34352d0935839a179495c88ed6c72ef2488434253f78dbd72c048),
            delegator: address(uint160(0x00ffffffffffffffffffffffffffffffffffffffff)),
            redeemer: address(uint160(0x0093fb3965a10d9ceb6cd7e80bb16b5cbde4156391)),
            target: address(uint160(0x00ad634329f67b3b16bfcde3adaa0a423750f365f2)),
            value: uint256(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff),
            callDataHash: bytes32(0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470),
            nonce: uint256(0x00000000000000000000000000000000000000000000000000000000000000ee),
            expiry: 147,
            presenceHash: bytes32(0x1e7c897b72ebb2d0d09ecbdfd639098a5cdcfd0b3c0a482d1cbf791c2fbbf270),
            structHash: bytes32(0x3544171275c0da1de6a13cf13d0fbef92f85f49ae8d7803357f3c9a6c5fc85a2),
            chainId: 1,
            enforcer: address(uint160(0x00ab4f25baa4e59398d72615822698e5df33fb39e0)),
            digest: bytes32(0x9454d357b563360fe7f77a3bee7870fd8a7c806bf00d07c568ed4ee887cdf7a3)
        });
        v[1] = HumanApprovalVector({
            delegationHash: bytes32(0x15d58cf24465f96d42c339692dad4268a7cf94a25734ede2a9fc7f39efc112e8),
            delegator: address(uint160(0x00cedca57b4fc5f59a0fd458e6ac3bf69f433db769)),
            redeemer: address(uint160(0x00905b656b647949ea2ebbd7c772bc6a0b2ace3e9b)),
            target: address(uint160(0x00935818cc015f2712dc510cec1e3ff9965cf11751)),
            value: uint256(0x00000000000000000000000000000000000000000000000181cfa3704ad5345a),
            callDataHash: bytes32(0xe963a194eab08a2d5c75f3f873eaaeb20e0423cd129076d5b1d92ca200ca9d69),
            nonce: uint256(0x0000000000000000000000000000000000000000000000006a9fa88d15dfa849),
            expiry: 0,
            presenceHash: bytes32(0x9bc2c4b81b5dfcdba0004dd48afd8e3788e9f2d704a8be1daa48790de2cc3771),
            structHash: bytes32(0x991d3d18114c161c3242f52ab77d169fce14d576de34a342f5b53fc936a65ca3),
            chainId: 143,
            enforcer: address(uint160(0x00691315997d252c4ce1cd9452128d4d71aa83bfe7)),
            digest: bytes32(0x1cbc62563abb1010257513cdba7e122f383ae888ee926f1ddcb2e8aa9d6aee80)
        });
        v[2] = HumanApprovalVector({
            delegationHash: bytes32(0xca13cd60aef49400be1c2c0ccedd33dd9976c84b9fb89a162c11251cbf452db4),
            delegator: address(uint160(0x006e4379da7c7a1229b05550ac39c44c4c1c632ddf)),
            redeemer: address(uint160(0x003eb18480bba535cbfb0c59db74e19fe1f7ac4db2)),
            target: address(uint160(0x005a8460d9abe024f8632bc436c81cd01edf30c8e1)),
            value: uint256(0x158789b3029f3086a46f06fe120874b561c4b46df35fd58c8c35e3d9ac5b48ec),
            callDataHash: bytes32(0x92ce2e1cd10d7dbd92c47c7e1659a1df8545eb951637ec3957023823bd3047b5),
            nonce: uint256(0x264eb5683f588f5c4bfd49ff944c96da2ab187181473bb60766560240b2ba865),
            expiry: 1144213559,
            presenceHash: bytes32(0xa2c09547d72827dbd05eb8c1db20c4858928a6440bbd9106e743c87b9536ea0b),
            structHash: bytes32(0xd3277cb7cef06269564e1febe27323c632c9493ff09d1d4be2327117ca9d5f73),
            chainId: 10143,
            enforcer: address(uint160(0x007860debdd7b744b3103f94ee526de8353d0b04fc)),
            digest: bytes32(0xef60995ca9e310a350bcb8a2065e993ca0a95e60fe6cea8d3fe38bcf4b93f39c)
        });
        v[3] = HumanApprovalVector({
            delegationHash: bytes32(0x4f57c917e68d57afb759d49c26a8d948211690634ff77e606aed38a3e4f2588c),
            delegator: address(uint160(0x00a67583e3ecc49c1e9749152e604b4aa5032db33c)),
            redeemer: address(uint160(0x00cff69d3559bb544a34c8213423a330f82ffcf5da)),
            target: address(uint160(0x00d9a4dc2662de960f84445038d258dabc8c169e73)),
            value: uint256(0x000000000000000000000000000000000000000000000000000000000000006e),
            callDataHash: bytes32(0xeb6afc49e8f646bb59283d03e7f5e72bc5c83902f1bf04c790bbcb31a5293082),
            nonce: uint256(0x000000000000000000000000000000000000000000000001e109253acfb439be),
            expiry: 1656634997,
            presenceHash: bytes32(0x5c2a1f71648ebfff7f28eaa63ed803510ef55b3ff4a30c40a3717565f854e130),
            structHash: bytes32(0x33596750e29b6bec9b0f41ed35ef342729734628c5259768b5b1f64164203895),
            chainId: 18446744073709551615,
            enforcer: address(uint160(0x006e53e156b153aab979407fcb00e4d122af9a5092)),
            digest: bytes32(0xf13a86480039d5b306c0b3241496e9837143606741282743025c095d259ce18b)
        });
        v[4] = HumanApprovalVector({
            delegationHash: bytes32(0x0b4bf06fe945a05da06a61f9e646436825a0ab764217ff6abf4e10b1633017d3),
            delegator: address(uint160(0x00e5e72163d144bb05af34665212f98da7cfa90c28)),
            redeemer: address(uint160(0x00660753dcfaf1e2a9e3a7e0f0bd48715fdbd09069)),
            target: address(uint160(0x001fac26031c77dcca7c11af74a5c3fc72fb2fe872)),
            value: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
            callDataHash: bytes32(0xea73d9ec82a981142684f1c98ca9d5455b8cc4cf1229200c5b7f772ad9abf424),
            nonce: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
            expiry: 0,
            presenceHash: bytes32(0x75e5483c7e05bd218bb795841d879298cc7df06a84b2db1b466f6c7fcada17bf),
            structHash: bytes32(0x7f5fe31bbe4256ac2abb811ff35d5c1c168bbd99175632d830664118ebc86fcf),
            chainId: 10143,
            enforcer: address(uint160(0x00b1a97240304b8bc35035135af5afffb7f4760684)),
            digest: bytes32(0x330793c75ae62b92d344e84555db58e5c880a542dbd1f5701b572cec44e2afb2)
        });
        v[5] = HumanApprovalVector({
            delegationHash: bytes32(0x614cadc79a08538b29dea1216bea601f3929277131914d9e538c54969d713e49),
            delegator: address(uint160(0x00663c88c373682d7ee845854b86abd4471dcc9970)),
            redeemer: address(uint160(0x00dc4b887600aaf1f2e554cab868c4a35aaed100c6)),
            target: address(uint160(0x00f3ab8a96b05e6ca026abfe9d3dd16a3f2ed3ddb4)),
            value: uint256(0x0000000000000000000000000000000000000000000000004f948a1eecd147d1),
            callDataHash: bytes32(0x9e9b0a8ae54e18caf983eb2042ee91062faf5839bbb79eb73b12e1696c5ceeb9),
            nonce: uint256(0x00000000000000000000000000000000000000000000000000000000000000c9),
            expiry: 2385153686,
            presenceHash: bytes32(0x292e6353ddc152c0fcb9937e122fa1ebc49b2eeca5eceb27b947e4622b09abce),
            structHash: bytes32(0xc58c4cf01f86f04dc2f8ee38b218a82ff3e17a4d21d1b2197e8f46d69251f2bc),
            chainId: 18446744073709551615,
            enforcer: address(uint160(0x006e2861331e71bc795af8595fc45609638049a1da)),
            digest: bytes32(0xf9a51bce342a8afe00c61ddb254ea9fb1758bee7f3e3450df426f576592f6716)
        });
        v[6] = HumanApprovalVector({
            delegationHash: bytes32(0xb5da9d330ef6391a48be7d30b15ec61dc8f8e278a20ea3b112aa9e94f214189d),
            delegator: address(uint160(0x00f818f480ca35b7a1b5d2feccefdfb2604db34268)),
            redeemer: address(uint160(0x0008fe65a2d0d1a465d6c7b224d9b6dea4c156a993)),
            target: address(uint160(0x004cab6c0ebbd0f8ae35b3337e2e75cc2be92c27bb)),
            value: uint256(0x0000000000000000000000000000000096bdf1cddb2b137363db73fe6302ff10),
            callDataHash: bytes32(0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470),
            nonce: uint256(0x000000000000000000000000000000000000000000000000b32c3f2ca7b44fcb),
            expiry: 1979772380,
            presenceHash: bytes32(0xd4addd4a203989d5170d7510cdc2cabf31af4e389186e694b945e9e7430785b3),
            structHash: bytes32(0x8a2a1c3b39169947bfcf6a358e71fbdfb2d30c71723fbc1aa5f101ad90eee6cd),
            chainId: 18446744073709551615,
            enforcer: address(uint160(0x00b0fddd9a724abb91f8411abfd09b8aafbf48f4a2)),
            digest: bytes32(0xcf62c938b80e0ea45ab3b9d7a41c335813909dce34e904c3d909c35718920090)
        });
        v[7] = HumanApprovalVector({
            delegationHash: bytes32(0x9619015892581a27c0e9515a721d2d6640c9f17628e4faa2c10d7c585440a312),
            delegator: address(uint160(0x009616ed83023b57eed50bf2830966ad2efb12e29e)),
            redeemer: address(uint160(0x00b275b7e6064c42ffa2a8f2b63c253977e4461445)),
            target: address(uint160(0x00ffffffffffffffffffffffffffffffffffffffff)),
            value: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
            callDataHash: bytes32(0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470),
            nonce: uint256(0x000000000000000000000000000000000000000039da5794b8916391e3ff7b48),
            expiry: 7386240841538948748,
            presenceHash: bytes32(0x8532d993c163c93556d686e1c70ae6353bd58ba364cef7589bd85336f0cdaff4),
            structHash: bytes32(0x106c32cbd70726c0bf7fede09dcf75349e3b9f1b2ab976d716657b9c5e876673),
            chainId: 31337,
            enforcer: address(uint160(0x00ec3f39a89e97ca2608f0da871f1ecbec0bc2edc3)),
            digest: bytes32(0xfa2c6b1611ab65112c81c0da8ae1e996e5680fde4f7a476d649c5c8ea29eba67)
        });
        v[8] = HumanApprovalVector({
            delegationHash: bytes32(0xb88a302a123822eaa850a1f4443a5af7fc1c71ecb78f71293aff38298fe130a7),
            delegator: address(uint160(0x000000000000000000000000000000000000000000)),
            redeemer: address(uint160(0x00832f65408be7e130ebbfc0173c0391eea6b30999)),
            target: address(uint160(0x00f2f133a886325eda48eab27fb3638e7b69e1459f)),
            value: uint256(0x07b8cd108401769b273b5aa5e52dfb5d0fa0c5b52a6ab0be9c4ad358e9b307ea),
            callDataHash: bytes32(0xad6ed043fc3777821e2d9baf0a57e2cd6be91b5b122609766b11fed8831e3605),
            nonce: uint256(0x00000000000000000000000000000000b3c005b5278cbe0ebc815fa166d8b8c4),
            expiry: 112,
            presenceHash: bytes32(0x4e13ef4c435ef48091e74a26e6ffb231dff0ae954af2841a5ece8ad255a05515),
            structHash: bytes32(0xc5950678029eb23e0df20a4c7834d940beb567bd8c5661bdcadd1cc6db402beb),
            chainId: 0,
            enforcer: address(uint160(0x00740fbb3485c232dfb433a5a84b68c40d7c7f1365)),
            digest: bytes32(0x51857a167f47977fb3f3fe1fc4cc70fe69e1ca4c4ce9f481229b962afa42455a)
        });
        v[9] = HumanApprovalVector({
            delegationHash: bytes32(0x6f8a58e27a577bc6c83b86bfd2c5086ddfa0ff352327a0c8af0e96dbaa5bcc66),
            delegator: address(uint160(0x00ffffffffffffffffffffffffffffffffffffffff)),
            redeemer: address(uint160(0x008baaec0e4cdc748515aea30183d1c13f13930576)),
            target: address(uint160(0x001148144018712b0bffabdc8ef90aba444a48f582)),
            value: uint256(0x000000000000000000000000000000000000000000000000000000001d23f49f),
            callDataHash: bytes32(0x82179d8f2467f8d6c9175f18a77d00cf652a0be6cd80773d8dc3becafa3605ad),
            nonce: uint256(0x0000000000000000000000000000000000000000000000000000000000000078),
            expiry: 198,
            presenceHash: bytes32(0xa78cfb4bc71928b6c39fa8de8b1f3551583042855d6813b4362b94dc92dc8e59),
            structHash: bytes32(0x8c2df8625a708ac1bfd4f0cbcb0717c7ae01072200b6bba5f193cc77c3a04793),
            chainId: 31337,
            enforcer: address(uint160(0x00dc11ae1219807906fde11411523a8835940ccdd2)),
            digest: bytes32(0x92540e9a02192eeb3b5aecb6fa4a4122f1756a74a5bc5e3f0791b695cb1e82a0)
        });
        v[10] = HumanApprovalVector({
            delegationHash: bytes32(0x2be3cf7593d6043e29b1c734f26d3f2299bd26949b3dee5906183cf5f4354190),
            delegator: address(uint160(0x00314ed7eabb54f484f40f57961ef84f8704209d7b)),
            redeemer: address(uint160(0x00720e61299af302d49e377b3b6b9b9ce6b3e86f63)),
            target: address(uint160(0x00acecbfb6bd146c9ee60a3030e7c32d5b1d9a40fd)),
            value: uint256(0x40a9cde0849bd1a251eaaac259b30256f5fb5247c217afdbc197e8d778234cdd),
            callDataHash: bytes32(0xf17537937f12d0650a220039986c773d6143fa24de213eab6deffa889ee89722),
            nonce: uint256(0x0000000000000000000000000000000000000000000000006f5a21dbbb1a721b),
            expiry: 618065913,
            presenceHash: bytes32(0xd825da3383552da6a32749440d37447612a476f2d1bd181a4e8f51e3151a672d),
            structHash: bytes32(0x0077d1ea487f5d3ce1e59bdcacfeb0863b22dae86dfb1e338cad294fe6205197),
            chainId: 31337,
            enforcer: address(uint160(0x003d6a5b3c0da85007e61327e5ad217d20256b9307)),
            digest: bytes32(0x4c305dada7e244e1a7c592475bc703e593203451cb32849c958056abc020f010)
        });
        v[11] = HumanApprovalVector({
            delegationHash: bytes32(0xca4086b350c356ed3cfd1be3767fae87a7b1c1fa4f0168befba63172c22cbcf2),
            delegator: address(uint160(0x00da38e4d06b797c2f6d8f59806968fa4487de5725)),
            redeemer: address(uint160(0x000000000000000000000000000000000000000000)),
            target: address(uint160(0x009247794d8d3be314ce3114a7e43bf2e5d64c0e40)),
            value: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
            callDataHash: bytes32(0x78a94fb678f69ef34d565d3074f80af2bbccb75aa5327446d6de16c5aa7de2e0),
            nonce: uint256(0x0000000000000000000000000000000000000000000000000000000000000058),
            expiry: 0,
            presenceHash: bytes32(0x5b7a218d98e57f1c7da1c5b43e2ac3736b51c00f15e06de3f0daccec6d925168),
            structHash: bytes32(0xd839566abc68d22ff69fbf63183f189b44f3ace3cc5e65ebbea90e8350a5200f),
            chainId: 0,
            enforcer: address(uint160(0x00da4bad8e85ee5537417ad7f79f3485b6ba503653)),
            digest: bytes32(0x0030d7510cd6520152d32e2da174b78cc0e42fc2cca194698c178c2e00e08524)
        });
    }

    function revokes() internal pure returns (RevokeVector[] memory v) {
        v = new RevokeVector[](6);
        v[0] = RevokeVector({
            delegationHash: bytes32(0xae2615a68a858a2a417caa903ca237b2c96df1c987f82ca1e6084cdf531b4a48),
            structHash: bytes32(0x1681c3f91174b0e67f14b07ebded11dc8d3a60c38cab9c6b9de8ea36df6e9cd5),
            chainId: 143,
            enforcer: address(uint160(0x00dff720a58e78f4e8c5eff02b23eed11729f364ed)),
            digest: bytes32(0x81e7e69967ad8ba46a07435f52696e015798896a404324e07e09958bedcee2a8)
        });
        v[1] = RevokeVector({
            delegationHash: bytes32(0x49579bd7bd90df677411ad3a5a627f8ca9b9c2ce59251313fc6198122b13558b),
            structHash: bytes32(0x80dba72f9ef32ae64c216ce171a4c9f1362fc60ed844731256558914f2db05af),
            chainId: 0,
            enforcer: address(uint160(0x005675f81ced480d1b9ef50e9e9d67a446e57e3dcf)),
            digest: bytes32(0x9ae8e952a20d954d20458e79f3f1602681e7b16b98cfa32436bc1355ce30deb4)
        });
        v[2] = RevokeVector({
            delegationHash: bytes32(0xd8e5b6cdbe25e22e344c69235db4f06fb26d278cb59fe35aeed39813d193fe5b),
            structHash: bytes32(0x6d80cea36e4035fa3ff3abc846aec86d8e762ed1189d172b950dff4a7ef575e7),
            chainId: 143,
            enforcer: address(uint160(0x00ffffffffffffffffffffffffffffffffffffffff)),
            digest: bytes32(0x851c87fd44c1e67bf503a1c20b197c1e765d47d719ecf0d3e8e2467052116fae)
        });
        v[3] = RevokeVector({
            delegationHash: bytes32(0x9c52a41e16109f3e4f6d7dc293b158908426fc1d5c653a25d6c4bb3dd25277a4),
            structHash: bytes32(0x387903bcdab9c5c06efb7924143798ec0ec66b20dadad504efc2bade581e63b5),
            chainId: 10143,
            enforcer: address(uint160(0x0022d5e4f582b915b9e2d955a77953894d9b0aa84a)),
            digest: bytes32(0x1f0435814c230f144b999a67bcb774985c5b8c2da5c54d38521d44d0f1f23bf8)
        });
        v[4] = RevokeVector({
            delegationHash: bytes32(0xa3b7b3853a83934d93e7f18eabdbceb8eca0f455fadb63d75ddd57f050480a62),
            structHash: bytes32(0xe641e108aa25218a0da6a5d89aa3d5bdbe3434922106ed39e3f38cb43e943b79),
            chainId: 143,
            enforcer: address(uint160(0x00c3599178b1a95c835189e3566ea798a5059be03b)),
            digest: bytes32(0x881617685713e56eb7f3688e1e49de586232a07bfe9b8671329ee65c0f3402a9)
        });
        v[5] = RevokeVector({
            delegationHash: bytes32(0x0000000000000000000000000000000000000000000000000000000000000000),
            structHash: bytes32(0x36c526644f64b4fe602e8ef5cf86202f6b464dc7fa4073d0dd3628b767d21154),
            chainId: 10143,
            enforcer: address(uint160(0x0028aec1e1cbd1339100c60299848d77c2d75d0d28)),
            digest: bytes32(0x4eaf816e8a762b2250b7045d3c94845b7b33e7949ce4a6f0fdc3322f1c3682e3)
        });
    }

    function panics() internal pure returns (PanicVector[] memory v) {
        v = new PanicVector[](6);
        v[0] = PanicVector({
            minEpoch: 0,
            structHash: bytes32(0x465c0d70eecf4a6fe46ea7c5288e9c4269136906ba3de1a872e68893f0474914),
            chainId: 1,
            enforcer: address(uint160(0x0010916a0f1300b5dafc8b2bde52c9cfb87abddc69)),
            digest: bytes32(0xe47b659f8d376bf7ccaaba96e954e4177180f4d479d329a6690c6ff2dd98a127)
        });
        v[1] = PanicVector({
            minEpoch: 1,
            structHash: bytes32(0x04d0ed6f68b8dc5d1395bf61642dcda0f813394ab07d14a9a5b305bd3d82af1d),
            chainId: 143,
            enforcer: address(uint160(0x000742fa200a4b5426d738cecd53531dffa3172fdc)),
            digest: bytes32(0x21eaae0bfac6dc77760d884347478711f7e019de41854ef8038e3158f90826a3)
        });
        v[2] = PanicVector({
            minEpoch: 18446744073709551615,
            structHash: bytes32(0x7445e5696f9c6ce5e619c654c167ea77d11f6cc004556dbe713484b48e34eb31),
            chainId: 18446744073709551615,
            enforcer: address(uint160(0x003a45c0847aa9b28225f802f42393f7b889e33f4a)),
            digest: bytes32(0xa8ca39867af6c8ffb771e226783ba9e0cc5bc3991d36a210e09ef784ad421f01)
        });
        v[3] = PanicVector({
            minEpoch: 4294967296,
            structHash: bytes32(0xd2d86018304e1e0dd772922f976cf7ce8c0bb689c77222b5a0a95ce97c587b9b),
            chainId: 6682290039538184082,
            enforcer: address(uint160(0x007dd0d928c7e780a7d11723c2f22f1e47d0b9562b)),
            digest: bytes32(0x69310ee983d0501d6d0813a345dceb64c9eb999388ac652a7f8f7dc115109c22)
        });
        v[4] = PanicVector({
            minEpoch: 10269089422478936172,
            structHash: bytes32(0x9a3a4db7617e9d1b5f88baa50fe8fa9adf77bb3b2734e7c137aed0b239b8c12d),
            chainId: 31337,
            enforcer: address(uint160(0x00ccd787acf28202afe8887d3abfa186f895f03ba4)),
            digest: bytes32(0x8ddf6bbe47e24015313fe0bb0e7430d22b8da58ceeb6d1af2308b74e05574704)
        });
        v[5] = PanicVector({
            minEpoch: 445695060974,
            structHash: bytes32(0x2d04b47d61c5a3978207284c3c67b4969146265e517528fee54586430b835c65),
            chainId: 18446744073709551615,
            enforcer: address(uint160(0x00c271b86c95a4c5d068ba221351e1cbd1b952abbb)),
            digest: bytes32(0x3a67bdfcb8081d79351caa7f3804c902d94952624790f90ab90b043fdb1718d4)
        });
    }

    function domain() internal pure returns (DomainVector memory) {
        return DomainVector({
            chainId: 1,
            enforcer: address(uint160(0x00d60f5c3a7b849e4e3bba03c8133637d7c3d61572)),
            separator: bytes32(0x1193ab6ebe4d0085012569432b8b556836e8213571720f2ccd879196defafe97)
        });
    }
}
